Repository rundeck/rundeck, pull requests merged in 2018-03, with the labels that each got.

#3152 SCM usability enhancement
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
  docs/en/plugins-user-guide/bundled-plugins.md
  docs/en/plugins-user-guide/git-plugins.md
  docs/en/plugins-user-guide/toc.conf
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Export.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Import.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/SetupTracking.groovy
  plugins/git-plugin/src/main/resources/resources/i18n/git-import.messages.properties
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/config/ExportSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/config/ImportSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/views/scm/_pluginConfigList.gsp
  test/api/test-scm-git-plugin-inputs.sh
Labels: enhancement

#3126 serverNodeUUID field to varchar
  rundeckapp/grails-app/domain/rundeck/JobFileRecord.groovy
Labels: release-notes/breaking

#3191 correct optional options when creating a project
  docs/en/administration/project-setup.md
Labels: documentation

#3206 Add free-stuff link to first-run text
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
Labels: release-notes/exclude

#3208 Templates for generated Docs updated: remove site nav, update footer
  docs/en/style.css
  docs/en/templates/footer.template
  docs/en/templates/header.template
  docs/en/templates/html.template
Labels: release-notes/exclude
