Repository rundeck/rundeck, pull requests merged in 2019-11, with the labels that each got.

#5330 FIX: Converted encryptor type variable within the storage configuration template to lower-case
  docker/official/remco/templates/rundeck-config-storage.properties
Labels: backport-to-3.0, backport-to-3.1, docker, v3.2.0

#5329 FIX: Rename path variable within storage configuration template
  docker/official/remco/templates/rundeck-config-storage.properties
Labels: docker, v3.2.0

#5387 Enhancement: step search improvement
  rundeckapp/grails-app/assets/javascripts/filterStepPluginsKO.js
  rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js
  rundeckapp/grails-app/views/common/_stepPluginsfilterStringHelp.gsp
  rundeckapp/grails-app/views/execution/_wfAddStep.gsp
  rundeckapp/grails-app/views/framework/_stepPluginFilterInputGroup.gsp
Labels: enhancement, v3.2.0

#5449 Restores a method that was removed by a merge.
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Labels: release-notes/exclude, v3.2.0

#5450 Prune Webhook token output from unexpected places
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
Labels: v3.2.0

#5402 Responsive Job Title - Fixes #5342
  rundeckapp/grails-app/assets/scss/custom/mainbar.scss
  rundeckapp/grails-app/assets/scss/paper/_responsive.scss
Labels: backport-to-3.1

#5456 Docker - Move features into separate template
  docker/official/remco/resources.d/rundeck-config-features.properties.toml
  docker/official/remco/templates/rundeck-config-features.properties
  docker/official/remco/templates/rundeck-config.properties
Labels: docker, release-notes/exclude, v3.2.0

#5460 Fix duplicate ACE editors being added on job edit page.
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Labels: release-notes/exclude, v3.2.0

#5459 Table word wrap issue, fixes #5384
  rundeckapp/grails-app/views/user/_token.gsp
Labels: 3.2.x, backport-to-3.1, bug, gui

#5466 Fix: run job with extra metadata doesn't work
  rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobStateServiceSpec.groovy
Labels: 3.2.x

#5476 Docker variable to enable/disable job lifecycle plugin
  docker/official/remco/templates/rundeck-config-features.properties
Labels: docker, release-notes/exclude, v3.2.0

#5483 Enable the repository feature with in-app config
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/grails-app/views/menu/plugins.gsp
  rundeckapp/grails-app/views/menu/systemInfo.gsp
  rundeckapp/repository/grails-app/conf/plugin.yml
  rundeckapp/repository/grails-app/controllers/repository/UrlMappings.groovy
  rundeckapp/repository/grails-app/views/artifact/index.gsp
  rundeckapp/repository/src/main/groovy/repository/RepositoryGrailsPlugin.groovy
Labels: v3.2.0

#5485 Restructure so we do not need to add each feature explicitly
  docker/official/remco/templates/rundeck-config-features.properties
Labels: docker, v3.2.0

#5470 Fix #5465 project import webhook fails
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/src/test/resources/test-rdproject.jar
Labels: backport-to-3.1, v3.2.0

#5482 Fix #5480 by moving the location of the input element.
  rundeckapp/grails-app/views/menu/storage.gsp
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5473 Fix #5468 joblifecycle plugin error handling
  core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobOptionImpl.java
  examples/example-java-job-lifecycle-plugin/src/main/java/org/rundeck/example/plugin/ExampleJobLifecyclePlugin.java
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/JobLifecyclePluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobLifecyclePluginServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x, release-notes/exclude

#5484 enable executionLifecyclePlugin by default
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.2.x, release-notes/exclude

#5492 Fix #5488. Wrong boolean check for execution lifecycle feature
  rundeckapp/grails-app/services/rundeck/services/ExecutionLifecyclePluginService.groovy
Labels: release-notes/exclude, v3.2.0

#5499 Job rescheduling issue
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: v3.2.0

#5502 Fix #5501 saving filters should work
  rundeckapp/grails-spa/src/components/activity/activityFilter.vue
Labels: backport-to-3.1, v3.2.0

#5503 Fix #5377. Upgrades Jackson library to the latest release.
  gradle.properties
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5509 Fixes #4263. Link to doc was pointing to an old location.
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5508 Fixes #5494. Constrain webhook post url to POST http method.
  rundeckapp/webhooks/grails-app/controllers/webhooks/UrlMappings.groovy
  rundeckapp/webhooks/grails-app/controllers/webhooks/WebhookController.groovy
  rundeckapp/webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Labels: backport-to-3.1, v3.2.0

#5519 Allow to run jobs using variables with keystorage and required yes
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: 3.2.x, backport-to-3.0, backport-to-3.1

#5498 Fixes #5497 by ensuring the auth token type is set to a valid value.
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Labels: backport-to-3.1, v3.2.0

#5525 Enhance Webhook UI - add a placeholder text for the Post Url field.
  rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
Labels: backport-to-3.1, v3.2.0

#5524 Add webhook type to AuthConstants.
  core/src/main/java/org/rundeck/core/auth/AuthConstants.java
Labels: backport-to-3.1, release-notes/exclude, v3.2.0

#5532 variable execution.succeededNodeList to observe real node execution on notification
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x, backport-to-3.0, backport-to-3.1

#5530 Adding the private context data to script node executor plugins
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutor.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutorSpec.groovy
Labels: v3.2.0

#5523 new version of ansible plugin (3.1.0)
  rundeckapp/build.gradle
Labels: v3.2.0

#5543 Vue and UI trellis updates
  rundeckapp/grails-app/assets/scss/custom/expand.scss
  rundeckapp/grails-app/assets/scss/custom/mainbar.scss
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
  rundeckapp/grails-spa/package.json
  rundeckapp/grails-spa/src/components/central/main.ts
  rundeckapp/grails-spa/src/components/motd/main.js
  rundeckapp/grails-spa/src/components/tour/main.js
  rundeckapp/grails-spa/src/pages/project-activity/main.js
  rundeckapp/grails-spa/src/pages/project-dashboard/main.js
  rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectPluginConfig.vue
  rundeckapp/grails-spa/src/pages/project-nodes-config/i18n.js
  rundeckapp/grails-spa/src/pages/project-nodes-config/main.js
  rundeckapp/grails-spa/src/utilities/vueEventBus.ts
Labels: 3.2.x

#5545 Adds automagic copyright date
  rundeckapp/grails-app/views/common/_footer.gsp
Labels: backport-to-3.0, backport-to-3.1

#5534 Task/5504/add support type
  rundeckapp/grails-app/assets/scss/custom/sidebar.scss
  rundeckapp/grails-app/assets/scss/pages/login.scss
  rundeckapp/grails-app/views/common/_footer.gsp
  rundeckapp/grails-app/views/common/_sidebar.gsp
  rundeckapp/grails-app/views/menu/welcome.gsp
Labels: backport-to-3.0, backport-to-3.1, critical

#5550 Change Runbook text to Readme
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
Labels: 3.2.x
