Repository rundeck/rundeck, pull requests merged in 2019-12, with the labels that each got.

#5560 Reduces text size
  rundeckapp/grails-app/views/common/_footer.gsp
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5559 Address Webhook UI feedback issues
  rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
  rundeckapp/webhooks/grails-app/views/webhook/admin.gsp
Labels: 3.2.x

#5567 Removes alligators in login.scss
  rundeckapp/grails-app/assets/scss/pages/login.scss
Labels: release-notes/exclude

#5569 Removes sidebar license notification, updates package-lock.json
  rundeckapp/grails-app/views/common/_sidebar.gsp
  rundeckapp/grails-spa/package-lock.json
Labels: backport-to-3.0, backport-to-3.1, critical

#5583 Fixes webhook config for plugins with a custom config component.
  rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
Labels: 3.2.x

#5590 Fix #5589 by adding additional checks to the method input value.
  rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy
  rundeckapp/repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
Labels: 3.2.x, backport-to-3.0, backport-to-3.1

#5595 Ensure alert is above other elements
  rundeckapp/grails-app/assets/scss/paper/_alerts.scss
Labels: 3.2.x, release-notes/exclude

#5597 adds modal search, moves checkboxes, cleanup UI
  rundeckapp/grails-spa/src/pages/menu/components/userSummary.vue
Labels: release-notes/exclude, v3.2.0

#5593 Suppress NPE generated by Jetty JAAS logout module
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationProvider.groovy
Labels: 3.2.x, backport-to-3.0, backport-to-3.1

#5600 Handle webhook post with auth token containing hash
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: 3.2.x, backport-to-3.1

#5613 Fixes #5611. Delete all webhooks in project when project is deleted.
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Labels: 3.2.x, backport-to-3.1

#5585 new version pywinrm plugin 2.0.5
  rundeckapp/build.gradle
Labels: 3.2.x

#5472 Fix typo in remco template (nestedGroups)
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: docker

#5602 call refresh-nodes when the project settings are refresh
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.2.x, backport-to-3.1

#5540 fixing Option Value plugin is not using the name attribute
  rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp
Labels: 3.2.x, backport-to-3.1, backport-to-3.2

#5554 Fix #5553 duration more than 1 month should show correctly
  rundeckapp/grails-app/assets/javascripts/momentutil.js
Labels: 3.2.x, backport-to-3.1, backport-to-3.2, bug

#5527 Fixes #5495 - This changes fix a wrong behavior when edit a job with a wrong value so the options was lost from the session and removed if edit operation is canceled.
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5578 skipping node executor plugins to avoid loops
  core/src/main/java/com/dtolabs/rundeck/core/nodes/ProjectNodeService.java
  rundeckapp/grails-app/services/rundeck/services/NodeService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/services/ProjectNodesEnhancer.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/services/ProjectNodesEnhancerSpec.groovy
Labels: 3.2.x

#5622 Fixes #5133 - Change duration jobs info displayed on activity view to show seconds time and not a text saying "a few seconds"
  rundeckapp/grails-spa/src/components/activity/activityList.vue
Labels: 3.2.x, backport-to-3.1

#5555 Fix unexpected behavior when killing a job that includes Job Reference of workflow type. 5478
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: 3.2.x, backport-to-3.0, backport-to-3.1

#5618 Add bom char to destination file of the script #4291
  core/src/main/java/com/dtolabs/rundeck/core/data/SharedDataContextUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/common/DefaultFileCopierUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/script/ScriptfileUtils.java
  core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/SharedDataContextUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java
Labels: 3.2.x, backport-to-3.1

#5623 Fix incorrect job schedule display in cluster mode
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: 3.2.x, backport-to-3.1, backport-to-3.2

#5415 [2.11 backport] ImportOptions to jobref in job definition
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/test/unit/rundeck/JobExecSpec.groovy
Labels: v2.11.15

#5629 Corrects a typo in documentation file
  docker/official/README.md
Labels: backport-to-3.1, backport-to-3.2
