Repository rundeck/rundeck, pull requests merged in 2019-10, with the labels that each got.

#5309 [2.11 backport] Fix #5301 fix initProject, and clean old listeners
  rundeckapp/build.gradle
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/test/unit/rundeck/services/ScmServiceSpec.groovy
Labels: v2.11.15

#5254 Improve interactivity of page when loading execution log
  rundeckapp/grails-app/assets/javascripts/executionControl.js
  rundeckapp/grails-app/assets/javascripts/util/compactMapList.js
  rundeckapp/grails-app/conf/application.yml
Labels: v3.2.0

#5339 Fix invalid default value error on startup against SQL Server
  rundeckapp/webhooks/grails-app/domain/webhooks/Webhook.groovy
Labels: backport-to-3.1, needs-backport

#5345 Fix job group expansion applying to all levels
  rundeckapp/grails-app/assets/javascripts/application.js
Labels: backport-to-3.1

#5341 Concurrency improvements for workflow state
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowNodeStateImpl.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImpl.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepState.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepStateImpl.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplSpec.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplTest.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepStateImplTest.groovy
Labels: backport-to-2.11, backport-to-3.0, backport-to-3.1

#5376 Fix missing import 5375
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
Labels: v3.2.0

#5383 Cleanup test dir in NodeServiceSpec test
  rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Labels: backport-to-3.0, backport-to-3.1

#5389 Revert "Improve interactivity of page when loading execution log"
  rundeckapp/grails-app/assets/javascripts/executionControl.js
  rundeckapp/grails-app/assets/javascripts/util/compactMapList.js
  rundeckapp/grails-app/conf/application.yml
Labels: release-notes/exclude

#5382 Webhooks on by default.
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/webhooks/grails-app/controllers/webhooks/UrlMappings.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/WebhooksGrailsPlugin.groovy
Labels: v3.2.0

#5325 Fix error on remote opts with enforced values for simple JSON object
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: backport-to-3.1

#5379 fix selectable run later executions on bulk delete 5373
  rundeckapp/grails-spa/src/components/activity/activityList.vue
Labels: backport-to-3.1, bug

#5381 Wait for AbortResult from event bus reply. Fixes #4916.
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5360 Fix error when attempting to download text log
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5412 fix #4842 default selected validation fails if the object is not a map
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: backport-to-3.1, v3.2.0

#5319 fixing readme and motd project import archive
  .travis.yml
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  test/api/archive-test-readme.zip
  test/api/test-project-import-readme-motd.sh
  test/docker/dockers/rundeck/scripts/run_tests.sh
Labels: backport-to-3.0, backport-to-3.1

#5426 Fixes #5121. Bump repository version.
  rundeckapp/repository/build.gradle
Labels: backport-to-3.1, v3.2.0

#5322 [RFC] Fix scrolling to bottom in log output
  rundeckapp/grails-app/assets/javascripts/executionControl.js
Labels: backport-to-3.0, backport-to-3.1, bug

#5333 options values can be replaced by global properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: enhancement, v3.2.0

#5434 Fix: error importing job xml with single exec lifecycle plugin entry
  rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
  rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
Labels: release-notes/exclude, v3.2.0

#5022 exposing password encrypt utility interface as plugin
  core/src/main/java/com/dtolabs/rundeck/core/encrypter/EncryptorResponse.java
  core/src/main/java/com/dtolabs/rundeck/core/encrypter/PasswordUtilityEncrypterPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java
  core/src/main/java/com/dtolabs/rundeck/plugins/ServiceTypes.java
  rundeckapp/grails-app/controllers/rundeck/controllers/PasswordUtilityController.groovy
  rundeckapp/grails-app/services/rundeck/services/PasswordUtilityEncrypterLoaderService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/grails-app/views/passwordUtility/_renderSelectedEncrypter.gsp
  rundeckapp/grails-app/views/passwordUtility/index.gsp
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/services/PasswordUtilityEncrypterPluginProviderService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/services/PasswordUtilityEncrypterProviderService.groovy
  rundeckapp/src/main/resources/META-INF/services/org.rundeck.core.plugins.PluginProviderServices
  rundeckapp/src/test/groovy/rundeck/services/passwordencrypt/PasswordUtilityEncrypterLoaderServiceSpec.groovy
Labels: v3.2.0

#5390 Fixes #5320 - adds a wordbreak to the contents of a table column
  rundeckapp/grails-app/assets/scss/custom/execution-output-table.scss
Labels: backport-to-3.0, backport-to-3.1, v3.2.0

#5441 Allow all plugin properties to use groupName and grouping rendering options.
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtility.java
  core/src/test/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilityTest.java
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Labels: v3.2.0

#5028 Audit Events listeners and plugins.
  core/src/main/java/com/dtolabs/rundeck/core/audit/ActionTypes.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/AuditEvent.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/RequestInfo.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/ResourceInfo.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/ResourceTypes.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/UserInfo.java
  core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java
  core/src/main/java/com/dtolabs/rundeck/plugins/ServiceTypes.java
  core/src/main/java/com/dtolabs/rundeck/plugins/audit/AuditEventListener.java
  core/src/main/java/com/dtolabs/rundeck/plugins/audit/AuditEventListenerPlugin.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/AuditInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/services/AuditEventsHandlerProviderService.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
  rundeckapp/src/main/resources/META-INF/services/org.rundeck.core.plugins.PluginProviderServices
  rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Labels: v3.2.0

#5216 User login status tracking
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/User.groovy
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/grails-app/services/rundeck/services/events/UserActionService.groovy
  rundeckapp/grails-app/views/menu/userSummary.gsp
  rundeckapp/grails-spa/build/webpack.base.conf.js
  rundeckapp/grails-spa/build/webpack4.js
  rundeckapp/grails-spa/src/pages/menu/App.vue
  rundeckapp/grails-spa/src/pages/menu/components/LoginStatus.vue
  rundeckapp/grails-spa/src/pages/menu/components/userSummary.vue
  rundeckapp/grails-spa/src/pages/menu/i18n.js
  rundeckapp/grails-spa/src/pages/menu/index.html
  rundeckapp/grails-spa/src/pages/menu/main.js
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/events/UserActionServiceSpec.groovy
Labels: v3.2.0

#5331 FIX: rename locally used remco variables within storage configuration template
  docker/official/remco/templates/rundeck-config-storage.properties
Labels: v3.2.0
