Repository rundeck/rundeck, pull requests merged in 2019-09, with the labels that each got.

#5105 Improves readability of options in job executions, answers #5044
  rundeckapp/grails-app/assets/scss/custom/jobs.scss
Labels: change requested

#5252 Darkens the list delimiter input to differentiate between inline label
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: status: reviewed and approved

#5213 Fix #5125. Correct timezone offset on execution node status.
  rundeckapp/grails-app/assets/javascripts/executionStateKO.js
Labels: status: reviewed and approved

#5223 Add creation date to project list on api
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProject.java
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProjectConfig.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IRundeckProject.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IRundeckProjectConfig.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/projects/RundeckProject.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/projects/RundeckProjectConfig.java
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerTest.groovy
  rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Labels: enhancement

#5253 Improve execution log parsing speed with CompileStatic
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/logging/RundeckLogFormat.groovy
Labels: enhancement

#5277 cleanup argstring display in activity list and exec page
  rundeckapp/grails-app/assets/scss/custom/jobs.scss
  rundeckapp/grails-app/assets/scss/custom/workflow-editor.scss
  rundeckapp/grails-app/views/execution/_execArgString.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-spa/src/components/activity/activityList.vue
Labels: gui

#5300 Fix #5083 - Fixing the regex expression to consider "." character when perform auto completions
  rundeckapp/grails-app/assets/javascripts/application.js
Labels: status: ready for merge, v3.1.2

#5285 Fix #5113. Allow unicode characters in project description.
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkResource.java
  rundeckapp/grails-app/domain/rundeck/Project.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Labels: v3.1.2

#5304 Fix #5301 fix initProject, and clean old listeners
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: needs-backport

#5302 Fix issue with plugin select value with multiOption
  rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerTests.groovy
Labels: v3.1.2

#5308 [3.0 backport] fix #5306 scm memory leak
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: v3.0.27
