Repository rundeck/rundeck, pull requests merged in 2019-07, with the labels that each got.

#5047 Issues #5002, #4979, #4463, #4464, #4465, #4466 - Update several library dependencies to address reported CVEs.
  core/build.gradle
  gradle.properties
  rundeck-storage/build.gradle
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/BuildConfig.groovy
Labels: cve, needs-backport

#5048 backport of PR #5047 - Update library dependencies to address CVEs
  core/build.gradle
  gradle.properties
  packaging/rundeck.spec
  rundeck-storage/build.gradle
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/BuildConfig.groovy
Labels: cve

#5103 Restores Previous and Next in Execution page #5102
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/views/execution/show.gsp
Labels: enhancement

#5106 Issue #5077 - Dependency updates for CVEs: bouncycastle, spring, c3p0, moment.js
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/assets/javascripts/moment.min.js
Labels: cve, needs-backport
