Repository rundeck/rundeck, pull requests merged in 2020-04, with the labels that each got.

#5929 Fixes #5928 - Updating ACL doc links in app
  rundeckapp/grails-app/views/menu/_editAclFile.gsp
Labels: 3.2.x, bug, gui

#5849 Adds Security and Vulnerability Content
  SECURITY.md
Labels: 3.2.x

#5799 Add stale bot config
  .github/stale.yml
Labels: 3.2.x, release-notes/exclude

#5934 Fix #5933 wf strategy change saved without changing workflow contents
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5946 Fix #5945 - Shared data context was not considering the base map with options attributes
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x

#5954 Support windows builds
  rundeckapp/grails-spa/.gitignore
  rundeckapp/grails-spa/build.gradle
  rundeckapp/grails-spa/package-lock.json
  rundeckapp/grails-spa/package.json
Labels: 3.2.x, bug

#5957 Support for loading plugin resources from addons
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Labels: 3.2.x

#5939 fix for issue 5889 global variables delete
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5965 Some fixes for saving writeable project node data
  core/src/main/java/com/dtolabs/rundeck/core/resources/format/ResourceFormatParserService.java
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Labels: 3.2.x

#5974 Fix #5894 prevent double click on run job button
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
Labels: 3.2.x

#5966 Fix #5943 - Avoiding creating temporary files when deleting executions
  rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/ProjectServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
Labels: 3.2.x

#5918 Ftr/paged job list plugin
  core/src/main/java/com/dtolabs/rundeck/core/schedule/SchedulesManager.java
  core/src/main/java/org/rundeck/app/gui/JobListLinkHandler.java
  rundeckapp/grails-app/assets/javascripts/umd-vue-component-loader.js
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/JobSchedulesService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/common/_sidebar.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/GroupedJobListLinkHandler.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/JobListLinkHandlerRegistry.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5970 Remove remaining SCM calls prior to job list on GUI
  rundeckapp/grails-app/assets/javascripts/menu/jobs.js
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/_jobslist.gsp
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.2.x, customer request, enhancement

#5968 Fix #5081 log file storage request should be unique for execution
  rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/ExecutionIntegrationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Labels: 3.2.x, needs documentation

#5971 Use pessimistic locking on job stats update
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecutionStats.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Labels: 3.2.x

#5985 Scheduler - Handle null trigger and do not store durably
  rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
Labels: 3.2.x

#5989 Plugin resource loader: remove unnecessary WARN log
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
Labels: 3.2.x, release-notes/exclude
