Repository rundeck/rundeck, pull requests merged in 2020-02, with the labels that each got.

#5752 fixes #5692 - Activity Filter Doesn't Save in Search Modal
  rundeckapp/grails-spa/src/components/activity/activityFilter.vue
Labels: 3.2.x

#5748 Fix for problem validating remote url options using other options values. 5733
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: 3.1.x, 3.2.x, backport-to-3.1

#5757 Backport PR 5737 to maint-3.1.x
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/fileupload/FSFileUploadPlugin.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/PluginFactoryBean.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logstorage/TreeExecutionFileStoragePlugin.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/storage/DbStoragePlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Labels: 3.1.x

#5749 Fixing a n+1 issue removing a code that accessed the list of executions and was making a query for each one.
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: backport-to-3.1, regression

#5765 Allow bundled plugins to be externally specified
  build.gradle
  core/build.gradle
  plugins/build.gradle
  rundeckapp/build.gradle
Labels: 3.2.x, release-notes/exclude

#5754 Fix #5753 - An error message needs to be shown on GUI when deleting the project returns an error
  rundeckapp/grails-app/views/menu/_projectDeleteForm.gsp
Labels: 3.2.x

#5755 Underscore to project description regex.
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkResource.java
  rundeckapp/grails-app/domain/rundeck/Project.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.2.x, backport-to-2.11, backport-to-3.1

#5764 fixing wrong job scheduled status message
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5762 Fix artifact id and publishing path
  build.gradle
  rundeckapp/build.gradle
Labels: 3.2.x, release-notes/exclude

#5742 Fix #5721 by setting the form name to the correct value for the avg duration url.
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
Labels: 3.2.x

#5769 Fixes #5761 by adding scheduled true to the dynamic finder.
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.2.x

#5771 Update selenium viz setup to work on OSX
  test/selenium/Dockerfile
  test/selenium/docker-local-compose.yml
  test/selenium/entry.sh
  test/selenium/package.json
  test/selenium/src/test/selenium.ts
Labels: 3.2.x, release-notes/exclude

#5774 upgrade attribute-match-node-enhancer plugin
  build.gradle
Labels: 3.2.x

#5777 Only process JAR and ZIP plugin manifests
  rundeckapp/build.gradle
Labels: 3.2.x, release-notes/exclude

#5779 Some improvements to job list page speed with many jobs
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/views/menu/_groupTree.gsp
  rundeckapp/grails-app/views/menu/_jobslist.gsp
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
Labels: 3.2.x

#5807 Fix regression in plugin service causing plugin names to return prefixed with type
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Labels: 3.2.x

#5811 Fixes #5809 by not executing a criteria query when the "in" criteria will be an empty list.
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: 3.2.x

#5659 adding some small changes to the edit project form for UI plugin
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/framework/_projectConfigurableForm.gsp
Labels: 3.2.x

#5739 Remove spurious text
  rundeckapp/grails-app/views/framework/_storageBrowser.gsp
Labels: 3.2.x

#5837 fix #5835 handle registerLogin optimistic locking failure
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
Labels: 3.2.x

#5738 saving the correct list of Succeeded Node
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x

#5746 Update asset pipeline plugin for gradle and grails.
  gradle.properties
  grails-persistlocale/build.gradle
  grails-securityheaders/build.gradle
  rundeckapp/build.gradle
  rundeckapp/grails-app/assets/less/library/bootswatch.less
  rundeckapp/grails-app/assets/less/library/markdeep.less
  rundeckapp/grails-app/assets/scss/custom/buttons.scss
  rundeckapp/grails-app/assets/scss/custom/execution-page.scss
  rundeckapp/grails-app/assets/scss/custom/expand.scss
  rundeckapp/grails-app/assets/scss/custom/flexbox.scss
  rundeckapp/grails-app/assets/scss/custom/forms.scss
  rundeckapp/grails-app/assets/scss/custom/jobs.scss
  rundeckapp/grails-app/assets/scss/custom/links.scss
  rundeckapp/grails-app/assets/scss/custom/mainbar.scss
  rundeckapp/grails-app/assets/scss/custom/nav-tabs.scss
  rundeckapp/grails-app/assets/scss/custom/popovers.scss
  rundeckapp/grails-app/assets/scss/custom/rows.scss
  rundeckapp/grails-app/assets/scss/custom/table.scss
  rundeckapp/grails-app/assets/scss/custom/text.scss
  rundeckapp/grails-app/assets/scss/custom/workflow-step.scss
  rundeckapp/metricsweb/build.gradle
  rundeckapp/repository/build.gradle
  rundeckapp/webhooks/build.gradle
Labels: 3.2.x

#5747 Fix: user git config should not be used during tests
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitUtilSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/TestSystemReader.groovy
Labels: 3.2.x, release-notes/exclude

#5773 Fixes #5727 by using the plugin registry source that includes groovy plugin metadata.
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
Labels: 3.2.x

#5798 fix Nullpointer exception on api call
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5778 Joblifecycle plus job without options doesn't show error messages
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Labels: 3.2.x

#5734 job definition io component extension
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java
  core/src/main/java/org/rundeck/app/components/jobs/ImportedJob.java
  core/src/main/java/org/rundeck/app/components/jobs/JobDefinitionComponent.java
  core/src/main/java/org/rundeck/app/components/jobs/JobDefinitionException.java
  core/src/main/java/org/rundeck/app/components/jobs/JobDefinitionManager.java
  core/src/main/java/org/rundeck/app/components/jobs/JobFormat.java
  core/src/main/java/org/rundeck/app/components/jobs/JobXMLUtil.java
  core/src/main/java/org/rundeck/app/components/jobs/UnsupportedFormatException.java
  core/src/main/java/org/rundeck/app/gui/UISection.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionLifecyclePluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobFromMapSerializer.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/JobsYAMLCodec.groovy
  rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobComponentProperties.gsp
  rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BuilderUtil.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/util/XmlParserUtil.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobXMLFormat.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/RundeckJobDefinitionManager.groovy
  rundeckapp/src/test/groovy/JobsXMLCodecTests.groovy
  rundeckapp/src/test/groovy/JobsYAMLCodecTests.groovy
  rundeckapp/src/test/groovy/ProjectServiceTests.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclePluginServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
  test/selenium/lib/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-b7b68386-3a52-46dc-a28b-1a4bf6ed87de.xml
  test/selenium/src/__tests__/edit-job.test.ts
  test/selenium/src/__tests__/visual-regression/create.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
  test/selenium/src/pages/projectCreate.page.ts
  test/selenium/src/projectImporter.ts
Labels: 3.2.x

#5813 adds ProjectComponent for archive import/export, refactor Webhooks data to use it
  core/src/main/java/org/rundeck/app/components/project/ProjectComponent.java
  core/src/main/java/org/rundeck/core/projects/ProjectDataExporter.java
  core/src/main/java/org/rundeck/core/projects/ProjectDataImporter.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertiesInputs.gsp
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
  rundeckapp/grails-app/views/menu/_projectImportForm.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveExportRequest.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveImportRequest.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveParams.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/util/ZipReader.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerTest.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/WebhooksGrailsPlugin.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/component/project/WebhooksProjectComponent.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/exporter/WebhooksProjectExporter.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/importer/WebhooksProjectImporter.groovy
  rundeckapp/webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
  rundeckapp/webhooks/src/test/groovy/webhooks/exporter/WebhooksProjectExporterSpec.groovy
  rundeckapp/webhooks/src/test/groovy/webhooks/importer/WebhooksProjectImporterSpec.groovy
Labels: 3.2.x
