Repository rundeck/rundeck, pull requests merged in 2020-10, with the labels that each got.

#6518 Fix the display of Enterprise plugins when listing plugins
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
Labels: 3.3.x

#6516 Fix old property for contextPath was being used to set the context ref in the UI
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/src/integration-test/groovy/rundeck/init/RundeckInitializerTest.groovy
Labels: 3.3.x

#6524 Revert "Fix the display of Enterprise plugins when listing plugins"
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
Labels: release-notes/exclude

#6495 Run owasp dependency checks in circleci
  .circleci/config.yml
Labels: 3.3.x

#6535 Only fail owasp check on nightly
  .circleci/config.yml
Labels: 3.3.x, release-notes/exclude

#6513 add feature toggle for sidebar project list
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/views/common/_sidebar.gsp
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
  test/api/test-metrics.sh
Labels: 3.3.x

#6493 Fix Activity Date Filter
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
Labels: 3.3.x

#6498 Fix #6497 500 error on exec query api for missing project
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
Labels: 3.3.x, bug

#6507 Update ContainerRoleSource to return roles from Spring Security.
  rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerRoleSource.groovy
  rundeckapp/src/test/groovy/org/rundeck/web/infosec/ContainerRoleSourceSpec.groovy
Labels: 3.3.x

#6527 Add cache warmup at bootstrap time for auth and project services
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
Labels: 3.3.x

#6488 Changing place of the hiddenField "origName" to be possible renaming options when editing a job
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: 3.3.x, customer request

#6522 modified css for log output when printing screen from the browser
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/execution-output-styles.scss
Labels: 3.3.x, customer request

#6532 Change username check in user gsp template
  rundeckapp/grails-app/views/user/_user.gsp
Labels: 3.3.x

#6519 Changes to allow upload an empty file to a job option.
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.3.x, customer request

#6542 Update Spring framwork to 5.1.18.RELEASE
  gradle.properties
Labels: 3.3.x

#6544 Fix server uuid loading in rpm/deb
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
  rundeckapp/src/test/groovy/rundeckapp/init/RundeckInitializerSpec.groovy
Labels: 3.3.x

#6545 Update chrome driver and chrome to v86
  test/selenium-docker-compose.yml
  test/selenium/docker-compose.yml
  test/selenium/package.json
  test/testdeck/package.json
Labels: 3.3.x, release-notes/exclude

#6515 Removes Rundeck preboot initialization from application.groovy
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/src/test/groovy/testhelper/TestAppInitializer.groovy
  rundeckapp/src/test/resources/META-INF/spring.factories
Labels: 3.3.x, release-notes/exclude

#6550 Fix loading zero projects
  rundeckapp/grails-app/views/menu/home.gsp
Labels: 3.3.x, release-notes/exclude

#6551 Update projectLabels method
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6514 Update Ldap module to try bind password from the configuration service.
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
Labels: 3.3.x

#6555 Allow another second wait time in the schedule enabled flip test.
  test/api/test-job-flip-scheduleEnabled.sh
Labels: 3.3.x, release-notes/exclude

#6558 Flip job schedule enabled api test timing update
  test/api/test-job-flip-scheduleEnabled.sh
Labels: 3.3.x

#6560 Fix crontab everyday/everymonth checkbox fields always hidden
  rundeckapp/grails-app/views/scheduledExecution/_editCrontab.gsp
Labels: 3.3.x

#6565 Set defaults for project list and cache
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x, release-notes/exclude

#6563 Add rundeck.login.localLogin.enabled to config base class.
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 3.3.x

#6585 Update travis slack integration
  .travis.yml
Labels: 3.3.x, release-notes/exclude

#6589 Update tomcat-jdbc version to 9.0.39
  rundeckapp/build.gradle
Labels: 3.3.x

#6446 update mail plugin to 3.0.0, placeholders for dev mode testing
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x

#6567 Sending an event to cleanup acl caches If cluster mode is active
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
  rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
Labels: 3.3.x

#6562 fix #6528 exception in log file storage
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
Labels: 3.3.x, bug

#6586 Add ability to mark a schedule as missed.
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/data/ExecutionDataService.groovy
  rundeckapp/grails-app/services/rundeck/services/data/ScheduledExecutionDataService.groovy
  rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp
  rundeckapp/grails-app/views/execution/mailNotification/_oldStatus.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-status.scss
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecQuery.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.3.x

#6506 Changing to consider logged user roles for ACL cache
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManager.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManagerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Labels: 3.3.x

#6573 Adds an option to run referenced jobs using child's node set
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy
  rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy
  rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/execution/ExecutionItemFactory.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/execution/JobExecutionItem.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/execution/JobRefCommandBase.java
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/execution/ExecutionItemFactoryTest.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTests.groovy
Labels: 3.3.x

#6591 Report incomplete status in abort response reason
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.3.x

#6574 Fixing GUI to allow select a node clicking at arrow link on matched nodes popup
  rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
  rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
Labels: 3.3.x

#6579 before/after hooks in scheduler manager, some refactoring
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionReference.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/PreparedExecutionReference.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ServiceContext.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ServiceThreadBase.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceContext.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceThread.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobReference.java
  core/src/main/java/com/dtolabs/rundeck/core/schedule/JobScheduleManager.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy
  rundeckapp/grails-app/services/rundeck/services/execution/ExecutionReferenceImpl.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobTest.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobStateServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x

#6477 Applying "if node set empty" config for workflow strategies other than "Node First"
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/NodeFirstWorkflowExecutor.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
Labels: 3.3.x, customer request

#6505 duplicate job options
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/views/common/_js.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optlistitemContent.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
  test/selenium/src/__tests__/selenium/jobs/job-duplicate-options.test.ts
  test/selenium/src/pages/jobCreate.page.ts
Labels: 3.3.x

#6461 fix: Constructor.newInstance can throw runtime error, not just exception
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ProviderCreationException.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ProviderLoaderException.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ServiceProviderException.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/BaseProviderRegistryService.java
Labels: 3.3.x, release-notes/exclude

#6556 Update nowrunning ajax query to support wildcard value
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/nowrunning.gsp
  rundeckapp/grails-app/views/menu/nowrunningFragment.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.3.x

#6554 Remove vendor.js script tag from base
  rundeckapp/grails-app/views/layouts/base.gsp
Labels: 3.3.x

#6525 Fix the display of Enterprise plugins when listing plugins
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
Labels: 3.3.x

#6568 performance: Update ACL list GUI pages to have asynch behavior
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/assets/javascripts/menu/aclListing.js
  rundeckapp/grails-app/assets/javascripts/util/loader.js
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/_aclListItemKO.gsp
  rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.3.x

#6590 Issue/1321 Activity lists not showing on Job page when using oracle database
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
Labels: 3.3.x

#6594 new sshj plugin
  build.yaml
  testbuild.groovy
Labels: 3.3.x

#6494 Notifications on its own thread
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTests.groovy
Labels: 3.3.x
