Repository rundeck/rundeck, pull requests merged in 2020-06, with the labels that each got.

#6097 Enhance log4j props
  core/src/main/resources/com/dtolabs/launcher/setup/templates/profile.template
  docker/official/remco/templates/log4j2.properties
  docker/official/test/remco/test.sh
  rundeckapp/templates/config/log4j2.properties.template
  rundeckapp/templates/sbin/rundeckd.template
Labels: 3.3.x, release-notes/exclude

#6083 Docker - Update to Ubuntu 18.04 and OpenJDK 11
  docker/build.gradle
  docker/official/Dockerfile
  docker/official/README.md
  docker/official/lib/entry.sh
  docker/official/lib/includes/100_defaults.sh
  docker/ubuntu-base/Dockerfile
Labels: 3.3.x

#6071 Fix java 11 illegal reflective access warnings
  rundeckapp/build.gradle
Labels: 3.3.x

#6090 Ability to load framework properties from the app config sources.
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/ConfigFrameworkPropertyLookupFactory.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/FrameworkPropertyLookupFactory.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/framework/ConfigFrameworkPropertyLookupFactorySpec.groovy
Labels: 3.3.x

#6105 Better spring security integration.
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerPrincipalRoleSource.groovy
Labels: 3.3.x

#6107 Fix style import
  rundeckapp/grails-spa/packages/ui/babel.config.js
Labels: 3.3.x, release-notes/exclude

#6096 tours enhancement
  rundeckapp/grails-spa/package-lock.json
  rundeckapp/grails-spa/packages/ui/src/components/tour/interfaces/Tours.ts
  rundeckapp/grails-spa/packages/ui/src/components/tour/tourDisplay/App.vue
  rundeckapp/grails-spa/packages/ui/src/components/tour/tourPicker/App.vue
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.3.x

#6110 Remove debug println.
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/FrameworkPropertyLookupFactory.groovy
Labels: 3.3.x, release-notes/exclude

#6100 Fix issue/1019 where running jobs is aways zero even if there are jobs running.
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/jobs/JobQueryService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.3.x

#6062 App version display update
  rundeckapp/grails-app/assets/javascripts/versionIdentity.js
  rundeckapp/grails-app/assets/javascripts/versionTest.js
  rundeckapp/grails-app/assets/scss/paper/_tooltips-and-popovers.scss
  rundeckapp/grails-app/views/common/_sidebar.gsp
  rundeckapp/grails-app/views/common/_versionDisplay.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/menu/systemInfo.gsp
  rundeckapp/grails-app/views/menu/welcome.gsp
  rundeckapp/grails-spa/src/components/version/VersionDateDisplay.vue
  rundeckapp/grails-spa/src/components/version/VersionDisplay.vue
  rundeckapp/grails-spa/src/components/version/VersionIconNameDisplay.vue
  rundeckapp/grails-spa/src/components/version/main.js
  rundeckapp/grails-spa/src/utilities/RundeckVersion.ts
  rundeckapp/grails-spa/src/utilities/__tests__/RundeckVersion.spec.ts
Labels: 3.3.x

#6123 Restore the version component
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionDateDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionIconNameDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/main.js
  rundeckapp/grails-spa/packages/ui/src/utilities/RundeckVersion.ts
  rundeckapp/grails-spa/packages/ui/src/utilities/__tests__/RundeckVersion.spec.ts
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.3.x, release-notes/exclude

#6131 webhook UUID validation fix (via @laubstein)
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/webhooks/src/main/groovy/webhooks/plugins/JobRunWebhookEventPlugin.groovy
Labels: 3.3.x, backport-to-3.2

#6098 Add default result for git-import pull action
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/PullAction.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
Labels: 3.3.x, backport-to-3.2

#6117 Fix for log4j2 template
  rundeckapp/templates/config/log4j2.properties.template
Labels: 3.3.x, release-notes/exclude

#6137 Respond with correct content type if server error encountered during request
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ErrorController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/views/error/404.gsp
  rundeckapp/grails-app/views/error/405.gsp
  rundeckapp/grails-app/views/error/error.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/ErrorControllerSpec.groovy
Labels: 3.3.x

#6142 Fix #6139 500 error manually setting project exec disabled property
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Labels: 3.3.x, backport-to-3.1, backport-to-3.2

#6124 New Tours fixes
  rundeckapp/grails-spa/packages/ui/src/components/tour/duck.png
  rundeckapp/grails-spa/packages/ui/src/components/tour/tourDisplay/App.vue
  rundeckapp/grails-spa/packages/ui/src/components/tour/tourPicker/App.vue
  rundeckapp/grails-spa/packages/ui/src/components/tour/tours.svg
Labels: 3.3.x

#6147 upgrade py-winrm-plugin to 2.0.7
  build.yaml
Labels: 3.3.x

#6130 Accept Environment variables optional for jsch executor. fix #4137
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtSSHExec.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutorSpec.groovy
  test/docker/dockers/hostnode/Dockerfile
  test/docker/dockers/hostnode/scripts/createnode.sh
Labels: 3.3.x

#6153 Build - Add command for printing cluster logs
  test/testdeck/src/ClusterManager.ts
  test/testdeck/src/DockerCompose.ts
  test/testdeck/src/commands/cluster_commands/LogsCommand.ts
Labels: 3.3.x, release-notes/exclude

#6102 Enable h2 console in dev mode
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x

#6154 Add creation of rd_base/server/lib directory
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Labels: 3.3.x

#6152 Webhook save must flush the session
  rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy
Labels: 3.3.x

#6127 Handle quartz scheduler failures and log as warning
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x

#6156 Quell a common grails/spring bean warning
  docker/official/remco/templates/log4j2.properties
  rundeckapp/templates/config/log4j2.properties.template
Labels: 3.3.x

#5405 Use typed configuration for Rundeck configs.
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/RefererInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionLifecyclePluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobLifecyclePluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy
  rundeckapp/grails-app/taglib/rundeck/ConfigTagLib.groovy
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/config/RundeckConfig.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
  rundeckapp/src/test/groovy/rundeck/ConfigTagLibSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/RefererInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclePluginServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/feature/FeatureServiceSpec.groovy
Labels: 3.3.x

#6162 Set project storage to use db by default
  rundeckapp/grails-app/conf/application.yml
Labels: 3.3.x

#6159 Fix #6158 should not set incorrect project.name
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProjectConfig.java
  core/src/test/groovy/com/dtolabs/rundeck/core/common/FrameworkProjectConfigSpec.groovy
Labels: 3.3.x

#6169 Fix for the 404 causing a 500 issue
  rundeckapp/grails-app/controllers/rundeck/controllers/ErrorController.groovy
  rundeckapp/grails-app/views/404.gsp
  rundeckapp/grails-app/views/405.gsp
  rundeckapp/grails-app/views/error.gsp
Labels: 3.3.x

#6161 Fix #6160 ui plugin detail not showing
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Labels: 3.3.x

#6168 Docker - Process passwd update through /tmp for random uid
  docker/official/lib/entry.sh
Labels: backport-to-3.2

#6103 Docker - Optional bindPassword variable for jass-loginmodule
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: 3.3.x

#5732 Fix templating errors in jaas-login module - issue #5731
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: backport-to-3.2

#6118 Fix issue 1020 - Error handler on failed steps should be executed only in failed nodes
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcher.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/ParallelNodeDispatcher.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/SequentialNodeDispatcher.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/StepExecutionContext.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/ExecutionContextImplSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcherSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/TestBaseWorkflowStrategy.java
  core/src/test/java/com/dtolabs/rundeck/core/tools/AbstractBaseTest.java
  core/src/test/resources/com/dtolabs/rundeck/core/common/test-nodes5.xml
Labels: 3.3.x

#6155 fix issue 5730: It's a workaround to allow calc metrics when database does not support sql contained within the criteria.
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
Labels: 3.3.x

#6178 Replace magic variable with constant
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Labels: release-notes/exclude

#6176 Fix for rundeckpro/969 job list paging
  rundeckapp/grails-app/views/menu/jobs.gsp
Labels: 3.3.x

#6183 Add ability to toggle the workflow config 973 fix in docker.
  docker/official/remco/templates/rundeck-config.properties
Labels: 3.3.x

#6185 Fix for LogFileStorage save issue
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
Labels: 3.3.x

#6187 Pin types for js-yaml
  test/testdeck/package.json
Labels: release-notes/exclude

#6164 Docker - Environment Variable $HOME not set
  docker/official/lib/entry.sh
Labels: 3.3.x

#6182 Attempt to fix spurious testing errors in git plugin in some test cleanup phases
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitUtilSpec.groovy
Labels: release-notes/exclude

#6190 Fix a couple of issues in docker remco template
  docker/official/remco/templates/rundeck-config.properties
Labels: 3.3.x

#6208 Fix #4085 empty log file causes NaN in percentLoaded value
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Labels: backport-to-3.2
