Repository rundeck/rundeck, pull requests merged in 2020-07, with the labels that each got.

#6193 Docker - Allow Remco templates to target different rundeck base dirs
  docker/official/lib/entry.sh
  docker/official/remco/templates/framework.properties
  docker/official/remco/templates/jaas-loginmodule.conf
  docker/official/remco/templates/log4j2.properties
  docker/official/remco/templates/rundeck-config.properties
Labels: release-notes/exclude

#6199 Performance enhancement for job takeover process
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: 3.3.x

#6226 Open additional modules for reflective access to avoid illegal reflective access warnings
  rundeckapp/build.gradle
Labels: 3.3.x

#6216 Updates an existing plugin when using plugin upload GUI instead of reporting error
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
Labels: 3.3.x

#6229 Build - Fix source map loading from ui-trellis
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.js
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/package.json
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: release-notes/exclude

#6233 Test - Add testdeck option to keep cluster running
  test/testdeck/src/commands/TestCommand.ts
Labels: 3.3.x, release-notes/exclude

#6209 Ansi color 24 bit support, Fix #6198 bold mode plus 256 color should work
  rundeckapp/grails-app/assets/stylesheets/ansi24.css
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorCodec.groovy
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/src/test/groovy/rundeck/codecs/AnsiColorCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Labels: 3.3.x

#6228 Fix URI parse message on Windows for log4j2 config file
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Labels: 3.3.x

#6244 Set ehcache missing cache strategy to 'create' to avoid warnings
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x

#6247 Test - Allow time for scheduling
  test/api/test-job-flip-scheduleEnabled-bulk.sh
Labels: 3.3.x, release-notes/exclude

#6255 Docker - Add / on rundeck/jaas/file/required
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: 3.3.x

#6248 Fix log viewer and adhoc command page in FireFox ESR(68)
  rundeckapp/grails-app/assets/javascripts/executionStateKO.js
  rundeckapp/grails-app/assets/javascripts/framework/adhoc.js
Labels: 3.3.x

#6245 Fixes API call using asterisk #6069
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.2.x, 3.3.x, backport-to-3.2

#6254 fix #6239 acls not imported during fs conversion upgrading from 3.2 to 3.3
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.3.x

#6257 Reduce console messages in standalone war launch
  rundeckapp/build.gradle
  rundeckapp/templates/config/log4j2.properties.template
Labels: 3.3.x

#6259 Test Deck - Add user config overrides
  test/selenium/.gitignore
  test/selenium/.vscode/launch.json
  test/selenium/README.md
  test/selenium/config.yml
  test/selenium/src/__tests__/run-job/jobs-list-page.test.ts
  test/testdeck/package.json
  test/testdeck/src/Config.ts
  test/testdeck/src/commands/ApiCommand.ts
  test/testdeck/src/commands/Cluster.ts
  test/testdeck/src/commands/TestCommand.ts
  test/testdeck/src/commands/cluster_commands/DownCommand.ts
  test/testdeck/src/commands/cluster_commands/LogsCommand.ts
  test/testdeck/src/commands/cluster_commands/PSCommand.ts
  test/testdeck/src/commands/cluster_commands/ProvisionCommand.ts
  test/testdeck/tsconfig.json
Labels: 3.3.x, release-notes/exclude

#6215 Ignore the unsupported exception thrown when posix file permissions are set
  rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTree.java
Labels: 3.3.x

#6271 Update snakeyaml to 1.26
  core/build.gradle
  gradle.properties
  grails-persistlocale/build.gradle
  grails-securityheaders/build.gradle
  rundeck-authz/rundeck-authz-yaml/build.gradle
  rundeckapp/build.gradle
  rundeckapp/metricsweb/build.gradle
  rundeckapp/repository/build.gradle
  rundeckapp/webhooks/build.gradle
Labels: 3.3.x

#6200 Enhance YAML multiline export functionality
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BuilderUtil.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/support/BuilderUtilSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Labels: 3.3.x

#6276 Fixes when to execute a job using "Remote URL options" #6275
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.2.x, 3.3.x, backport-to-3.2

#6205 Add ability to configure object storage plugin with a region
  plugins/object-store-plugin/build.gradle
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/ObjectStorePlugin.groovy
Labels: 3.3.x

#6274 replace ehcache2 with jcache/ehcache3
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x

#6272 Fix: remove timing issue for test
  rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6280 Allow a rundeck server to be set as primary.
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  docker/official/remco/templates/rundeck-config.properties
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Labels: 3.3.x

#6217 Adds the ability to send webhook notifications in json format
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Notification.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.3.x

#6277 Update dependencies
  .circleci/config.yml
  .travis.yml
  build.gradle
  core/build.gradle
  cve-suppress.xml
  gradle.properties
  locallib/README.md
  locallib/not-yet-commons-ssl-0.3.17.jar
  locallib/not-yet-commons-ssl-LICENSE.txt
  plugins/git-plugin/build.gradle
  plugins/jasypt-encryption-plugin/build.gradle
  plugins/object-store-plugin/build.gradle
  rundeckapp/build.gradle
  rundeckapp/repository/build.gradle
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/HostnameVerifyingTrustManager.java
  rundeckapp/src/test/groovy/rundeck/CommandExecTests.groovy
  rundeckapp/src/test/groovy/rundeck/JobExecTests.groovy
  rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
  rundeckapp/src/test/groovy/rundeck/WorkflowTests.groovy
  rundeckapp/src/test/java/com/dtolabs/rundeck/jetty/jaas/HostnameVerifyingTrustManagerTest.java
  testbuild.groovy
Labels: 3.3.x

#6286 Cleanup User Summary page vue/layout
  rundeckapp/grails-app/views/menu/userSummary.gsp
  rundeckapp/grails-spa/packages/ui/src/pages/menu/components/userSummary.vue
  rundeckapp/grails-spa/packages/ui/src/pages/menu/i18n.js
Labels: 3.3.x, release-notes/exclude

#6295 Fix non existant tmp dir issue
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Labels: 3.3.x

#6296 Fix noisy cache warnings on startup
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.3.x

#6302 Fix node view output not rendering
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts
Labels: 3.3.x

#6307 Fix scroller reference
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Labels: 3.3.x, release-notes/exclude
