Repository rundeck/rundeck, pull requests merged in 2020-03, with the labels that each got.

#5850 Fixes #2668 by preventing an endless loop
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Labels: 3.2.x

#5838 Fix #5830 select values should not be encoded
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Labels: 3.2.x, backport-to-3.1

#5729 Refactoring context variables for email and plugins notification
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x

#5281 Fix #4704 Creating a new permission to allow or deny view executions history limiting by job groups
  core/src/main/java/com/dtolabs/rundeck/core/cli/acl/AclTool.java
  core/src/main/java/org/rundeck/core/auth/AuthConstants.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ReportsControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Labels: 3.2.x

#5853 Fix test failure
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x

#5851 Remove random 'e' character
  rundeckapp/grails-app/views/user/list.gsp
Labels: 3.2.x

#5840 Fix #5063 show error in job exec popup
  rundeckapp/grails-app/views/menu/jobs.gsp
  test/selenium/lib/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-0088e04a-0db3-4b03-adda-02e8a4baf709.xml
  test/selenium/src/__tests__/run-job/jobs-list-page.test.ts
  test/selenium/src/pages/jobsList.page.ts
Labels: 3.2.x

#5803 Scheduling enhacement
  core/src/main/java/com/dtolabs/rundeck/core/schedule/SchedulesManager.java
  core/src/main/java/org/rundeck/app/components/schedule/TriggerBuilderHelper.java
  core/src/main/java/org/rundeck/app/components/schedule/TriggersExtender.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobSchedulesService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/jobs/JobQueryService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_jobActionButton.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobActionButtonMenuContent.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobTest.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionQuery.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/LocalJobSchedulesManagerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x, enhancement

#5859 project component ordering changes
  core/src/main/java/org/rundeck/app/components/project/BuiltinExportComponents.java
  core/src/main/java/org/rundeck/app/components/project/BuiltinImportComponents.java
  core/src/main/java/org/rundeck/core/projects/ProjectDataExporter.java
  core/src/main/java/org/rundeck/core/projects/ProjectDataImporter.java
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/main/groovy/org/rundeck/util/Toposort.groovy
  rundeckapp/src/test/groovy/org/rundeck/util/ToposortSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: 3.2.x, release-notes/exclude

#5869 Fix #5868 git import should not fail
  rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Labels: 3.2.x

#5873 Fix #5872 broken link to remote option usage docs
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: 3.2.x

#5862 disabling prototype node file editor page
  rundeckapp/grails-app/views/framework/editProjectNodeSourceFile.gsp
Labels: 3.2.x, release-notes/exclude

#5871 Fix #5868 git import (port to master)
  rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Labels: 3.2.x, release-notes/exclude

#5878 Fix orchestrator issue
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5879 Fix orchestrator issue
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5882 Update AWS SDK to 1.11.743
  build.yaml
Labels: 3.2.x

#5897 Fix job query group/paging
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
  test/selenium/src/__tests__/run-job/jobs-list-page.test.ts
  test/selenium/src/pages/jobsList.page.ts
Labels: 3.2.x

#5905 Update AWS plugins
  build.yaml
Labels: 3.2.x

#5903 Include some filter params as json on page
  rundeckapp/grails-app/views/menu/jobs.gsp
Labels: 3.2.x, release-notes/exclude

#5839 Fix: delete all executions checkbox doesn't work in job delete form from upload page
  rundeckapp/grails-app/views/scheduledExecution/delete.gsp
Labels: 3.2.x

#5908 Add a directory for addon features.
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Labels: 3.2.x

#5907 Fix #5906
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/views/execution/_execDetails.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/menu/_jobslist.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showDetail.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Labels: 3.2.x, release-notes/exclude

#5902 Verirfying list of listeners to avoid an exception thrown before handle result
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Labels: 3.2.x

#5833 Update API archive import error response
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
  test/api/include.sh
Labels: 3.2.x

#5909 Fix test error ref #5833
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
Labels: 3.2.x, release-notes/exclude

#5914 upgrade py-winrm plugin version
  build.yaml
Labels: 3.2.x

#5904 Fix: job actions menu position for long descriptions
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
Labels: 3.2.x

#5411 Docker: Also change the max filesize in fileUploadService
  docker/official/README.md
  docker/official/remco/templates/grails-config.properties
Labels: 3.2.x

#5896 job query enhancement
  core/src/main/java/org/rundeck/app/components/jobs/JobQuery.java
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/jobs/JobQueryService.groovy
  rundeckapp/grails-app/views/menu/jobs.gsp
Labels: 3.2.x, enhancement

#5915 Adds media query to backdrop
  rundeckapp/grails-app/assets/scss/custom/modals.scss
Labels: 3.2.x, flaw, gui
