Repository rundeck/rundeck, pull requests merged in 2020-01, with the labels that each got.

#5616 Fixes #5117 - getting back the tags to select target nodes for jobs execution
  rundeckapp/grails-app/assets/scss/custom/labels.scss
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Labels: 3.2.x, 3.3.x, backport-to-3.1, backport-to-3.2

#5579 Fix #5001 - Adapting query so dashboard can show one time scheduled job (run job later) as scheduled and not as running job
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/QueueQuery.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
  rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Labels: 3.2.x, 3.3.x, backport-to-3.0, backport-to-3.1, backport-to-3.2

#5667 Adds v-if checking for if provider/plugin is builtin
  rundeckapp/grails-spa/src/pages/repository/components/ProviderCard.vue
  rundeckapp/grails-spa/src/pages/repository/components/ProviderCardRow.vue
Labels: 3.2.x, 3.3.x, backport-to-3.2

#5708 Bug/3922/jobs incorrect cursors
  rundeckapp/grails-app/assets/scss/custom/jobs.scss
Labels: 3.2.x

#5710 Defining a default value for crontabString prop when field is empty.
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Labels: 3.2.x

#5706 Fix #5704 copy paste err message issue in UserService.
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Labels: 3.2.x

#5681 FIX: typo in spanish translation
  rundeckapp/grails-app/i18n/messages_es_419.properties
Labels: 3.3.x

#5705 Allow valid unicode characters in user first and last name fields
  rundeckapp/grails-app/domain/rundeck/User.groovy
  rundeckapp/src/test/groovy/rundeck/UserTests.groovy
Labels: 3.2.x, backport-to-3.1

#5658 update jgit to 5.6.0.201912101111-r
  plugins/git-plugin/build.gradle
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitUtil.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
Labels: 3.2.x, dependencies

#5688 scm git plugin: close repo and delete using recursive flag on cleanup
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
Labels: 3.2.x, backport-to-3.1

#5673 Fix #5620 webhook checkbox label should work
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
Labels: 3.2.x

#5666 upgrade openssh plugin
  rundeckapp/build.gradle
Labels: 3.2.x

#5399 [build] Upgrade to gradle 4.8 compatible project structure.
  build.gradle
  docker/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  rundeckapp/build.gradle
  settings.gradle
Labels: 3.2.x

#5703 Upgrade snakeyaml
  core/build.gradle
  core/src/test/java/com/dtolabs/rundeck/core/common/TestNodesYamlParser.java
  grails-persistlocale/build.gradle
  grails-securityheaders/build.gradle
  rundeckapp/build.gradle
  rundeckapp/metricsweb/build.gradle
  rundeckapp/repository/build.gradle
  rundeckapp/webhooks/build.gradle
Labels: 3.2.x, backport-to-3.1

#5594 Adds example for audit plugin
  examples/example-java-audit-plugin/README.md
  examples/example-java-audit-plugin/pom.xml
  examples/example-java-audit-plugin/src/main/java/com/example/ExampleAuditListener.java
Labels: 3.2.x

#5689 expanding execution variables on notification plugin config
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.2.x

#5577 ssh export rd variables
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/NodeExecutorUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/NodeExecutorUtilsSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilderSpec.groovy
Labels: 3.2.x, customer request, enhancement, needs documentation

#5720 Job query internal extension
  core/src/main/java/org/rundeck/app/components/jobs/BaseQueryInput.java
  core/src/main/java/org/rundeck/app/components/jobs/JobQuery.java
  core/src/main/java/org/rundeck/app/components/jobs/JobQueryInput.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BaseQuery.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.2.x

#5740 [CI/CD] Collect test results
  .circleci/config.yml
Labels: 3.2.x, release-notes/exclude

#5741 Sync build setup from master
  .circleci/config.yml
  .circleci/run.sh
  .circleci/travis-shim.sh
  scripts/travis-build.sh
  scripts/travis-helpers.sh
Labels: 3.1.x, release-notes/exclude

#5737 Changing the mechanism that loads the plugins into memory to consider the type of the plugin in addition to its name
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/fileupload/FSFileUploadPlugin.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/PluginFactoryBean.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logstorage/TreeExecutionFileStoragePlugin.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/storage/DbStoragePlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Labels: 3.2.x, backport-to-3.1
