Repository rundeck/rundeck, pull requests merged in 2020-08, with the labels that each got.

#6297 Fix #5801. Remove reference to plugin that doesn't exist.
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
Labels: 3.3.x

#6348 OWASP dependency updates
  build.gradle
  core/build.gradle
  gradle.properties
  rundeckapp/build.gradle
Labels: 3.3.x

#6347 Remove the @Transactional from JobEventsService
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
Labels: 3.3.x

#6342 Docker - Add version and commit labels to docker image
  build.gradle
  docker/build.gradle
Labels: 3.3.x

#6350 Fix #6349: failure to serialize jobs for git due to mkdirs
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
Labels: 3.3.x, backport-to-3.2

#6301 Core config enhancements
  core/src/main/java/org/rundeck/app/bootstrap/PreBootstrap.java
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
  rundeckapp/src/test/groovy/rundeckapp/TestPrebootstrap.groovy
  rundeckapp/src/test/resources/META-INF/services/org.rundeck.app.bootstrap.PreBootstrap
Labels: 3.3.x

#6329 Restores the ability to specify the server config dir with the command line option -c.
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
  rundeckapp/src/test/groovy/rundeckapp/cli/CommandLineSetupTest.groovy
Labels: 3.3.x

#6339 Add JCache configuration that is roughly equivalent to the former ehcache configuration.
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/ehcache.xml
  rundeckapp/grails-app/conf/jcache.xml
Labels: 3.3.x

#6355 Enhance stack traces for selenium webdriver errors
  test/testdeck/src/test/selenium.ts
  test/testdeck/src/util/Error.ts
Labels: 3.3.x, release-notes/exclude

#6353 SCM and Git plugin fixes
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/StoredJobChangeEvent.groovy
Labels: 3.3.x, backport-to-3.2

#6285 Fix: flaky test race condition in LogFileStorageServiceSpec
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Labels: 3.3.x

#6369 [3.3.2] Fix logging system initialization
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
Labels: 3.3.x, backport-to-main, release-notes/exclude

#6370 Set webpack public path dynamically
  rundeckapp/grails-spa/packages/ui/src/components/tour/main.js
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.3.x, backport-to-main, release-notes/exclude

#6381 Bump s3 model source version to 1.0.5
  build.yaml
Labels: 3.3.x, release-notes/exclude

#6391 Paged Project List
  rundeckapp/grails-app/assets/javascripts/menu/home.js
  rundeckapp/grails-app/taglib/rundeck/ConfigTagLib.groovy
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/src/test/groovy/rundeck/ConfigTagLibSpec.groovy
Labels: 3.3.x

#6380 Fix reflective access warning for java.util.logging.
  rundeckapp/build.gradle
Labels: 3.3.x

#6389 Bring minio client library up to 7.1.0
  cve-suppress.xml
  plugins/object-store-plugin/build.gradle
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTree.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreUtils.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithDirectAccessDirSourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithMemoryDirSourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/testhelpers/MinioTestUtils.groovy
Labels: 3.3.x

#6192 Plugin UI Enhancement
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java
  rundeckapp/grails-app/assets/javascripts/application.js
  rundeckapp/grails-app/assets/javascripts/filterStepPluginsKO.js
  rundeckapp/grails-app/assets/javascripts/jobEditPage_bundle.js
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/assets/javascripts/util/yellowfade.js
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/grails-app/taglib/rundeck/PluginTagLib.groovy
  rundeckapp/grails-app/taglib/rundeck/WidgetTagLib.groovy
  rundeckapp/grails-app/views/execution/_execDetailsWorkflow.gsp
  rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
  rundeckapp/grails-app/views/execution/_wflistitemContent.gsp
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/grails-app/views/framework/_pluginConfigPropertySummaryValue.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editCrontab.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optlistContent.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optlistitemContent.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/DynamicFormPluginProp.vue
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/workflow-step.scss
  rundeckapp/grails-spa/packages/ui/src/pages/dynamic-form/App.vue
  rundeckapp/grails-spa/packages/ui/src/pages/dynamic-form/i18n.js
  rundeckapp/grails-spa/packages/ui/src/pages/dynamic-form/main.js
  rundeckapp/grails-spa/packages/ui/vue.config.js
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
  test/selenium/src/__tests__/selenium/jobs/job-change-strategy.test.ts
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts
  test/selenium/src/__tests__/selenium/jobs/job-option-config.test.ts
  test/selenium/src/__tests__/selenium/jobs/job-option-undo-redo.test.ts
  test/selenium/src/__tests__/selenium/jobs/job-wf-undo-redo.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: 3.3.x

#6398 fix issue creating a job loading notification dynamic properties
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6403 ACL List paging
  rundeckapp/grails-app/assets/javascripts/menu/aclListing.js
  rundeckapp/grails-app/assets/javascripts/util/pager.js
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/views/menu/_aclKOTemplates.gsp
  rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp
  rundeckapp/grails-app/views/menu/_aclsPagingKO.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
Labels: 3.3.x

#6396 Fix read validation of a job from another project. #3157
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.3.x, backport-to-3.2

#6409 Test - Update chrome and chromedriver
  test/selenium-docker-compose.yml
  test/selenium/docker-compose.yml
  test/selenium/docker-local-compose.yml
  test/testdeck/package.json
Labels: 3.3.x, release-notes/exclude

#6408 Project list speed update2
  rundeckapp/grails-app/assets/javascripts/menu/home.js
Labels: 3.3.x, release-notes/exclude

#6413 fix js issues job create/edit form
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/views/framework/_stepPluginFilterInputGroup.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
Labels: 3.3.x

#6299 Change http return when execution status is passive from 503 to 200
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
  test/api/include.sh
Labels: 3.3.x, needs documentation

#6420 Migrate pre spring boot 2 cookie configs to valid configs.
  rundeckapp/grails-app/conf/application.yml
Labels: 3.3.x

#6394 Forcing a new attempt when to execute script and the script file is busy because of chmod command executed just before
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/NewLocalNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
Labels: 3.3.x

#6422 Pin js-yaml types
  test/selenium/package.json
Labels: 3.3.x, release-notes/exclude

#6415 Project List minor UI: Show result count indicator when using any filter method
  rundeckapp/grails-app/assets/javascripts/util/pager.js
  rundeckapp/grails-app/views/menu/home.gsp
Labels: 3.3.x

#6423 Improve project list loading for user session
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/views/framework/_projectSelect.gsp
  rundeckapp/grails-app/views/framework/_projectSelectSidebar.gsp
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Labels: 3.3.x, release-notes/exclude
