Repository rundeck/rundeck, pull requests merged in 2020-05, with the labels that each got.

#5990 Fix #5938 error when logging in with empty credentials.
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
  rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Labels: 3.2.x

#6012 Update user summary menu item to use a spring bean.
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/UserSummaryMenuItem.groovy
Labels: 3.2.x

#6006 fix #5988 - Handling tags with null values on parser of node resource files in json format
  core/src/main/java/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParser.java
  core/src/test/groovy/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParserSpec.groovy
Labels: 3.2.x

#6007 Fix #6001 - useName property of referenced jobs should be true when it is null and there is name but there is not uuid on map
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Labels: 3.2.x

#6024 Add the ability to refresh the user summary page using the event bus.
  rundeckapp/grails-spa/src/pages/menu/components/userSummary.vue
Labels: 3.2.x

#5994 project storage SPI
  core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/BaseFileResourceModelSource.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/FileResourceModelSource.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceFactory.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceService.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/format/ResourceFormats.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/StorageTreeFactory.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/StorageUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/projects/ProjectStorageTree.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/projects/ProjectStorageTreeImpl.java
  core/src/main/java/org/rundeck/app/spi/Services.java
  core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/storage/StorageUtilSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/resources/TestFileResourceModelSource.java
  rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/PrefixPathTree.java
  rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/SubPathTree.java
  rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/TreeBuilder.java
  rundeck-storage/rundeck-storage-conf/src/test/groovy/org/rundeck/storage/conf/PrefixPathTreeSpec.groovy
  rundeck-storage/rundeck-storage-data/src/main/java/org/rundeck/storage/data/DataUtil.java
  rundeck-storage/rundeck-storage-data/src/test/groovy/org/rundeck/storage/data/DataUtilSpec.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/ConfigStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/NodeService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.2.x

#5440 Docker - Set uid in passwd for OpenShift support
  docker/official/lib/entry.sh
Labels: 3.2.x

#6013 Prevent attempt to schedule jobs on a quartz scheduler that is shutdown.
  rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
Labels: 3.2.x

#6033 Update testdeck ts-rundeck
  test/selenium/package.json
  test/testdeck/package.json
  test/testdeck/src/RundeckCluster.ts
  test/testdeck/src/cluster/Config.ts
  test/testdeck/src/test/api.ts
Labels: 3.2.x, release-notes/exclude

#5944 Docker - Make /etc/passwd group writable
  docker/ubuntu-base/Dockerfile
Labels: 3.2.x

#5981 adding an invalid key pattern to avoid characters like space on the key.
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
Labels: 3.2.x

#5695 Bugfix: close logread in tailExecutionOutput
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
Labels: 3.2.x

#6027 Update grails spring security plugin to 3.3.1
  rundeckapp/build.gradle
Labels: 3.2.x

#5980 Remove legacy node config UI
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
Labels: 3.2.x

#5995 Clean up duplicate LogFileStorageRequest entries at startup
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
Labels: 3.2.x

#6002 fix asUser on retry job
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.2.x

#6039 Docker - Fix default value for config storage converter path
  docker/official/remco/templates/rundeck-config-storage.properties
Labels: 3.2.x

#6010 Fixing the job import process where the ruleset strategy was not saved correctly
  rundeckapp/grails-app/domain/rundeck/Workflow.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/services/rundeck/services/ConfigStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/WorkflowServiceSpec.groovy
Labels: 3.2.x

#5983 Fix #5979 update ui-trellis to support markdown extended property descriptions
  .circleci/config.yml
  rundeckapp/grails-spa/package-lock.json
  rundeckapp/grails-spa/package.json
  rundeckapp/grails-spa/src/types.d.ts
Labels: 3.2.x

#6043 Update testbuild for rundeck-authz libs
  testbuild.groovy
Labels: 3.2.x, release-notes/exclude

#6044 Fix AuthZ bintray publishing
  rundeck-authz/build.gradle
  rundeck-authz/rundeck-authz-api/build.gradle
  rundeck-authz/rundeck-authz-core/build.gradle
  rundeck-authz/rundeck-authz-yaml/build.gradle
Labels: 3.2.x, release-notes/exclude

#6054 Fix execution stats lockmode
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
Labels: 3.2.x, backport-to-3.2

#6057 Remove translate3d scroll fix
  rundeckapp/grails-spa/src/components/execution-log/logViewer.vue
Labels: 3.2.x, backport-to-3.2, release-notes/exclude

#6059 Scope global antd styles
  rundeckapp/grails-spa/build/webpack.base.conf.js
  rundeckapp/grails-spa/package-lock.json
  rundeckapp/grails-spa/package.json
Labels: backport-to-3.2, release-notes/exclude

#6067 Fix: unit test file incorrectly placed
  rundeckapp/src/test/groovy/rundeck/services/logging/StepLabellingStreamingLogWriterSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6066 Fix #6065 plugin values should be shown in multivalued list
  rundeckapp/grails-app/assets/javascripts/menu/joboptions.js
Labels: 3.3.x, backport-to-3.2, bug

#6075 Fix: need to await expect resolves, bump timeouts
  test/selenium/src/__tests__/selenium/visual-regression/create.test.ts
Labels: 3.3.x, release-notes/exclude

#6072 FileSystem Key Storage permissions
  rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTree.java
  rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTreeUtil.java
  rundeck-storage/rundeck-storage-filesys/src/test/groovy/org/rundeck/storage/data/file/FileTreeSpecification.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/storage/FileStoragePlugin.groovy
Labels: 3.3.x

#6063 fix: incorrect height for sidebar wrapper
  rundeckapp/grails-app/assets/scss/paper/_sidebar-and-main-panel.scss
Labels: 3.2.x

#5920 Remove rd-acl
  core/build.gradle
  core/src/main/java/com/dtolabs/launcher/Setup.java
  core/src/main/java/com/dtolabs/rundeck/core/Constants.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/BaseTool.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/CLITool.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/CLIToolException.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/CLIToolOptions.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/CLIToolOptionsException.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/DefaultCLIToolLogger.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/HelpOptions.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/Log4JCLIToolLogger.java
  core/src/main/java/com/dtolabs/rundeck/core/cli/acl/AclTool.java
  core/src/main/resources/com/dtolabs/launcher/setup/templates/cli-log4j.properties.template
  core/src/main/resources/com/dtolabs/rundeck/core/cli/templates/rd-acl
  core/src/main/resources/com/dtolabs/rundeck/core/cli/templates/rd-acl.bat
  docker/official/Dockerfile
  docker/official/etc/cli-log4j.properties
  docker/official/etc/profile
  docker/official/etc/profile.bat
  docker/ubuntu-base/Dockerfile
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
  test/docker/dockers/rundeck/scripts/start_rundeck.sh
  testbuild.groovy
Labels: 3.2.x

#6080 Use spring loaded instead of dev tools
  rundeckapp/build.gradle
Labels: 3.3.x

#6085 Fix the Japanese translation of "retry"
  rundeckapp/grails-app/i18n/messages_ja.properties
Labels: 3.3.x

#6050 Fix an issue that caused job execution to get stuck inside a loop when an exception was thrown from a log event call
  core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
Labels: 3.3.x, backport-to-3.2, bug

#6087 Update docker to use log42.
  docker/official/lib/entry.sh
  docker/official/remco/resources.d/log4j.properties.toml
  docker/official/remco/resources.d/log4j2.properties.toml
  docker/official/remco/templates/log4j.properties
  docker/official/remco/templates/log4j2.properties
Labels: 3.3.x

#6091 Avoiding loading all plugins whenever a method needs to search for a plugin description
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/DescribableServiceUtil.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Labels: 3.3.x, backport-to-3.2
