Repository rundeck/rundeck, pull requests merged in 2020-09, with the labels that each got.

#6429 fix error creating and editing jobs in 3.3.3
  rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
Labels: 3.3.x

#6427 update openssh version
  build.yaml
Labels: 3.3.x

#6432 restrictOptName must be applied just for option name
  rundeckapp/grails-app/assets/javascripts/jobedit.js
Labels: 3.3.x, backport-to-main

#6431 Add proper packaging steps to readme
  README.md
Labels: 3.3.x

#6443 port pr 6441 to main
  rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6417 Fix #6335 failOnDisable flag in jobref definition not serialized/loaded correctly
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Labels: 3.3.x

#6425 Fixes when send an email notification when a job is marked as "Incomplete" #6401
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 3.3.x

#6444 ImportOptios flag is not importing correctly when upload a job definition #6442
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Labels: 3.3.x

#6426 internal refactor: don't throw runtime exception on missing property lookup
  core/src/main/java/com/dtolabs/rundeck/core/common/FilesystemFramework.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IFramework.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/StorageTreeFactory.java
  core/src/main/java/com/dtolabs/rundeck/core/utils/PropertyLookup.java
  core/src/test/groovy/com/dtolabs/rundeck/core/utils/PropertyLookupSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/utils/TestPropertyLookup.java
Labels: 3.3.x, release-notes/exclude

#6434 Fix issue 5462 where SCP File Copier and SSH Node Executor have same properties which meant that the properties were not saved to the Default Node Executor when File Copier overwrote the changes. This change makes the properties to be saved, regardless of where they were changed (in File Copier or Node Executor properties).
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy
Labels: 3.3.x

#6414 Rundeck initialization refactoring
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/HealthController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckWebAppInitializer.groovy
  rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/AddonClasspathInjectorPrebootstrap.groovy
  rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/InitializeRundeckPreboostrap.groovy
  rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/ServerLibInjectorPreBoostrap.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/src/integration-test/groovy/rundeck/init/RundeckInitializerTest.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpTest.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/AppRestarter.groovy
  rundeckapp/src/main/resources/META-INF/services/org.rundeck.app.bootstrap.PreBootstrap
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
  rundeckapp/src/test/groovy/rundeckapp/init/RundeckInitializerSpec.groovy
  rundeckapp/templates/config/rundeck-config.properties.template
Labels: 3.3.x

#6462 Add Community Survey to Readme + Release Notes Fix
  README.md
Labels: 3.3.x

#6454 Node Executor or File Copier Plugin are missing #6436
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy
Labels: 3.3.x

#6457 Notification plugin key storage
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/AcceptsServices.java
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/KeyStorageSelector.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
Labels: 3.3.x

#6458 upgrade pywinrm plugin. Adding flag for enabling kerberos delegation
  build.yaml
Labels: 3.3.x

#6456 Fix #6449 - Sync command disabled as default and without arguments
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
Labels: 3.3.x

#6438 UI Update: Notifications editor
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
  rundeckapp/grails-app/domain/rundeck/Notification.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/AceEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/ExtendedDescription.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/modules/pluginService.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/utilities/braceFix.ts
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.js
  rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/util/UndoRedo.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/App.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/JsonEmbed.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/i18n.js
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/main.js
  rundeckapp/grails-spa/packages/ui/vue.config.js
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyEmailNotificationPlugin.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyWebhookNotificationPlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
  rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x

#6455 Remove unused fonts
  rundeckapp/grails-app/assets/fonts/themify.eot
  rundeckapp/grails-app/assets/fonts/themify.svg
  rundeckapp/grails-app/assets/fonts/themify.ttf
  rundeckapp/grails-app/assets/fonts/themify.woff
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/themify.eot
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/themify.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/themify.ttf
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/themify.woff
Labels: 3.3.x

#6460 Replace git plugin icon with font icon
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactory.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPluginFactory.groovy
  plugins/git-plugin/src/main/resources/resources/i18n/git-export.messages.properties
  plugins/git-plugin/src/main/resources/resources/i18n/git-import.messages.properties
  plugins/git-plugin/src/main/resources/resources/icon.png
  plugins/git-plugin/src/main/resources/resources/license.txt
  rundeckapp/grails-app/views/scm/index.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-brands-400.eot
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-brands-400.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-brands-400.ttf
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-brands-400.woff
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-brands-400.woff2
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-regular-400.eot
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-regular-400.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-regular-400.ttf
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-regular-400.woff
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-regular-400.woff2
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-solid-900.eot
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-solid-900.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-solid-900.ttf
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-solid-900.woff
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/webfonts/fa-solid-900.woff2
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/_icons.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/_shims.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/_variables.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/brands.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/fontawesome.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/regular.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/solid.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/fontawesome/v4-shims.scss
Labels: 3.3.x

#6465 Set version to 3.3.4-SNAPSHOT
  gradle.properties
  version.properties
Labels: 3.3.x, release-notes/exclude

#6464 Update notifications: enable vue ui in production, update selenium tests
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyEmailNotificationPlugin.groovy
  test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts
  test/selenium/src/pages/jobCreate.page.ts
Labels: 3.3.x

#6466 Fix timing of test for new notification ui
  test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts
  test/selenium/src/pages/jobCreate.page.ts
Labels: release-notes/exclude

#6470 Fix: project list gui config values not working
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 3.3.x

#6473 Fix sidebar active indicator on webhooks page
  rundeckapp/webhooks/grails-app/views/webhook/admin.gsp
Labels: 3.3.x

#6484 User manager login status not shown
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 3.3.x, release-notes/exclude

#6485 Speed up filesystem plugin access
  core/src/main/java/com/dtolabs/rundeck/core/plugins/DirPluginScanner.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginScanner.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeEvent.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeEventListener.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeType.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirProvider.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginScanner.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/WatchingPluginDirProvider.java
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/DirPluginScannerSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/plugins/TestDirPluginScanner.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/init/rundeckapp/init/PluginCachePreloader.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/UiPluginService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/FileUploadServiceIntegrationSpec.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Labels: 3.3.x

#6492 Fix #6357 disabling schedule in job edit does not work
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x

#6490 Fix #6304 where changing only the crontab would not update the scheduled execution.
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
Labels: 3.3.x

#6502 Upgrade mariadb driver to 2.7.0
  rundeckapp/build.gradle
Labels: 3.3.x

#6500 Quell reflective access messages.
  rundeckapp/build.gradle
Labels: 3.3.x
