Repository rundeck/rundeck, pull requests merged in 2020-12, with the labels that each got.

#6649 Adjust EventStore column max lengths
  rundeckapp/grails-app/domain/rundeck/StoredEvent.groovy
Labels: 3.3.x, release-notes/exclude

#6653 allowed values list in option form is displayed misaligned in 3.3.7
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: 3.3.x

#6658 Fix/job life cycle node list
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x, bug

#6663 Add ability to redirect login page to a different uri.
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/interceptors/UserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/UserInterceptorSpec.groovy
Labels: 3.3.x

#6667 Fixing enterprise download link that was point to OSS version (update available notification)
  rundeckapp/grails-spa/packages/ui/src/components/version-notification/App.vue
Labels: 3.3.x

#6664 Fix execution log viewer not updating settings on running job
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Labels: 3.3.x

#6684 Allow syncing user info in preauthenticated mode.
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandler.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckUserDetailsService.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandlerSpec.groovy
Labels: 3.3.x

#6680 Fixes #6580 by using Instant.now()
  rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
Labels: 3.3.x

#6640 Updating node set on subworkflow state when the node filter is modified during the job execution
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImpl.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepState.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepStateImpl.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplSpec.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplTest.groovy
Labels: 3.3.x

#6677 Add user email to the context that is used to resolve parameters for options.
  rundeckapp/grails-app/controllers/rundeck/utils/OptionsUtil.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/OptionsUtilsSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/OptionsUtilsTests.groovy
Labels: 3.3.x

#6689 Update pywinrm plugin. Added a function to remove/replace simple quotes when execute CMD command
  build.yaml
Labels: 3.3.x

#6692 Migrate auth call from framworkService to new acl classes in repository controller.
  rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy
  rundeckapp/repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
Labels: 3.3.x

#6696 Fix: ACL listing should be sorted (refactor update)
  core/src/main/java/org/rundeck/app/acl/AppACLContextImpl.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6694 Pro property loader wasn't decrypting property value
  rundeckapp/grails-app/init/rundeckapp/init/ReloadableRundeckPropertySource.groovy
Labels: 3.3.x

#6678 Fix bold styling in markdown
  rundeckapp/grails-app/assets/stylesheets/github-markdown.css
Labels: 3.3.x, release-notes/exclude

#6662 fix an issue with notification plugin + dynamic properties.
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/DummyNotificationPlugin.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceJobIntegrationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x
