Repository rundeck/rundeck, pull requests merged in 2021-08, with the labels that each got.

#7200 update testcontainers due to build issue in object store plugin
  plugins/object-store-plugin/build.gradle
Labels: 3.4.x, release-notes/exclude

#7202 Bump snapshot to 3.4.3
  gradle.properties
  version.properties
Labels: 3.4.x

#7192 RUN-165: Fix issue when scheduled jobs runs twice in a cluster
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.4.x

#7185 RUN-238: Add pluginSecurity feature to disable plugin uploads
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  grails-repository/grails-app/controllers/repository/RepositoryController.groovy
  grails-repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Labels: 3.4.x

#7201 RUN-260: Fix/issue 1899 Wrong value after changing option type
  rundeckapp/grails-app/assets/javascripts/optionEditKO.js
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  test/selenium/src/pages/jobCreate.page.ts
Labels: 3.4.x

#7205 Job tags not copied when duplicating job
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Labels: 3.4.x

#7213 Add plugin security feature check to installPlugin endpoint
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Labels: 3.4.x

#7220 Fix: unable to upload an acl policy file with the gui
  rundeckapp/grails-app/assets/javascripts/menu/aclListing.js
  rundeckapp/grails-app/views/common/_modal.gsp
  rundeckapp/grails-app/views/menu/_aclManageKO.gsp
  rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  test/selenium/src/__tests__/selenium/acls/system-acls.test.ts
  test/selenium/src/pages/systemAcls.page.ts
Labels: 3.4.x, to-jira

#7222 RUN-326: Delete apitoken.aclpolicy from docker image
  docker/official/etc/apitoken.aclpolicy
Labels: 3.4.x, to-jira

#7216 RUN-334: Node executor secret bundle creation
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IFrameworkServices.java
  core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschSecretBundleUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/DefaultSecretBundle.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/SecretBundle.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/FileCopierService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginFileCopier.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/BaseScriptPlugin.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutorSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschSecretBundleUtilSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/BaseScriptPluginSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
Labels: release-notes/exclude, 3.4.x, to-jira

#7191 Upgrade pywinrm plugin. Removed all environment variables containing …
  build.yaml
Labels: 3.4.x

#7228 RUN-335: Fix: by: urn list is not working
  rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java
  rundeck-authz/rundeck-authz-yaml/src/test/groovy/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicySpec.groovy
Labels: 3.4.x, to-jira

#7235 Bump snapshot version to 3.4.4
  gradle.properties
  version.properties
Labels: 3.4.x
