Repository rundeck/rundeck, pull requests merged in 2021-02, with the labels that each got.

#6761 Fix/project acl import
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: 3.3.x

#6767 Update mergify for 3.4.0
  .mergify.yml
Labels: release-notes/exclude

#6773 Enhance configurability of InterceptorHelper.
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/main/java/org/rundeck/app/access/InterceptorHelper.java
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/ApiAccessInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/AuditInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/FormTokenInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/RefererInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/RefererInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: 3.4.x

#6780 add animation effects to nav tabs
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_tabs-navs-pagination.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_variables.scss
Labels: 3.4.x, release-notes/exclude

#6784 Fix 1369: duplicate secure option doesn't work correctly
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6778 Remove outdated docs build text
  README.md
Labels: 3.4.x

#6777 Remove "launcher jar" link from downloads list
  README.md
Labels: 3.4.x

#6785 Do not set z-index to prevent children being stuck in stacking context
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
Labels: 3.4.x, release-notes/exclude

#6795 Add method for cache clean for system path directly
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
Labels: 3.4.x, backport-to-3.3, release-notes/exclude

#6799 fix menu hover event
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarContainer.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarDrawer.vue
Labels: 3.4.x, release-notes/exclude

#6801 Layout fixups
  rundeckapp/grails-app/views/common/_baseUiNext.gsp
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
Labels: 3.4.x, release-notes/exclude

#6786 Enable workflow designer by default for snapshot
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.4.x, release-notes/exclude

#6800 Fixup login and logout footer and scrolling
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/pages/login.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_pages.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
Labels: 3.4.x, release-notes/exclude

#6808 Fix: when acl cache is cleaned, auth eval cache should be notified
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/AuthorizationServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3, release-notes/exclude

#6812 Fixup CTA button on first run screen and proj create
  rundeckapp/grails-app/views/framework/_createProjectForm.gsp
  rundeckapp/grails-app/views/menu/home.gsp
Labels: 3.4.x, release-notes/exclude

#6815 Enh/projects table
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/project-list.scss
Labels: 3.4.x, release-notes/exclude

#6766 Updates: property validation and authorization utilities
  core/src/main/java/com/dtolabs/rundeck/core/authorization/AclsUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/authorization/SubjectAuthContext.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyObjectValidator.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/ValidatorSpec.groovy
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/Authorization.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/Authorizations.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/AuthorizationsSpec.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertySummaryValue.gsp
Labels: 3.3.x, 3.4.x, release-notes/exclude
