Repository rundeck/rundeck, pull requests merged in 2021-03, with the labels that each got.

#6807 Fix: ProjectManager fileCache config requires static config
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 3.4.x

#6763 minor code correction
  plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java
  plugins/upvar-plugin/src/test/groovy/org/rundeck/plugins/vars/ExportVarWorkflowStepSpec.groovy
Labels: 3.3.x, 3.4.x, release-notes/exclude

#6820 Fixes the UserGroupSource to pass the username to the script
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptUserGroupSource.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/service/ScriptUserGroupSourceSpec.groovy
Labels: 3.4.x

#6830 Initial utility bar implementation
  rundeckapp/grails-app/views/common/_baseUiNext.gsp
  rundeckapp/grails-app/views/common/_js.gsp
  rundeckapp/grails-app/views/common/_navData.gsp
  rundeckapp/grails-app/views/menu/_projectImportForm.gsp
  rundeckapp/grails-spa/packages/ui-trellis/.env.dist
  rundeckapp/grails-spa/packages/ui-trellis/.gitignore
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarDrawer.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityActionItem.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityBar.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityBarItem.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/utilitybar.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/Copyright.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/RundeckVersionDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/ServerDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/VersionDateDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/VersionDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/VersionIconNameDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/main.js
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/version.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/RundeckInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/RundeckInfoWidget.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/interfaces/AppLinks.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/interfaces/rundeckWindow.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/rundeckService.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Releases.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/UtilityBar.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stories/setup.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/types/window.d.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/utilities/RundeckVersion.ts
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/mainbar.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
  rundeckapp/grails-spa/packages/ui/src/components/central/main.ts
  rundeckapp/grails-spa/packages/ui/src/components/navbar/main.ts
  rundeckapp/grails-spa/packages/ui/src/components/tour/main.js
  rundeckapp/grails-spa/packages/ui/src/components/tour/tourPicker/App.vue
Labels: 3.4.x, release-notes/exclude

#6832 Project Picker
  rundeckapp/grails-app/views/common/_mainbar.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelectButton.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/projectSelect.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/vue-virtual-scroller.d.ts
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/app.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/mainbar.scss
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.4.x, release-notes/exclude

#6816 Deprecated API: version 10 and lower
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
  test/api/test-execution-output-bad-version.sh
  test/api/test-execution-output-v5.sh
  test/api/test-project-bad-version.sh
  test/api/test-project-resources-404.sh
  test/api/test-project-resources.sh
  test/api/test-project.sh
  test/api/test-resources.sh
Labels: 3.4.x

#6806 Fix: "Show all" button on Jobs list is not clickable #1464
  rundeckapp/grails-app/views/framework/_tagsummary.gsp
Labels: 3.4.x

#6752 Allow dynamic attributes in updated Notification UI
  examples/example-java-notification-plugin/build.gradle
  examples/example-java-notification-plugin/gradle/wrapper/gradle-wrapper.jar
  examples/example-java-notification-plugin/gradle/wrapper/gradle-wrapper.properties
  examples/example-java-notification-plugin/gradlew
  examples/example-java-notification-plugin/gradlew.bat
  examples/example-java-notification-plugin/settings.gradle
  examples/example-java-notification-plugin/src/main/java/com/dtolabs/rundeck/plugin/example/ExampleNotificationPlugin.java
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/DynamicFormPluginProp.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/i18n.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropView.vue
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/src/pages/dynamic-form/main.js
Labels: 3.4.x

#6840 Add news widget
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/News.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/news.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/News.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui/src/components/community-news-notification/main.js
  rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
Labels: 3.4.x, release-notes/exclude

#6838 Update java access modifiers to enhance extensibility.
  core/src/main/java/com/dtolabs/rundeck/core/common/Framework.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/FilePluginCache.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginScanner.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/WatchingPluginDirProvider.java
Labels: 3.4.x

#5969 Fix #2301 - Changing to keep empty option value (if no value is passed) even if the option has a default value
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#6836 Avoiding error when parsing user roles that contain commas
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionTest.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#6851 Push layout body down inside content
  grails-repository/grails-app/views/artifact/index.gsp
  grails-webhooks/grails-app/views/webhook/admin.gsp
  rundeckapp/grails-app/views/common/_baseUiNext.gsp
  rundeckapp/grails-app/views/common/execUnauthorized.gsp
  rundeckapp/grails-app/views/communityNews/index.gsp
  rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp
  rundeckapp/grails-app/views/execution/mailNotification/_oldStatus.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/framework/_createProjectForm.gsp
  rundeckapp/grails-app/views/framework/adhoc.gsp
  rundeckapp/grails-app/views/framework/editProject.gsp
  rundeckapp/grails-app/views/framework/editProjectConfig.gsp
  rundeckapp/grails-app/views/framework/editProjectFile.gsp
  rundeckapp/grails-app/views/framework/editProjectNodeSourceFile.gsp
  rundeckapp/grails-app/views/framework/editProjectNodeSources.gsp
  rundeckapp/grails-app/views/framework/nodes.gsp
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/grails-app/views/menu/createProjectAclFile.gsp
  rundeckapp/grails-app/views/menu/createSystemAclFile.gsp
  rundeckapp/grails-app/views/menu/editProjectAclFile.gsp
  rundeckapp/grails-app/views/menu/editSystemAclFile.gsp
  rundeckapp/grails-app/views/menu/executionMode.gsp
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/menu/licenses.gsp
  rundeckapp/grails-app/views/menu/logStorage.gsp
  rundeckapp/grails-app/views/menu/metrics.gsp
  rundeckapp/grails-app/views/menu/plugins.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
  rundeckapp/grails-app/views/menu/projectDelete.gsp
  rundeckapp/grails-app/views/menu/projectExport.gsp
  rundeckapp/grails-app/views/menu/projectHome.gsp
  rundeckapp/grails-app/views/menu/projectImport.gsp
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-app/views/menu/systemConfig.gsp
  rundeckapp/grails-app/views/menu/systemInfo.gsp
  rundeckapp/grails-app/views/menu/userSummary.gsp
  rundeckapp/grails-app/views/menu/wait.gsp
  rundeckapp/grails-app/views/menu/welcome.gsp
  rundeckapp/grails-app/views/passwordUtility/index.gsp
  rundeckapp/grails-app/views/reports/index.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/delete.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/runbook.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
  rundeckapp/grails-app/views/scheduledExecution/upload.gsp
  rundeckapp/grails-app/views/scm/diff.gsp
  rundeckapp/grails-app/views/scm/index.gsp
  rundeckapp/grails-app/views/scm/performAction.gsp
  rundeckapp/grails-app/views/scm/setup.gsp
  rundeckapp/grails-app/views/searchPlugins/index.gsp
  rundeckapp/grails-app/views/user/edit.gsp
  rundeckapp/grails-app/views/user/list.gsp
  rundeckapp/grails-app/views/user/profile.gsp
Labels: 3.4.x, release-notes/exclude

#6852 Fix exploded button groups
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
Labels: 3.4.x, release-notes/exclude

#6854 Scope multiselect css
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/DynamicFormPluginProp.vue
Labels: 3.4.x, release-notes/exclude

#6862 Move System Report config menu link to bean definition
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemReportMenuItem.groovy
Labels: 3.4.x, release-notes/exclude

#6864 Apply margin rule to direct card footer children
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
Labels: 3.4.x, release-notes/exclude

#6849 Add group: and user: urn support for ACL subjects
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
Labels: 3.4.x

#6847 Add bcrypt credential type for PropertyFileLoginModule
  rundeckapp/build.gradle
  rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/BcryptCredentialProvider.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/JettyCompatibleSpringSecurityPasswordEncoder.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/passwordutil/HiddenInputPasswordUtilityEncrypter.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/passwordutil/JettyPasswordUtilityEncrypter.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/passwordutil/JettyPasswordUtilityEncrypterTest.groovy
  rundeckapp/src/test/groovy/rundeckapp/cli/CommandLineSetupTest.groovy
Labels: 3.4.x, needs documentation

#6861 Update base Docker image
  docker/official/Dockerfile
  docker/ubuntu-base/Dockerfile
Labels: 3.4.x

#6872 Link to community news page
  rundeckapp/grails-app/views/common/_js.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/News.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/interfaces/AppLinks.ts
  rundeckapp/grails-spa/packages/ui/src/components/community-news-notification/main.js
Labels: 3.4.x, release-notes/exclude

#6873 Remove secondary so buttons stand out better on darker background
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
Labels: release-notes/exclude

#6874 Remove projtabs link
  rundeckapp/grails-app/views/common/_mainbar.gsp
Labels: 3.4.x, release-notes/exclude

#6846 Remove File Base Project storage capability
  core/src/main/java/org/rundeck/app/acl/ACLFSFileManager.java
  core/src/test/groovy/org/rundeck/app/acl/ACLFSFileManagerSpec.groovy
  docker/official/test/remco/test.yml
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFilesystemProjectImporter.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFrameworkFactory.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/CombinedContextACLManager.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/ContextACLStorageFileManagerFactory.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFilesystemProjectImporterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/authorization/CombinedContextACLManagerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.4.x, needs documentation

#6875 Fix for rdicon icon sizes in util bar
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityActionItem.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityBar.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue
Labels: 3.4.x, release-notes/exclude

#6829 fix: 500 error for workflow API response if no read or view auth
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#6865 Update AWS source model plugin version.
  build.yaml
  rundeckapp/build.gradle
Labels: 3.4.x

#6859 cleanup execution in non-cluster mode
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpTest.groovy
Labels: 3.4.x

#6833 Fix: use correct project auth context to eval some project access
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.4.x

#6877 Use correct method name in test
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x, release-notes/exclude

#6628 Enable Project based ACLs for Key Storage under keys/project/<NAME>/ paths
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProject.java
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/AuthRundeckStorageTree.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/AuthStorageContextProvider.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/KeyStorageContextProvider.java
  core/src/main/java/com/dtolabs/rundeck/core/storage/ProjectKeyStorageContextProvider.java
  core/src/test/groovy/com/dtolabs/rundeck/core/storage/ProjectKeyStorageContextProviderSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/storage/AuthRundeckStorageTreeTest.java
  rundeckapp/grails-app/assets/javascripts/menu/storage.js
  rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/services/rundeck/services/StorageService.groovy
  rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
  rundeckapp/grails-app/views/framework/_storageBrowseModalKO.gsp
  rundeckapp/grails-app/views/framework/_storageBrowser.gsp
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue
  rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
Labels: 3.3.x, 3.4.x

#6869 deprecated API endpoint removal
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/CliAuthTester.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  test/api/include.sh
  test/api/test-execution-abort-json.sh
  test/api/test-execution-abort.sh
  test/api/test-execution-cleaner-job.sh
  test/api/test-execution-output-plain-lastlines.sh
  test/api/test-execution-output-plain.sh
  test/api/test-execution-output-utf8.sh
  test/api/test-execution-output.sh
  test/api/test-execution-state.sh
  test/api/test-execution.sh
  test/api/test-executions-query-v11.sh
  test/api/test-executions-query.sh
  test/api/test-executions-running.sh
  test/api/test-history.sh
  test/api/test-job-flip-scheduleEnabled-scheduler-bug.sh
  test/api/test-jobs-export-invalid-project.sh
  test/api/test-jobs-export-missing-project.sh
  test/api/test-jobs-export-yaml.sh
  test/api/test-jobs-export.sh
  test/api/test-jobs-import-invalid.sh
  test/api/test-jobs-import-project.sh
  test/api/test-jobs-import-v13.sh
  test/api/test-jobs-import-yaml-project.sh
  test/api/test-jobs-invalid-project.sh
  test/api/test-jobs-missing-project.sh
  test/api/test-jobs-v13.sh
  test/api/test-project-export.sh
  test/api/test-project-import.sh
  test/api/test-project-resources.sh
  test/api/test-resource.sh
  test/api/test-resources.sh
  test/api/test-run-script-interpreter.sh
  test/api/test-run-script.sh
Labels: 3.4.x

#6882 update trigger_downstream_snapshots & trigger_downstream_releases fun…
  scripts/travis-helpers.sh
Labels: 3.4.x, release-notes/exclude

#6886 project key storage ACL settings
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesHelp.vue
Labels: 3.4.x

#6745 Add usersync configuration options to Docker Remco templates
  docker/official/remco/templates/rundeck-config.properties
Labels: 3.3.x, 3.4.x

#6902 Set projectKeyStorage feature flag to be true by default . Fix issu…
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
Labels: 3.4.x

#6905 Fix modal on commands and joblist screen
  rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
  rundeckapp/grails-app/views/menu/_jobslist.gsp
Labels: 3.4.x, release-notes/exclude

#6853 Refactorings on running executions status
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionValidator.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/JobValidationReference.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobReference.java
  rundeckapp/grails-app/assets/javascripts/executionStateKO.js
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionValidatorService.groovy
  rundeckapp/grails-app/views/execution/_wfstateSummaryLine.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/menu/_runningExecutions.gsp
  rundeckapp/grails-app/views/reports/_activityLinks.gsp
  rundeckapp/grails-app/views/reports/_baseReport.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/exec-state.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/exec-status.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-state.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-status.scss
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-activity/i18n.js
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionQuery.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionValidatorServiceSpec.groovy
Labels: 3.4.x, release-notes/exclude

#6509 Fix win32 build
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui/package.json
Labels: 3.3.x, 3.4.x, release-notes/exclude

#6839 Fix multiple SCM Integration Issues
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPluginFactory.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactory.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPluginFactory.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Common.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/views/scm/_pluginConfigList.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: 3.3.x, 3.4.x, backport-to-3.3

#6911 Fix/scm clean
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPluginFactory.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPluginFactory.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactory.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPluginFactory.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3, bug

#6909 scm delete nows perfoms a clean before deleting the configuration
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6914 fix #6889 incorrect ids for exclude filter radios
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Labels: 3.4.x

#6828 Db migration conversion
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/conf/DataSource.groovy
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/RundeckCliOptions.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckDbMigration.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitConfig.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckWebAppInitializer.groovy
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/AuthToken.groovy
  rundeckapp/grails-app/migrations/core/BaseReport.groovy
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
  rundeckapp/grails-app/migrations/core/Execution.groovy
  rundeckapp/grails-app/migrations/core/HibernateIndex.groovy
  rundeckapp/grails-app/migrations/core/JobFileRecord.groovy
  rundeckapp/grails-app/migrations/core/LogFileStorageRequest.groovy
  rundeckapp/grails-app/migrations/core/NodeFilter.groovy
  rundeckapp/grails-app/migrations/core/Notification.groovy
  rundeckapp/grails-app/migrations/core/Orchestrator.groovy
  rundeckapp/grails-app/migrations/core/PluginMeta.groovy
  rundeckapp/grails-app/migrations/core/Project.groovy
  rundeckapp/grails-app/migrations/core/RDOPTION.groovy
  rundeckapp/grails-app/migrations/core/RDUSER.groovy
  rundeckapp/grails-app/migrations/core/ReferencedExecution.groovy
  rundeckapp/grails-app/migrations/core/ReportFilter.groovy
  rundeckapp/grails-app/migrations/core/ScheduledExecution.groovy
  rundeckapp/grails-app/migrations/core/Storage.groovy
  rundeckapp/grails-app/migrations/core/StoredEvent.groovy
  rundeckapp/grails-app/migrations/core/Tag-3.4.0.groovy
  rundeckapp/grails-app/migrations/core/Webhook.groovy
  rundeckapp/grails-app/migrations/core/Workflow.groovy
  rundeckapp/src/integration-test/groovy/rundeck/init/RundeckDbMigrationTest.groovy
  rundeckapp/src/integration-test/resources/changelog-test.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
  rundeckapp/templates/config/rundeck-config.properties.template
Labels: 3.4.x, release-notes/exclude

#6916 Plugin Repository UI Refine
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/src/pages/repository/App.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/Repository.vue
Labels: 3.4.x

#6919 move System Configuration to a menu item
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemConfigMenuItem.groovy
Labels: 3.4.x

#6920 Change text shown when waiting for logs to match UI
  rundeckapp/grails-app/i18n/messages.properties
Labels: 3.4.x

#6915 Remove notificationsEditorVue feature toggle, remove old notifications ui code
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
Labels: 3.4.x

#6891 Add splash screen update and stickers section
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/firstrun.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/RundeckInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stories/setup.ts
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/src/components/first-run/main.ts
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.4.x

#6921 Update lib dependency versions for bouncy castle, hibernate, jackson,…
  gradle.properties
  plugins/git-plugin/build.gradle
  plugins/jasypt-encryption-plugin/build.gradle
  rundeckapp/build.gradle
Labels: 3.3.x

#6925 Align asset pipeline plugin versions for all grails plugins.
  grails-metricsweb/build.gradle
  grails-persistlocale/build.gradle
  grails-repository/build.gradle
  grails-securityheaders/build.gradle
  grails-webhooks/build.gradle
Labels: 3.4.x

#6928 Fixup server display
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/ServerDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts
Labels: 3.4.x, release-notes/exclude

#6929 Add indexes on Execution and LogFileStorageRequest columns that are used in queries.
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
Labels: 3.4.x

#6930 Add indexes to Execution and LogFileStorageRequest to improve performance.
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
Labels: 3.3.x

#6927 fix for db migration with mariadb
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
Labels: 3.4.x

#6937 Enhance Call to Action Buttons
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
Labels: 3.4.x, release-notes/exclude

#6939 Update tomcat jdbc lib to 9.0.44.
  rundeckapp/build.gradle
Labels: 3.4.x

#6940 retrieving scheduled executions without using cache
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Export.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
Labels: 3.4.x, backport-to-3.3, bug
