Repository rundeck/rundeck, pull requests merged in 2021-09, with the labels that each got.

#7233 RUN-354: Update project picker to respect GUI startpage setting
  rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
Labels: 3.4.x

#7237 RUN-366: Migration to change adhoc_local_string column type from VARCHAR to NVARCHAR on SQL Server database.
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/Tag-3.4.4.groovy
  rundeckapp/grails-app/migrations/core/WorkflowStepVARCHARtoNVARCHAR.groovy
Labels: 3.4.x

#7226 RUN-324: Grant webhooks permissions with project based ACL
  grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Labels: 3.4.x

#7243 RUN-373: Fix/accessible styles mr
  rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/input-group.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/text.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_inputs.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_typography.scss
Labels: release-notes/exclude

#7242 Fix Readme Download Issues
  README.md
Labels: release-notes/exclude, 3.4.x

#7246 Enhancements and fixes in support of workflow editing
  rundeckapp/grails-app/views/execution/_wflistitemContent.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/AceEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/AceEditorVue.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Plugins.ts
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/rundeck-icon.scss
Labels: release-notes/exclude, 3.4.x

#7245 RUN-373: Change font fill to solid white
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_variables.scss
Labels: release-notes/exclude, 3.4.x

#7244 RUN-373: add Jost variable font
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/Jost-Italic-VariableFont_wght.woff2
  rundeckapp/grails-spa/packages/ui-trellis/theme/fonts/Jost-VariableFont_wght.woff2
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_typography.scss
Labels: 3.4.x

#7251 Fix: dismissible alert x button too far right
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/bootstrap/stylesheets/bootstrap/_alerts.scss
Labels: 3.4.x

#7250 RUN-384: Fix duplicated node filter after save a job
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/views/common/_queryFilterManagerModal.gsp
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Labels: 3.4.x, to-jira

#7260 Add app_admin/ops_admin, added resource type definitions
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthConstants.java
Labels: release-notes/exclude, 3.4.x

#7255 Patch styles
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/theme-light.scss
  test/selenium/src/pages/jobShow.page.ts
Labels: release-notes/exclude, 3.4.x

#7151 RUN-113: unable to delete project with 100 k executions
  rundeckapp/grails-app/domain/rundeck/BaseReport.groovy
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/views/menu/_projectDeleteForm.gsp
Labels: 3.4.x

#7259 fix to include payload format and http method on notification importing
  rundeckapp/grails-app/domain/rundeck/Notification.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyWebhookNotificationPlugin.groovy
  rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
Labels: 3.4.x

#7269 Grant permission to delete webhook with project based ACL.
  grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Labels: 3.4.x

#7271 bump snapshot version to 3.4.5
  gradle.properties
  version.properties
Labels: 3.4.x

#7248 RUN-138: Fix: Improve Limit log feature for better behavior with large logs
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/logging/LoggingThreshold.groovy
  rundeckapp/src/test/groovy/rundeck/services/logging/LoggingThresholdSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/logging/LoggingThresholdTest.groovy
  rundeckapp/src/test/groovy/rundeck/services/logging/ThresholdLogWriterSpec.groovy
Labels: 3.4.x

#7256 RUN-181: add a flag to disable Local Execution and Local File Copier
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopier.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopierSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutorSpec.groovy
Labels: 3.4.x, to-jira

#7268 Add api token type RUNNER
  core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenType.java
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: release-notes/exclude, 3.4.x

#7264 RUN-345: Add functionality to specify a blocklist of plugins
  .circleci/config.yml
  .travis.yml
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginBlocklist.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckEmbeddedPluginExtractor.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckPluginBlocklist.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
  test/api/blocklist-missing-plugin-test.sh
  test/api/blocklist-plugin-count-test.sh
  test/api/include.sh
  test/docker/docker-compose-plugin-blocklist.yaml
  test/docker/dockers/rundeck/data/blocklist.yaml
  test/docker/dockers/rundeck/scripts/run-plugin-blocklist-api-tests.sh
  test/docker/dockers/rundeck/scripts/start_rundeck.sh
  test/docker/test-api-plugin-blocklist.sh
  test/run-docker-plugin-blocklist-test.sh
Labels: 3.4.x

#7253 fix: abort attempt may fail to retry
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Labels: 3.4.x
