Repository rundeck/rundeck, pull requests merged in 2021-06, with the labels that each got.

#7100 [RUN-61]fix rundeckpro/rundeckpro#1823 check if sequences
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
  rundeckapp/grails-app/migrations/core/HibernateIndex.groovy
Labels: 3.4.x

#7106 Fix rundeckpro-1824 ent logstorage config [RUN-78]
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/PluginCustomizer.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#7117 Bump SNAPSHOT version to 3.4.1
  gradle.properties
  version.properties
Labels: 3.4.x

#6823 Fix: Add support for unquoted options (rundeck will supply the value as-is)
  core/src/main/java/com/dtolabs/rundeck/core/data/ScriptVarExpander.java
  core/src/main/java/com/dtolabs/rundeck/core/data/SharedDataContextUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/dispatcher/DataContextUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArg.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArgList.java
  core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/DataContextUtilsSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/SharedDataContextUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/ExecArgListTest.java
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: 3.4.x, enhancement, needs documentation

#7120 RUN-124: Scope Ace setup to execution plugin tab
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Labels: 3.4.x

#7123 Fix: option values enabled by default dev mode
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Labels: 3.4.x, release-notes/exclude

#7021 Fix: git build info is cached and not cleaned
  rundeckapp/build.gradle
Labels: 3.4.x

#7095 RUN-136: access control did not allow to toggle execution enabled/disabled option even if allowed by ACL policy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#7108 RUN-7: dropdown context menu to be shown on the notification edit modal
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
Labels: 3.4.x

#7115 RUN-75: Adding maxsize and expiration time for fileUploadService config on RundeckConfigBase
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 3.4.x, needs documentation

#7093 Bump rundeck client version to 0.2.3
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui/package-lock.json
  rundeckapp/grails-spa/packages/ui/package.json
Labels: 3.4.x

#7126 RUN-127: Fix: Unable to edit a job after removing a plugin used in that job
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#7119 RUN-106: Enh: Support for Enteprise Change Password on user profile
  rundeckapp/grails-app/views/user/profile.gsp
Labels: 3.4.x, release-notes/exclude

#6964 RUN-153: remove grails-plugin-publish from grails plugins used by rundeckapp
  grails-metricsweb/build.gradle
  grails-persistlocale/build.gradle
  grails-repository/build.gradle
  grails-securityheaders/build.gradle
  grails-webhooks/build.gradle
Labels: 3.4.x, release-notes/exclude, to-jira

#7121 RUN-64: Fix: optionValuePlugins list disappears when when a validation errors
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
Labels: 3.4.x

#7133 RUN-141: Fix: UI Bug with Projects list that hinders display over 15 projects in a list.
  rundeckapp/grails-app/assets/javascripts/menu/home.js
Labels: 3.4.x

#7060 RUN-130: Allowed apostrophe character on first name and last name fields
  rundeckapp/grails-app/domain/rundeck/User.groovy
Labels: 3.4.x
