Repository rundeck/rundeck, pull requests merged in 2021-05, with the labels that each got.

#7022 SCM: Fix job sourceId not appearing in exported file path
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6983 Fix #6982 plugin meta was not deleted with project
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobMetadataServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6996 Fix: #6790 cancel job create/edit with FR/JA lang doesn't work
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp
  test/selenium/src/__tests__/selenium/jobs/job-create-cancel-i18n.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/userProfile.page.ts
Labels: 3.4.x

#6987 Fix: Create index for errorHandler on WorkflowStep table to help prevent deadlocks in MSSQL
  rundeckapp/grails-app/domain/rundeck/WorkflowStep.groovy
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/WorkflowStep.groovy
Labels: 3.4.x

#6953 Enh: Adding access to Key Storage for Webhook Plugins
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Labels: 3.4.x

#6959 Fix: /login/authAjax redirect loop for ajax requests
  rundeckapp/grails-app/conf/application.groovy
Labels: 3.4.x, backport-to-3.3

#6892 Enh: Allow access to Key Storage for Node Resources Script Plugins
  core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactory.java
  core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactorySpec.groovy
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesConfig.vue
Labels: 3.4.x

#7033 fix url mapping for System Report Menu Item
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemReportMenuItem.groovy
Labels: 3.4.x, backport-to-3.3

#6976 Fix: Oracle saves empty fields as null and results in bug in comparison code
  rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
Labels: 3.4.x, bug

#7007 Kill process when thread for local command is interrupted
  core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java
  core/src/test/groovy/com/dtolabs/rundeck/core/utils/ScriptExecUtilSpec.groovy
Labels: 3.4.x

#6971 Fix: "Duplicate to other project" option visibility
  rundeckapp/grails-app/taglib/rundeck/AuthTagLib.groovy
Labels: 3.4.x

#7031 Fix: externally deleted job not reflected in scm import status
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.4.x

#6922 Cleanup: jobs import api endpoint requires apiv14
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 3.4.x

#6986 Including job list type on parameters when triggering job search
  rundeckapp/grails-app/views/menu/_groupTree.gsp
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
Labels: 3.4.x, bug, gui

#6992 "Event" resource ACLs at project level are not being honored (cherry picked from commit be2a67558729ff1edeb4c2363b6a81768c5d2f04)
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.3.x, backport-to-3.3

#6977 Fix: layout issues: scm import screen
  rundeckapp/grails-app/views/scm/performAction.gsp
Labels: 3.4.x, release-notes/exclude

#7048 initialize cmdDatavariable used in closure
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.4.x

#7051 Set node version in TravisCI
  .travis.yml
Labels: 3.4.x, release-notes/exclude

#7055 Fix stuck progress bar on oversized logs
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
  rundeckapp/grails-spa/packages/ui-trellis/tests/data/fixtures/ExecOverSize.json
Labels: 3.4.x

#7052 Enh/project config change event
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 3.4.x

#7056 fix: project ACL change is not refreshed in cluster
  core/src/main/java/org/rundeck/app/acl/ACLCacheControl.java
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/AuthorizationServiceSpec.groovy
Labels: 3.4.x

#7046 Fixed css style of okta login button
  rundeckapp/grails-app/domain/rundeck/User.groovy
Labels: 3.4.x, release-notes/exclude

#7042 Remove margin on text color in card
  rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
Labels: 3.4.x, release-notes/exclude

#7062 Adjust Size of Skeleton List & Color
  rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/Skeleton.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
Labels: release-notes/exclude

#7065 fix margin again
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_cards.scss
Labels: 3.4.x, release-notes/exclude

#7068 Fix error page layout
  rundeckapp/grails-app/views/error.gsp
Labels: 3.4.x, release-notes/exclude

#7072 Remove legacy log output feature
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/assets/javascripts/executionStateKO.js
  rundeckapp/grails-app/assets/javascripts/framework/adhoc.js
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/framework/adhoc.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp
Labels: 3.4.x

#7047 Add loading skeletons
  rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/Skeleton.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/skeleton.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/News.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/News.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts
Labels: 3.4.x

#7074 Fix #7073 docker rolling logs not working
  docker/official/remco/templates/log4j2.properties
Labels: 3.4.x

#7076 Fix #7075 kill job button doesn't work
  rundeckapp/grails-app/views/execution/show.gsp
  test/selenium/src/__tests__/selenium/execution/adhoc-command-page-abort.test.ts
  test/selenium/src/__tests__/selenium/execution/execution-show-page-abort.test.ts
  test/selenium/src/pages/adhocCommand.page.ts
  test/selenium/src/pages/executionShow.page.ts
Labels: 3.4.x

#6967 Enh: Change default server.address to localhost instead of hostname to generate default rundeck-config.properties
  rundeckapp/templates/config/rundeck-config.properties.template
Labels: 3.4.x, enhancement, needs documentation

#7082 [internal enhancement] execution views cleanup on execution show page
  rundeckapp/grails-app/assets/javascripts/executionStateKO.js
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  test/selenium/src/__tests__/selenium/execution/execution-show-page-views.test.ts
  test/selenium/src/pages/adhocCommand.page.ts
  test/selenium/src/pages/executionShow.page.ts
Labels: 3.4.x, release-notes/exclude

#7080 Add Style for Fixed Table and Word Breaks
  rundeckapp/grails-app/views/execution/_execDetails.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tables.scss
Labels: 3.4.x

#7087 Refactor: auth success user profile updates decoupled from UserService
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandler.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandlerSpec.groovy
Labels: release-notes/exclude

#7089 Fix: bundled groovy plugins should be overwritten when extracted
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckEmbeddedPluginExtractor.groovy
Labels: 3.4.x, backport-to-3.3, release-notes/exclude
