Repository rundeck/rundeck, pull requests merged in 2021-07, with the labels that each got.

#7143 fix issue on exported data vars for job references not being exported… [RUN-167]
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: 3.4.x

#7129 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 3.4.x

#7159 Bump snapshot to 3.4.2
  gradle.properties
  version.properties
Labels: 3.4.x, release-notes/exclude

#7150 RUN-220: FIX: npe if execution fails to start
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
Labels: 3.4.x, to-jira

#7158 RUN-121: Remove 1 second timeout for request
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/News.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts
Labels: 3.4.x

#7153 RUN-222: SCM Loader enhancement: avoid failed plugin will be init on background iteration
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.4.x

#7030 RUN-151: Fix: Properly detect when a job was renamed in SCM Import
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobImportState.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobImporter.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobRenamed.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ImportTracker.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/JobImportGitState.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/JobRenamedImp.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ContextJobImporter.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ResolvedJobImporter.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/grails-app/views/scm/diff.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Labels: 3.4.x, backport-to-3.3, to-jira

#7137 RUN-143: Handles null value when resource does not have the attribute filtered by rule key
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
Labels: 3.4.x, backport-to-3.3

#7178 RUN-189: Upgrade pywinrm plugin. Excluded RD_EXEC_COMMAND from environment var…
  build.yaml
Labels: 3.4.x

#7170 RUN-191: Fix to properly show SSO login button
  rundeckapp/grails-app/views/user/login.gsp
Labels: 3.4.x, backport-to-3.3, bug

#7173 RUN-194: Fix errors from 1000+ Executions on Oracle Database
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Labels: 3.4.x

#7122 RUN-232: Job import does not preserve option value ordering
  rundeckapp/grails-app/domain/rundeck/Option.groovy
Labels: 3.4.x, to-jira

#6990 RUN-256: Make log levels configurable on Docker Image via Remco
  docker/official/README.md
  docker/official/remco/templates/log4j2.properties
Labels: 3.4.x, to-jira

#7181 RUN-222: SCM Loader enhancement Part 2
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
Labels: 3.4.x, release-notes/exclude

#7179 RUN-190: Remove old release version arg from setversion.sh
  setversion.sh
Labels: 3.4.x

#7142 RUN-63 and RUN-155: Fixes Sort list of plugins by key order.
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Labels: 3.4.x

#7163 RUN-252: Optional BindDN in JAAS login module template for Docker Image
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: 3.4.x, to-jira

#7194 RUN-285: Fix navbar overflow during zoom
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBar.vue
Labels: 3.4.x, to-jira

#7186 Hotfix: Update to output new TAG
  setversion.sh
Labels: 3.4.x

#7196 RUN-288: Fix copybox to work if connection is insecure
  rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/copybox/CopyBox.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/Switch.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/utilities/Clipboard.ts
Labels: 3.4.x, to-jira
