Repository rundeck/rundeck, pull requests merged in 2021-12, with the labels that each got.

#7401 RUN-492: Project import including all but executions
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
Labels: 3.4.x

#7396 RUN-523: Fix display bug with Project Settings
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBar.vue
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
Labels: 3.4.x

#7405 Post main branch generated artifacts to a latest bucket in S3
  .circleci/config.yml
  scripts/circle-helpers.sh
Labels: 3.4.x

#7386 Fix issue serving user assets
  rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/DefaultInterceptorHelperSpec.groovy
Labels: 3.4.x

#7408 Enh | Add utility classes for Max Width and Flex
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_utilities.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_variables.scss
Labels: 3.4.x

#7412 RUN-532: fix cannot edit job with basic orchestrator
  rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/execution/_execDetails.gsp
  rundeckapp/grails-app/views/execution/_execDetailsOrchestrator.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp
  rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/NotificationsEditorSection.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue
  rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: 3.4.x

#7416 Enh/UI updates
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-app/views/menu/projectHome.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_code.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_utilities.scss
Labels: 3.4.x

#7421 Update chromedriver
  test/selenium/package.json
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/testdeck/package.json
  test/testdeck/src/projectImporter.ts
Labels: release-notes/exclude, 3.4.x

#7418 WIP: restore tomcat test behavior
  rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/DefaultInterceptorHelperSpec.groovy
  test/api/testall.sh
  test/docker/dockers/tomcat/scripts/run_api_tests.sh
  test/docker/test-api-tomcat.sh
Labels: release-notes/exclude, 3.4.x

#7427 Fix #7424 update log4j dependency
  rundeckapp/build.gradle
  testbuild.groovy
Labels: 3.4.x

#7428 Node Filter Save Button
  rundeckapp/grails-app/views/framework/nodes.gsp
Labels: 3.4.x

#7430 Disable flaky test
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
Labels: release-notes/exclude, 3.4.x

#7420 RUN-541: Fix: Job options misbehaviors when reordering/duplicating
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Labels: 3.4.x

#7434 RUN-533: Fixed ldap user information on profile
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
Labels: 3.4.x

#7435 RUN-547: Address CVE-2021-45046 Update log4j2 to 2.16.0
  gradle.properties
  rundeckapp/build.gradle
  testbuild.groovy
Labels: 3.4.x, backport-to-3.3

#7436 RUN-548: Export to another instance fix
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
Labels: 3.4.x

#7445 RUN-552: Update log4j to 2.17.0 fix #7443
  gradle.properties
  testbuild.groovy
Labels: 3.4.x, backport-to-3.3
