Repository rundeck/rundeck, pull requests merged in 2021-11, with the labels that each got.

#7350 RUN-465 Fixes duplicated job scheduling after renaming job/group
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobReference.java
  rundeckapp/grails-app/services/rundeck/services/JobReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.4.x

#7344 #7342 : Address color issues in tags
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_labels.scss
Labels: 3.4.x

#7348 Add Copy Box for job id
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
  rundeckapp/grails-spa/packages/ui/src/components/copybox/main.ts
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 3.4.x

#7351 add darkmode styles for vue good table
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_tables.scss
Labels: 3.4.x

#7286 RUN-415: Migrate off travis
  .circleci/circle-shim.sh
  .circleci/config.yml
  .circleci/travis-shim.sh
  .travis.yml
  scripts/circle-build.sh
  scripts/circle-helpers.sh
Labels: 3.4.x

#7354 reference main packaging-core branch always
  .circleci/config.yml
Labels: 3.4.x

#7276 RUN-413: UI: update job editor nodes section to Vue
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/views/execution/_execDetails.gsp
  rundeckapp/grails-app/views/framework/_displayNodeSetFilters.gsp
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
  rundeckapp/grails-spa/packages/ui/src/components/form/InlineValidationErrors.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeDetailsSimple.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterInput.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterLink.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterResults.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeIcon.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeListEmbed.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeShowEmbed.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeStatus.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/OrchestratorEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/NotificationsEditorSection.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/main.js
  rundeckapp/grails-spa/packages/ui/src/utilities/genUrl.ts
  rundeckapp/grails-spa/packages/ui/src/utilities/nodeUi.ts
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: 3.4.x, to-jira

#7359 RUN-478: add found Token principal to subject when used for API requests
  core/src/main/java/com/dtolabs/rundeck/core/authentication/Token.java
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
Labels: release-notes/exclude, 3.4.x

#7358 fix height for input
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
Labels: 3.4.x

#7356 RUN-482: Bump to spring-security 5.2.0
  gradle.properties
Labels: 3.4.x

#7374 update sanitizer dependency
  rundeckapp/build.gradle
Labels: 3.4.x

#7368 update style for alerts
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_alerts.scss
Labels: 3.4.x

#7364 Enh: Multi Input Style
  rundeckapp/grails-app/views/framework/_nodeFilterInputGroup.gsp
  rundeckapp/grails-app/views/framework/nodes.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
  test/selenium/src/pages/adhocCommand.page.ts
Labels: 3.4.x

#7375 RUN-387: fix: new Ace editor supports min/maxLines for auto sizing of editor
  rundeckapp/grails-app/assets/javascripts/application.js
Labels: 3.4.x

#7357 RUN-479: Including runAtTime parameter on Run Job Later feature
  rundeckapp/grails-app/assets/javascripts/scheduler.js
Labels: 3.4.x

#7369 update icon color
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-status.scss
Labels: 3.4.x

#7372 bump to 3.4.7 version
  gradle.properties
  version.properties
Labels: release-notes/exclude, 3.4.x

#7377 exclude guava dependency from owasp
  rundeckapp/build.gradle
Labels: 3.4.x

#7261 Allow absolute redirectUrl in preauthenticated
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
Labels: 3.4.x, to-jira

#7387 upgrade to pywinrm plugin 2.0.15
  build.yaml
Labels: 3.4.x

#7383 RUN-493 Add warning message if changing job scheduling on a cluster
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.4.x

#7385 Fix/darkmode updates
  rundeckapp/grails-app/views/menu/_editAclFile.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_buttons.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_code.scss
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginURLUploadForm.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginUploadForm.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/views/UploadPluginView.vue
Labels: 3.4.x

#7390 RUN- 514 Mssql to nvarchar on workflow_step
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/Tag-3.4.7.groovy
  rundeckapp/grails-app/migrations/core/WorkflowStepNVARCHAR.groovy
Labels: 3.4.x

#7389 RUN-513: option default value bad parsing
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Labels: 3.4.x

#7378 add classes to fix layout
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_sidebar-and-main-panel.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
Labels: 3.4.x

#7363 Remove out of date files
  CHANGELOG.md
  Makefile
  RELEASE.md
  jenkins-build.sh
  release.sh
  releaseversion.js
Labels: release-notes/exclude, 3.4.x
