Repository rundeck/rundeck, pull requests merged in 2021-04, with the labels that each got.

#6945 Adjust SCM UI and Installed Plugins Style
  rundeckapp/grails-app/views/scm/performAction.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_utilities.scss
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/ProviderCard.vue
Labels: 3.4.x

#6952 Enhance SCM UI
  rundeckapp/grails-app/views/scm/_statusBadge.gsp
  rundeckapp/grails-app/views/scm/diff.gsp
  rundeckapp/grails-app/views/scm/performAction.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_utilities.scss
Labels: 3.4.x

#6949 Fix: run job error might not seen, replace with modal
  rundeckapp/grails-app/views/menu/jobs.gsp
Labels: 3.4.x

#6943 Fixes arguments of method called to handle schedules from project config API
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Labels: 3.4.x, bug

#6948 fix: use aclFileManager to read project acls for export
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6954 Update Style of Installed Plugins
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/ProviderCard.vue
Labels: 3.4.x

#6965 Adjust style of modal pagination
  rundeckapp/grails-app/views/menu/_jobPickerModalPagination.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tabs-navs-pagination.scss
Labels: 3.4.x

#6938 Handles job pagination (if enabled) on referenced job picker modal
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/views/menu/_groupTree.gsp
  rundeckapp/grails-app/views/menu/_jobPickerModalPagination.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tabs-navs-pagination.scss
Labels: 3.4.x, bug

#6871 Replacing code that fetches the list of ScheduledExecutions parents to use criteria and improve query time
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
  rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
Labels: 3.4.x

#6962 Adjust Executions Options Section
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/execution-page.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/jobs.scss
Labels: 3.4.x

#6963 Sec: Remove apache httpclient 3.1
  core/build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/common/impl/URLFileUpdater.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/http/ApacheHttpClient.java
  core/src/main/java/com/dtolabs/rundeck/core/http/HttpClient.java
  core/src/main/java/com/dtolabs/rundeck/core/http/RequestProcessor.java
  core/src/main/java/com/dtolabs/rundeck/core/resources/URLResourceModelSource.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutorSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/http/ApacheHttpClientSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/common/impl/TestURLFileUpdater.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
  core/src/test/java/com/dtolabs/rundeck/core/resources/TestURLResourceModelSource.java
  gradle.properties
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  testbuild.groovy
Labels: 3.4.x, backport-to-3.3, security

#6985 Updated Messages for ja_JP (Japanese)
  rundeckapp/grails-app/i18n/messages_ja.properties
Labels: 3.4.x

#6998 Scm performance enhancements
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/SynchState.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/SynchAction.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/assets/javascripts/menu/jobs.js
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scm/_scmExportStatus.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#6978 SCM import button in jobs page
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
Labels: 3.4.x, backport-to-3.3, release-notes/exclude

#6993 Enh: Add button to Commit SCM changes in jobs list page
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#7003 Scm/bp 3.3.x
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/SynchState.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/SynchAction.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/assets/javascripts/menu/jobs.js
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/grails-app/views/menu/_workflowsFull.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scm/_scmExportStatus.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.3.x

#7002 Scm enhancement cleanup
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
Labels: 3.4.x

#7011 Scm: Loader Fix and Sync Config Changes
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#7008 Fix: deleted jobs not reflected in project synch state
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/jobs/PatternJobFileMapper.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: 3.4.x, backport-to-3.3

#7016 SCM Import: fix import of renamed jobs
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
Labels: 3.4.x, backport-to-3.3
