Repository rundeck/rundeck, pull requests merged in 2021-01, with the labels that each got.

#6695 Move logo to assets and allow override
  rundeckapp/grails-app/assets/images/logos/rundeck-logo-black.png
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
Labels: 3.3.x, release-notes/exclude

#6700 Apply shared bintray config from sub projects
  rundeck-authz/bintray.gradle
  rundeck-authz/build.gradle
  rundeck-authz/rundeck-authz-api/build.gradle
  rundeck-authz/rundeck-authz-core/build.gradle
  rundeck-authz/rundeck-authz-yaml/build.gradle
Labels: 3.3.x

#6704 fix #6703 oracle reserved word 'mode'
  rundeckapp/grails-app/domain/rundeck/AuthToken.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/Token.groovy
  rundeckapp/src/test/groovy/rundeck/AuthTokenSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
Labels: 3.3.x, release-notes/exclude

#6702 WIP fix pattern for sql exception check
  test/docker/docker-compose-api-mysql.yaml
Labels: 3.3.x, release-notes/exclude

#6724 remove OSS survey
  README.md
Labels: 3.3.x, release-notes/exclude

#6712 Update pywinrm plugin. Added a function to remove/replace simple quotes when execute command
  build.yaml
Labels: 3.3.x

#6709 Creating a new log filter plugin to mask sensitive output log text
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/MaskLogOutputByRegexPlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/MaskLogOutputByRegexPluginSpec.groovy
Labels: 3.3.x

#6725 Issues/6693 slow job list show page
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/views/common/_js.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
Labels: 3.3.x

#6730 edit framework controller to accept resourceModelSources config when creating a new project
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Labels: 3.3.x

#6732 Fixes webhook notification issue that use credentials in URL
  rundeckapp/grails-app/domain/rundeck/Notification.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyWebhookNotificationPlugin.groovy
  rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.3.x

#6701 Changes to allow to impor nodes only separately from Configurarion
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/views/menu/_projectImportForm.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveImportRequest.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveParams.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  test/api/include.sh
Labels: 3.3.x, needs documentation

#6737 Add hooks for workflow designer
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/assets/javascripts/application.js
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/views/layouts/base.gsp
Labels: 3.3.x, release-notes/exclude

#6738 Update chrome and chromedriver for selenium tests
  test/selenium-docker-compose.yml
  test/selenium/docker-compose.yml
  test/selenium/docker-local-compose.yml
  test/selenium/package.json
  test/testdeck/package.json
Labels: 3.3.x, release-notes/exclude

#6734 fixes rundeckpro/rundeckpro#1454, add in event bus notification when …
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Labels: 3.3.x

#6723 Fix to get schedules both via addon (enterprise-schedules) and via job scheduling (job edit page)
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 3.3.x

#6740 Fix #6614 check plugin exists instead of configuration
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkController2Spec.groovy
Labels: 3.3.x

#6666 Add ability for Node Sources to use Key Storage
  core/src/main/java/com/dtolabs/rundeck/core/authentication/Urn.java
  core/src/main/java/com/dtolabs/rundeck/core/authorization/AclsUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/authorization/SubjectUserAndRoles.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/AclRule.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/AclRuleBuilder.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/AclRuleImpl.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/AclSubject.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/AuthContextProvider.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/TypedSubject.java
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/UserAndRoles.java
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/AclRuleBuilderSpec.groovy
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
  rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/Policy.java
  rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java
  rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/yaml/model/ACLPolicyDoc.java
  rundeck-authz/rundeck-authz-yaml/src/test/groovy/com/dtolabs/rundeck/core/authorization/providers/YamlProviderSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesHelp.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectPluginConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/i18n.js
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/main.js
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/nodeSourcesUtil.ts
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManager.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/BaseAuthContextProvider.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManagerSpec.groovy
Labels: 3.3.x

#6739 Update bootstrap js to 3.3.7
  rundeckapp/grails-app/assets/javascripts/bootstrap/bootstrap.js
Labels: 3.3.x

#6735 Fix SCM icons lost after 3.3.7 upgrade
  rundeckapp/grails-app/assets/javascripts/menu/jobs.js
Labels: 3.3.x

#6748 Additional fix for #6668, fix display of overal scm state
  rundeckapp/grails-app/assets/javascripts/menu/jobs.js
Labels: 3.3.x, release-notes/exclude

#6750 Fix community news post dates
  rundeckapp/grails-spa/packages/ui/src/pages/community-news/CommunityNewsFeed.vue
Labels: 3.3.x
