Repository rundeck/rundeck, pull requests merged in 2022-07, with the labels that each got.

#7803 RUN-1015 Use length check to find unencrypted storage keys
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfig.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfigSpec.groovy
Labels: 4.x

#7808 Bump snapshot version to 4.5.0
  gradle.properties
  version.properties
Labels: 4.x

#7770 instance name color fixed at login and logout
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
Labels: 4.x

#7811 RUN-1058: Add the missing public key into apt trusted list
  .circleci/config.yml
  test/ci-test-docker-selenium.sh
Labels: 4.x

#7809 RUN-1013: Fixed global log limit adding a Failed status on a job
  rundeckapp/grails-app/services/rundeck/services/logging/LoggingThreshold.groovy
  rundeckapp/src/test/groovy/rundeck/services/logging/LoggingThresholdSpec.groovy
Labels: 4.x

#7779 RUN-991: Fix: Incorrect "Forward Slash" parsing in File/URL Step
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutor.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutorSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
Labels: 4.x

#7785 RUN-1006: Fix Notification Property Value type when SCM Export YAML format.
  rundeckapp/grails-app/domain/rundeck/Notification.groovy
  rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
Labels: 4.x

#7780 RUN-790: Fix bug where Health Status Enhancers affects performance with lots of nodes.
  core/src/main/java/com/dtolabs/rundeck/plugins/nodes/NodeEnhancerPlugin.java
  rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy
Labels: 4.x

#7789 RUN-1000: System Report 'Allocated Memory' display broken in the GUI
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
Labels: 4.x

#7778 RUN-1004: Remove "project FS importer" code (disabled since 3.4)
  .circleci/config.yml
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  docker/official/remco/templates/rundeck-config-storage.properties
  docker/official/test/remco/test.yml
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFilesystemProjectImporter.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFrameworkFactory.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/ContextACLStorageFileManagerFactory.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckFilesystemProjectImporterSpec.groovy
  test/docker/common.sh
  test/docker/docker-compose-ssl-test.yml
  test/docker/dockers/rundeck/scripts/start_rundeck.sh
  test/docker/dockers/rundeck/scripts/upload_key_storage.sh
  test/docker/dockers/tomcat/Dockerfile
  test/docker/dockers/tomcat/admin.aclpolicy
  test/docker/dockers/tomcat/entry.sh
  test/docker/dockers/tomcat/framework.properties
  test/docker/dockers/tomcat/scripts/run_api_tests.sh
  test/docker/dockers/tomcat/tokens.properties
  test/run-docker-ansible-tests.sh
  test/run-docker-tomcat-tests.sh
Labels: to-jira, 4.x

#7791 RUN-1045: fixed broken error message that appears when you have not stored a password
  core/src/main/java/com/dtolabs/rundeck/core/storage/TypedStorageTreeImpl.java
  plugins/copyfile-plugin/src/main/java/com/dtolabs/rundeck/plugin/copyfile/CopyFileNodeStepPlugin.java
Labels: 4.x

#7735 RUN-917: update ExecReport table for better queries
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/ExecReportJcExecIdToExecutionId.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/integration-test/groovy/ReportServiceTests.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpIntegrationSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecReportSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: 4.x

#7763 RUN-950: Changing default SCM SSH authentication to SSHJ
  plugins/git-plugin/build.gradle
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ssh/SshjSession.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ssh/SshjSessionFactory.groovy
Labels: to-jira, 4.x

#7788 RUN-994: Show proper error message when an existing filter with same name is already present
  rundeckapp/grails-spa/packages/ui/src/components/activity/savedFilters.vue
Labels: 4.x

#7806 RUN-1054: Fix: Member info not visible on Job tab in Cluster Manager
  rundeckapp/grails-spa/packages/ui/src/components/server-identity/main.js
  rundeckapp/grails-spa/packages/ui/src/components/server-identity/serverIdentity.js
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 4.x

#7805 RUN-1041: Fix Date Format differences in Context Variable output
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
Labels: 4.x

#7817 RUN-1082: Add audit tracking for jobs and acls.
  build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/audit/ActionTypes.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/ResourceTypes.java
  core/src/main/java/com/dtolabs/rundeck/plugins/audit/AuditEventListener.java
  docker/official/remco/templates/log4j2.properties
  examples/example-java-audit-plugin/pom.xml
  plugins/audit-logging-plugin/build.gradle
  plugins/audit-logging-plugin/src/main/groovy/org/rundeck/plugin/audit/AuditLoggerPlugin.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventDispatcher.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
  rundeckapp/templates/config/log4j2.properties.template
  settings.gradle
  test/api/blocklist-plugin-count-test.sh
  testbuild.groovy
Labels: customer request, 4.x

#7822 Revert "RUN-1082: Add audit tracking for jobs and acls."
  build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/audit/ActionTypes.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/ResourceTypes.java
  core/src/main/java/com/dtolabs/rundeck/plugins/audit/AuditEventListener.java
  docker/official/remco/templates/log4j2.properties
  examples/example-java-audit-plugin/pom.xml
  plugins/audit-logging-plugin/build.gradle
  plugins/audit-logging-plugin/src/main/groovy/org/rundeck/plugin/audit/AuditLoggerPlugin.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventDispatcher.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
  rundeckapp/templates/config/log4j2.properties.template
  settings.gradle
  test/api/blocklist-plugin-count-test.sh
  testbuild.groovy
Labels: 4.x

#7820 BUGFIX RUN-1084: unable to update webhook
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Labels: 4.x

#7787 RUN-983: Package Updates to address new CVEs
  build.gradle
  gradle.properties
  rundeckapp/build.gradle
  testbuild.groovy
Labels: 4.x

#7819 RUN-771: Enable Twistlock Scan
  .circleci/config.yml
  scripts/circle-helpers.sh
Labels: 4.x

#7823 RUN-1090: Upgrade spring to 5.3.20
  gradle.properties
Labels: 4.x
