Repository rundeck/rundeck, pull requests merged in 2022-12, with the labels that each got.

#7943 RUN-1226: Runner Node Executor enhancement
  core/src/main/java/com/dtolabs/rundeck/core/common/BaseFrameworkExecutionProviders.java
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IExecutionProviders.java
  core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeSpecifiedService.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestFileCopierService.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestNodeExecutorService.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/AppExecutionPluginLoader.groovy
Labels: to-jira, 4.x

#8032 RUN-1366: remove unneeded rundeck-data-spi library, fix core library dependencies
  core/build.gradle
  grails-webhooks/build.gradle
  grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
  rundeck-app-util/README.md
  rundeck-app-util/build.gradle
  rundeck-app-util/src/main/java/org/rundeck/app/authentication/Token.java
  rundeck-app-util/src/main/java/org/rundeck/app/util/spi/AuthTokenManager.java
  rundeck-data-model/build.gradle
  rundeck-data-model/src/main/java/org/rundeck/spi/data/DataAccessException.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/BaseDataManager.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/DataManager.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/package-info.java
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/RundeckAuthTokenManagerService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/ProviderRegistration.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
  settings.gradle
Labels: 4.x

#8028 RUN-1353 | Overflow Scrollbars on Login Page Removal
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/login.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
Labels: 4.x

#8026 RSE-238 Fix: Dynamic max nodes shown in rundeck GUI
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterResults.vue
Labels: 4.x

#8014 RUN-1223: hidden plugin property rendering and UI components
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/UIStore.ts
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/ui/UiSocket.vue
  rundeckapp/grails-spa/packages/ui/src/components/ui/main.ts
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/i18n.js
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: 4.x

#8039 RUN-1369: Update spring-sec to fixed version
  gradle.properties
Labels: 4.x

#8010 RUN-1200: Enabled feature query API endpoint
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/feature/FeatureEnabledResult.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
  test/api/include.sh
Labels: needs documentation, 4.x

#8031 RSE-259 Fix:Ruleset Plugin fails to evaluate conditions if negative number are used
  core/src/main/java/com/dtolabs/rundeck/core/rules/NumericCondition.java
Labels: 4.x

#8011 RUN-1345: fix incorrect 404 page response for job edit/update page
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 4.x

#8041 RUN-1224: Job Runner Run page GUI
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_show.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 4.x

#7828 RUN-610: Enable stepplugin and nodestepplugin in runner
  core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
Labels: to-jira, 4.x

#8044 RUN-1349 | Fix Missing Execution Clean History Form Display
  rundeckapp/grails-app/views/framework/_editProjectForm.gsp
Labels: 4.x

#8051 RUN-1350: fix: step/global log filters not working after jquery upgrade
  rundeckapp/grails-app/assets/javascripts/menu/logStorage.js
  rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js
  rundeckapp/grails-app/assets/javascripts/workflowStepEditorKO.js
Labels: release-notes/exclude, 4.x

#8049 RUN-1380: Fix defining plugin groups on project creation
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Labels: release-notes/exclude, 4.x

#8055 Run 1386-fix plugin groups deleted when not modified
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Labels: 4.x

#8054 RUN-1385: Fix null definitions in plugin groups
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Labels: 4.x

#8061 RUN-1392 Duplicated fields at Notification settings modal
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
Labels: 4.x
