Repository rundeck/rundeck, pull requests merged in 2022-03, with the labels that each got.

#7559 revert to default katex
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
Labels: 4.x

#7560 RUN-705: nested groups are not displayed by default
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 4.x

#7565 Add install node step to maven publish
  .circleci/config.yml
Labels: 4.x

#7568 WIP: CI updates
  test/selenium/lib/compose/cluster/docker-compose.yml
  test/testdeck/src/commands/TestCommand.ts
Labels: 4.x

#7571 RUN-715: CI updates 2
  rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/AuthorizationInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
  test/api/unauthorized-test-xml.sh
  test/testdeck/src/commands/TestCommand.ts
  test/testdeck/src/util/RundeckAPI.ts
Labels: release-notes/exclude, 4.x

#7567 RUN-707: Use-Client-Side-FileReader-API-Load-Content-From-File
  rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
Labels: 4.x

#7574 RUN-698: execution mode change should allow app_admin authorization
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/RundeckAccess.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Labels: 4.x

#7580 Update gradle caching to use dynamic version
  .circleci/config.yml
Labels: release-notes/exclude, 4.x

#7569 RUN-706: Add feature flag to disable "Job File Option" uploads
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/grails-app/views/framework/_optionValuesSelectKO.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Labels: security, 4.x

#7573 Remove tests from release builds
  .circleci/config.yml
Labels: 4.x

#7576 RUN-721: dark mode link color
  rundeckapp/grails-spa/packages/ui-trellis/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_typography.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_variables.scss
Labels: 4.x

#7582 RUN-716: Fix the crontab update issue
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
Labels: 4.x

#7578 RUN-738: Rundeck 4.0 theme names and UI JS cleanup
  rundeckapp/grails-app/assets/javascripts/application.js
  rundeckapp/grails-app/assets/javascripts/version.js
  rundeckapp/grails-app/assets/javascripts/versionIdentity.js
  rundeckapp/grails-app/views/404.gsp
  rundeckapp/grails-app/views/405.gsp
  rundeckapp/grails-app/views/execution/_wfstateSummaryLine.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/ServerDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/VersionDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/version.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/utilities/RundeckVersion.ts
  rundeckapp/grails-spa/packages/ui-trellis/tests/unit/RundeckVersion.spec.ts
  rundeckapp/grails-spa/packages/ui/src/components/server-identity/main.js
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionDateDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/VersionIconNameDisplay.vue
  rundeckapp/grails-spa/packages/ui/src/components/version/main.js
  rundeckapp/grails-spa/packages/ui/src/utilities/RundeckVersion.ts
  rundeckapp/grails-spa/packages/ui/vue.config.js
Labels: to-jira, 4.x

#7584 CI fix: disable jest tests in ui-trellis
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/tsconfig.json
Labels: release-notes/exclude, 4.x

#7586 RUN-749: Correct the parameter name of minute
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
Labels: 4.x

#7591 RUN-760: Correct daysOfWeek and months selection in simple schedule
  rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/services/scheduleDefinition.ts
Labels: 4.x

#7600 RUN-767: restore crontab section hint information in editor
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/i18n.js
Labels: to-jira, 4.x

#7598 RUN-756 Redesign: align titles
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
  rundeckapp/grails-app/views/framework/adhoc.gsp
  rundeckapp/grails-app/views/framework/editProject.gsp
  rundeckapp/grails-app/views/framework/editProjectFile.gsp
  rundeckapp/grails-app/views/framework/nodes.gsp
  rundeckapp/grails-app/views/framework/projectNodeSources.gsp
  rundeckapp/grails-app/views/menu/_projectDeleteForm.gsp
  rundeckapp/grails-app/views/menu/_sysConfigExecutionModeNavMenu.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/grails-app/views/menu/executionMode.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-app/views/menu/logStorage.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
  rundeckapp/grails-app/views/menu/projectDelete.gsp
  rundeckapp/grails-app/views/menu/projectExport.gsp
  rundeckapp/grails-app/views/menu/projectHome.gsp
  rundeckapp/grails-app/views/menu/projectImport.gsp
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-app/views/passwordUtility/index.gsp
  rundeckapp/grails-app/views/reports/index.gsp
  rundeckapp/grails-app/views/scm/index.gsp
  rundeckapp/grails-app/views/user/profile.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/text.scss
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
Labels: 4.x

#7606 RUN-502 Custom Logo Fix
  rundeckapp/grails-app/views/common/_mainbar.gsp
Labels: 4.x

#7566 RUN-708: Cannot uncheck the "Keep going on success" option for error handler
  rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy
Labels: 4.x

#7587 RUN-741: fix flaky test in ExecutionController2Spec
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionController2Spec.groovy
Labels: 4.x

#7601 update core circle ci images
  .circleci/config.yml
  scripts/circle-helpers.sh
Labels: 4.x

#7593 Update Javadoc in ExecutionLogger.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLogger.java
Labels: 4.x

#7602 RUN-732: add Oauth Okta and Ping to config base
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: release-notes/exclude, 4.x

#7583 RUN-745: Upgrade grails 5.1.5
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
Labels: to-jira, 4.x

#7608 RUN-786: Fix: CPU usage showing negative value
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
Labels: 4.x

#7613 RUN-500: Improve dark-mode markdown table visibility
  rundeckapp/grails-app/assets/stylesheets/github-markdown.css
  rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue
Labels: 4.x

#7594 Fixes: ERR_PACKAGE_PATH_NOT_EXPORTED
  rundeckapp/grails-app/assets/javascripts/_package-manager/package.json
Labels: 4.x

#7592 Allow old quoting behavior
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArg.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArgList.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter_Ext.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapterSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter_ExtTest.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/execution/ExecArgListTest.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestScriptPluginFileCopier.java
  rundeckapp/src/test/groovy/rundeck/services/AuthorizingNodeExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/DirectNodeExecutionServiceSpec.groovy
Labels: needs documentation, 4.x
