Repository rundeck/rundeck, pull requests merged in 2022-01, with the labels that each got.

#7403 RDCLOUD-62 Add /user/reset to unsecured path
  rundeckapp/grails-app/conf/application.groovy
  rundeckapp/grails-app/conf/application.yml
  rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
Labels: 3.4.x

#7402 RUN-519 Allows file option uploaded for execution to be reused when retry execution feature is enabled.
  rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
  rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Labels: 3.4.x

#7448 RUN-567: Re-enable/Fix selenium node selector test
  test/selenium/package.json
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/testdeck/package.json
Labels: 3.4.x

#7465 Fixes Project Nav Remains when View All Projects link is clicked #RUN-405
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
Labels: 3.4.x

#7400 RUN-569: fix #7399 plugin date parsing fails in non-english locale
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
Labels: 3.4.x

#7466 update log4J to 2.17.1
  gradle.properties
  testbuild.groovy
Labels: 3.4.x, backport-to-3.3

#7464 update node image used for circle ci
  .circleci/config.yml
Labels: 3.4.x

#7468 update docker publishing
  docker/build.gradle
Labels: release-notes/exclude, 3.4.x

#7472 CI test updates
  test/api/include.sh
  test/api/test-job-flip-scheduleEnabled.sh
  test/api/test-job-scheduled.sh
Labels: release-notes/exclude, 3.4.x

#7476 Add command line -m option to run db migrations then stop the app
  build.gradle
  plugins/azure-object-store-plugin/build.gradle
  plugins/object-store-plugin/build.gradle
  rundeck-authz/build.gradle
  rundeck-storage/build.gradle
  rundeckapp/build.gradle
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/RundeckCliOptions.groovy
  rundeckapp/grails-app/init/rundeckapp/init/RundeckInitConfig.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Labels: 3.4.x

#7475 RUN-582: fix flaky selenium test
  test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: release-notes/exclude, 3.4.x, to-jira

#7482 RUN-579: #579 fix create project button position in first run
  rundeckapp/grails-app/views/menu/home.gsp
Labels: 3.4.x

#7489 bump snapshot version and date
  gradle.properties
  version.properties
Labels: 3.4.x

#7481 RUN-120 Added Create Project button into Project Picker
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
Labels: 3.4.x

#7479 RUN-565: Fix/issue 5780 api gui pagination
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/main/java/org/rundeck/app/components/jobs/JobQueryInput.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 3.4.x

#7493 RUN-611: Ldap name and last name cannot sync
  rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
  rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
Labels: 3.4.x

#7486 RUN-236: Make official ubuntu 20.04 image the base image of rundeck ubuntu-base
  docker/official/Dockerfile
  docker/ubuntu-base/Dockerfile
Labels: 3.4.x, 4.0.0

#7510 RUN-628: Fix dom id reference
  rundeckapp/grails-app/assets/javascripts/application.js
  rundeckapp/grails-app/assets/javascripts/executionControl.js
  rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js
  rundeckapp/grails-app/assets/javascripts/menu/home.js
  rundeckapp/grails-app/assets/javascripts/util/testing.js
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
  rundeckapp/grails-spa/packages/ui/src/pages/execution-show/main.js
Labels: 3.4.x

#7495 RCLOUD-181: Add the ability to authenticate webhooks using the Authorization header
  grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
  grails-webhooks/grails-app/domain/webhooks/Webhook.groovy
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/main/groovy/webhooks/WebhooksGrailsPlugin.groovy
  grails-webhooks/src/main/groovy/webhooks/authenticator/AuthorizationHeaderAuthenticator.groovy
  grails-webhooks/src/main/groovy/webhooks/authenticator/WebhookAuthenticator.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
  rundeckapp/grails-app/migrations/core/Webhook.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/components/help/HelpIcon.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Webhooks.ts
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/i18n.js
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
Labels: needs documentation, 3.4.x, 4.0.x

#7394 RUN-515: Convert schedules section of job edit/create to Vue
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/schedule/services/scheduleDefinition.ts
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/SchedulesEditorSection.vue
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/main.js
Labels: 3.4.x

#7503 RUN-292: Obscure Password Input on S3 Resource Model
  build.yaml
Labels: 3.4.x
