Repository rundeck/rundeck, pull requests merged in 2022-08, with the labels that each got.

#7829 RUN-1105: Upgrade grails to 5.1.9
  gradle.properties
Labels: 4.x

#7839 RUN-1116: Fix nightly build: tomcat docker test requires tag argument to script
  .circleci/config.yml
Labels: to-jira, 4.x

#7831 RUN-1089: Upgrade to Liquibase 4.8.0
  gradle.properties
  rundeckapp/grails-app/migrations/core/ScheduledExecution.groovy
Labels: 4.x

#7825 RUN-1092: Update okhttp to 4.9.2
  rundeckapp/build.gradle
Labels: 4.x

#7846 RCLOUD-561 - Add a location on login page where another login button can be inserted
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/views/user/login.gsp
Labels: 4.x

#7842 RUN-224: Fix: Enabling/Disabling both Scheduling and Executions at the same time using timer mode
  grails-execution-mode-timer/grails-app/services/com/rundeck/plugin/UpdateModeProjectService.groovy
  grails-execution-mode-timer/grails-app/utils/com/rundeck/plugin/jobs/ExecutionStatusJob.groovy
  grails-execution-mode-timer/src/test/groovy/com/rundeck/plugin/UpdateModeProjectServiceSpec.groovy
Labels: 4.x

#7827 improve query to get referenced executions
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecQuery.groovy
  rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Labels: 4.x

#7856 RSE-9-job-remote-option-url-retry-connection-parameter-not-honored
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: needs documentation, 4.x

#7861 RSE-8 Remove unnecessary GUI messages "ajax - user/login" from Rundeck
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Labels: 4.x

#7830 RUN-1061 - Fix Sub Menu Position and Adjust Spacing, Font Size
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/mainbar.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_variables.scss
Labels: 4.x

#7872 RSE-45: remote options simple json sort
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#7877 RUN-1140: Add a new rendering option t support the token script expansion in plugins
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Labels: to-jira, 4.x

#7826 RUN-1082: Add audit tracking for jobs and acls
  build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/audit/ActionTypes.java
  core/src/main/java/com/dtolabs/rundeck/core/audit/ResourceTypes.java
  core/src/main/java/com/dtolabs/rundeck/plugins/audit/AuditEventListener.java
  core/src/main/java/org/rundeck/app/acl/ListenableACLFileManager.java
  core/src/main/java/org/rundeck/app/acl/Listeners.java
  core/src/main/java/org/rundeck/app/acl/ListenersManager.java
  docker/official/remco/templates/log4j2.properties
  examples/example-java-audit-plugin/pom.xml
  plugins/audit-logging-plugin/build.gradle
  plugins/audit-logging-plugin/src/main/groovy/org/rundeck/plugin/audit/AuditLoggerPlugin.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventDispatcher.groovy
  rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
  rundeckapp/templates/config/log4j2.properties.template
  settings.gradle
  test/api/blocklist-plugin-count-test.sh
  testbuild.groovy
Labels: needs documentation, 4.x

#7883 Bump version to 4.6.0
  gradle.properties
  version.properties
Labels: 4.x

#7882 RUN-1178 The activity page doesn't work with running jobs / Auto-refresh doesn't work
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Labels: 4.x
