Repository rundeck/rundeck, pull requests merged in 2022-06, with the labels that each got.

#7743 bump snapshot version to 4.4.0
  gradle.properties
  version.properties
Labels: release-notes/exclude, 4.x

#7744 RUN-944: Add bootstrap storage tree rewrite feature
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfig.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/RundeckBootstrapStorageTreeUpdater.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreator.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/TreeCreator.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/TreeUpdater.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/Updater.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/UpdaterConfig.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfigSpec.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/TreeUpdaterSpec.groovy
Labels: 4.x

#7720 RUN-904: Upgrade gradle to 7.4.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  grails-execution-mode-timer/gradle.properties
Labels: to-jira, 4.x

#7660 RUN-836: Fix js error on nodes config page
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
Labels: 4.x

#7741 RUN-941: Fix: Can't access some menu items in main menu
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
Labels: 4.x

#7747 Re-Enable Gradle Cache
  .circleci/config.yml
Labels: 4.x

#7751 RUN-946: bump openssh plugin version to 2.0.2
  build.yaml
Labels: 4.x

#7730 RUN-890: Add runner ACL resources to ACL Editor dropdown
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthConstants.java
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthResources.java
Labels: 4.x

#7713 RUN-882 remote url options sort
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: needs documentation, 4.x

#7731 RUN-524: Fix: Output freezes when switching from Nodes tab to Log Output tab
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts
  rundeckapp/grails-spa/packages/ui/src/pages/execution-show/nodeView.ts
Labels: 4.x

#7761 Set rundeck.feature.storageRewrite.enabled default to true
  rundeckapp/grails-app/conf/spring/resources.groovy
Labels: 4.x

#7742 RUN-922: Adjust Tooltip position for activity list & Fix position of search icon
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Labels: 4.x

#7772 RUN-945 return basic rundeck server info without any authorization.
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
Labels: 4.x

#7688 RUN-928: OpenAPISpec: add docs for tokens, metrics
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/CreateToken.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/CreateTokenBase.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/CreateTokenStringRoles.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/ListTokens.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/RemoveExpiredTokens.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/Token.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/ApiErrorResponse.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/LinkListResponse.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
Labels: to-jira, 4.x

#7768 RUN-982 Node tags being showed all in uppercase without distinction b…
  rundeckapp/grails-app/assets/javascripts/knockout-node-filter-link.js
Labels: 4.x

#7782 Add unzip to tomcat docker container
  test/api/test-jobs-v13.sh
  test/docker/dockers/tomcat/Dockerfile
Labels: 4.x
