Repository rundeck/rundeck, pull requests merged in 2022-02, with the labels that each got.

#7509 RUN-624: unifying button colors and stylings
  rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
  rundeckapp/grails-app/views/framework/_storageBrowser.gsp
  rundeckapp/grails-app/views/framework/adhoc.gsp
  rundeckapp/grails-app/views/framework/editProject.gsp
  rundeckapp/grails-app/views/framework/editProjectConfig.gsp
  rundeckapp/grails-app/views/framework/editProjectNodeSourceFile.gsp
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-app/views/menu/projectAcls.gsp
  rundeckapp/grails-app/views/menu/wait.gsp
  rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editLogFilterModal.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_optlistitemContent.gsp
  rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
  rundeckapp/grails-app/views/scm/_pluginConfigList.gsp
  rundeckapp/grails-app/views/user/_user.gsp
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/grails-app/views/user/profile.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/DynamicFormPluginProp.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_buttons.scss
  rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
  rundeckapp/grails-spa/packages/ui/src/components/activity/savedFilters.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterInput.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterResults.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/OrchestratorEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui/src/pages/menu/components/userSummary.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectPluginConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginURLUploadForm.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginUploadForm.vue
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
  test/selenium/src/pages/adhocCommand.page.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/testdeck/src/pages/jobCreate.page.ts
Labels: 3.4.x

#7512 RUN-632: Fix vue console errors
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarDrawer.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/OffsetPagination.vue
Labels: 3.4.x, 4.0.x

#7532 RUN-648: Add some ENV variables to Docker Remco mapping
  docker/official/remco/templates/rundeck-config.properties
Labels: 4.x

#7534 RUN-664: update asset plugin to the last version
  gradle.properties
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/layouts/base.gsp
Labels: to-jira, 4.x

#7530 RUN-438: Fix SSO configs. Upgrade grails spring security plugin and libs.
  core/build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/views/user/login.gsp
Labels: 4.x

#7411 RUN-626: Allow several tokens per user for API authentication
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/src/test/groovy/rundeckapp/BootStrapTest.groovy
Labels: 3.4.x, to-jira, 4.x

#7521 RUN-604: Update version to 4.0.0-SNAPSHOT
  core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginMetadataValidator.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/PluginMetadataValidatorTest.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy
  gradle.properties
  version.properties
Labels: 4.x

#7523 RUN-642: API Updates for 4.x
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  test/api/include.sh
Labels: 4.x

#7524 RUN-644 UI Alignment Spacing/Layouts
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/menu/projectHome.gsp
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_grid.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_layouts.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_sidebar-and-main-panel.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
  rundeckapp/grails-spa/packages/ui/src/pages/repository/App.vue
  rundeckapp/grails-spa/packages/ui/src/pages/repository/components/Repository.vue
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
Labels: 4.x

#7513 RUN-631: Remove execution 'follow' action which duplicates 'show'
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: release-notes/exclude, 3.4.x, 4.x

#7550 RUN-693: Fix typo successul to successful in NotificationPlugin.java javadocs
  core/src/main/java/com/dtolabs/rundeck/plugins/notification/NotificationPlugin.java
Labels: to-jira, 4.x

#7552 Fix typos
  core/src/main/java/com/dtolabs/rundeck/plugins/notification/NotificationPlugin.java
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
Labels: release-notes/exclude, 4.x

#7498 RUN-586: Expand and optimize Job Edit Details tests
  test/selenium/src/__tests__/selenium/edit-job.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: 3.4.x, 4.x

#7355 OpenAPI documentation generator - RUN-668
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
Labels: 3.4.x, 4.x

#7529 [MERGE AFTER #7515] RUN-638: Update Schedule Tab Tests
  test/selenium/lib/projects/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-b7b68386-3a52-46dc-a28b-1a4bf6ed87de.xml
  test/selenium/src/__tests__/selenium/edit-job.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: 4.x

#7554 RUN-603: Enhance UserController to support more flexible error message
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: 4.x

#7538 [MERGE AFTER #7529] RUN-670: Add tests for Job Edit Other tab
  test/selenium/src/__tests__/selenium/edit-job.test.ts
  test/selenium/src/pages/jobCreate.page.ts
Labels: release-notes/exclude, 4.x

#7533 RUN-654 Rundeck Enterprise to PagerDuty Process Automation
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/grails-app/views/404.gsp
  rundeckapp/grails-app/views/405.gsp
  rundeckapp/grails-app/views/common/_mainbar.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/menu/home.gsp
  rundeckapp/grails-app/views/menu/welcome.gsp
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
  rundeckapp/grails-spa/packages/ui-trellis/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/svg/PagerdutyLogo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/RundeckVersionDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/RundeckInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/RundeckInfoWidget.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/interfaces/rundeckWindow.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts
  rundeckapp/grails-spa/packages/ui-trellis/theme/images/logos/pagerduty-full-logo.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/images/logos/pagerdutylogo.svg
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.scss
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/pagerduty-icon.scss
  rundeckapp/grails-spa/packages/ui/src/components/central/main.ts
  rundeckapp/grails-spa/packages/ui/src/components/navbar/main.ts
  rundeckapp/grails-spa/packages/ui/src/components/theme/main.ts
  rundeckapp/src/main/resources/public/images/pdfavicon.ico
Labels: 4.x

#7502 RUN-590: Remove unused gradlew scripts
  plugins/azure-object-store-plugin/gradle/wrapper/gradle-wrapper.jar
  plugins/azure-object-store-plugin/gradle/wrapper/gradle-wrapper.properties
  plugins/object-store-plugin/gradle/wrapper/gradle-wrapper.jar
  plugins/object-store-plugin/gradle/wrapper/gradle-wrapper.properties
  plugins/script-plugin/gradlew
  plugins/script-plugin/gradlew.bat
  plugins/stub-plugin/gradlew
  plugins/stub-plugin/gradlew.bat
  rundeckapp/gradle/wrapper/gradle-wrapper.jar
  rundeckapp/gradle/wrapper/gradle-wrapper.properties
  rundeckapp/gradlew
  rundeckapp/gradlew.bat
Labels: release-notes/exclude, 3.4.x, 4.x

#7553 RUN-695: fix issue with API access before server fully starts
  rundeckapp/grails-app/controllers/rundeck/interceptors/ApiAccessInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/ApiVersionInterceptor.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/ApiAccessInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/ApiVersionInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/AuthorizationInterceptorSpec.groovy
Labels: release-notes/exclude, 4.x

#7556 Revert "RUN-668: OpenAPI documentation generator"
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
Labels: release-notes/exclude, 4.x
