Repository rundeck/rundeck, pull requests merged in 2022-09, with the labels that each got.

#7878 RSE-54 Customizing UI with client logo resize login form, push login button to bottom without scroll
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/login.scss
Labels: 4.x

#7887 RSE-60 Failed to Import project, error 500 whitelabel on screen
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
Labels: 4.x

#7880 RSE-56 rundeck.gui.helpLink property replace the doc link instead of support link
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/HelplinkController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/HelplinkControllerSpec.groovy
Labels: 4.x

#7894 RUN-1206: Update snakeyaml to 1.31 to address CVE-2022-25857
  build.gradle
  gradle.properties
Labels: 4.x

#7876 RUN-986: Fix flaky test for avg duration notification
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
Labels: 4.x

#7890 RUN-1022: project menu dropdown create project doesnt work with an app context path
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts
  rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
Labels: 4.x

#7873 fix: RSE-34 validation added to prevent invalid captured pattern
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyValidator.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
Labels: 4.x

#7866 RUN-621: Add changes needed for ROI Plugin
  rundeckapp/grails-app/views/scheduledExecution/create.gsp
  rundeckapp/grails-app/views/scheduledExecution/edit.gsp
Labels: 4.x

#7837 Auth Token data-spi
  core/build.gradle
  core/src/main/java/com/dtolabs/rundeck/core/authentication/Token.java
  core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenManager.java
  core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenType.java
  core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthenticationToken.java
  grails-webhooks/build.gradle
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
  rundeck-data-model/build.gradle
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/AuthTokenMode.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/AuthenticationToken.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/SimpleTokenBuilder.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/TokenDataProvider.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/package-info.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/utils/Utils.java
  rundeck-data-spi/build.gradle
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/BaseDataManager.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/DataAccessException.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/DataManager.java
  rundeck-data-spi/src/main/java/org/rundeck/spi/data/package-info.java
  rundeckapp/build.gradle
  rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/grails-app/domain/rundeck/AuthToken.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/RundeckAuthTokenManagerService.groovy
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/grails-app/services/rundeck/services/data/AuthTokenDataService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/Token.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/ProviderRegistration.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormTokenDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/providers/GormTokenDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/AuthTokenSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
  settings.gradle
Labels: 4.x

#7901 change lombok from annotationProcessor to implementation to resolve i…
  rundeckapp/build.gradle
Labels: 4.x

#7899 RSE-117 [QA 4.6.1] Minor GUI Bug on WH Dropdown
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
Labels: 4.x

#7914 fix packaging submodule branch
  .gitmodules
Labels: release-notes/exclude, 4.x

#7910 fix bugs with AuthToken refactor
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: 4.x

#7911 RUN-1208: Improvements on job file option input sanitation
  rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/src/test/groovy/rundeck/UtilityTagLibSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Labels: 4.x

#7892 RUN-1205: fix: dev-mode: failing ui pseudo-test
  rundeckapp/grails-app/assets/javascripts/menu/joboptionsTest.js
Labels: to-jira, 4.x

#7909 RCLOUD-601: Adding job start failure metric.
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Labels: 4.x

#7891 RUN-933: Add note about new example plugins repo
  examples/README.md
Labels: 4.x

#7932 RUN-1263: fix webhook listing and project export
  core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenManager.java
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/RundeckAuthTokenManagerService.groovy
  rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#7935 RSE-140 MOTD (Message of the day) not displayed (Rundeck OSS)
  rundeckapp/grails-app/views/menu/home.gsp
Labels: 4.x
