Repository rundeck/rundeck, pull requests merged in 2022-05, with the labels that each got.

#7632 RUN-807: Fixes org.postgresql:postgresql vulns
  rundeckapp/build.gradle
Labels: 4.x

#7686 RUN-864 - Update input group addon class
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
Labels: 4.x

#7689 RUN-868 - Update Calendar Darkmode Classes and Buttons
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_popovers.scss
  rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectPluginConfig.vue
Labels: 4.x

#7685 RUN-866: RUN-829: Fix: Cluster manager hostname disappears
  rundeckapp/grails-spa/packages/ui/src/components/server-identity/main.js
Labels: 4.x

#7693 RUN-796: internal project config change event includes changed keys info
  core/src/main/java/org/rundeck/app/grails/events/AppEvents.java
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#7695 RUN-833: avoid logging warnings by removing dot notation config value access
  grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XFOSecurityHeaderProvider.groovy
  grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XXSSPSecurityHeaderProvider.groovy
Labels: 4.x

#7656 RUN-834: Fix: testcase was added to wrong class
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#7672 RUN-861: Support for OpenAPI documentation Generation (rerecreated)
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
Labels: to-jira, 4.x

#7701 RUN-877: remove asset-pipeline config from plugin
  grails-execution-mode-timer/build.gradle
Labels: release-notes/exclude, 4.x

#7696 RUN-874: Fix: XXSSP header is deprecated
  grails-securityheaders/src/main/groovy/grails/securityheaders/SecurityheadersGrailsPlugin.groovy
  grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XXSSPSecurityHeaderProvider.groovy
Labels: 4.x

#7649 Fix: 404 page when clicking on referenced execution from a different parent
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
Labels: 4.x

#7674 RUN-842: Remove options when importing Job Definitions
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#7704 RUN-873:Fix: bug ansible plugins dont show properly
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/autocomplete.scss
Labels: 4.x

#7692 RUN-822 - Remove Unused Css file
  rundeckapp/grails-app/views/404.gsp
  rundeckapp/grails-app/views/405.gsp
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-app/views/user/loggedout.gsp
  rundeckapp/grails-app/views/user/login.gsp
Labels: 4.x

#7711 RUN-660: Update version plugin to the new release version 1.1.0
  build.yaml
Labels: 4.x

#7703 RUN-887: Fix local file copier config error
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopier.java
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
  test/api/blocklist-plugin-count-test.sh
Labels: to-jira, 4.x

#7712 bump snapshot version to 4.3.0
  gradle.properties
  version.properties
Labels: 4.x

#7694 RUN-894: Messages for WebHooks import errors and new messages for webhook toke…
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  grails-webhooks/src/main/groovy/webhooks/importer/WebhooksProjectImporter.groovy
Labels: 4.x

#7691 RUN-758: add configuration to disable "Public Key" GUI download option
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/assets/javascripts/menu/storage.js
  rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/views/framework/_storageBrowser.gsp
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
Labels: to-jira, 4.x

#7721 RUN-903 | Storybook Knobs Deprecated
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.js
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/copybox/containers.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/drawer/drawer.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/tabs/tabs.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/data/list.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/filter-list/filterList.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/firstrun.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/inputs.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/text.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/base.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/sidebar.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/wizards.stories.tsx
  rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/navbar.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/skeleton.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/utilitybar.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/version.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/news.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/projectSelect.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/webhook-select/webhookSelect.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/stories/theme.stories.tsx
  rundeckapp/grails-spa/packages/ui/package-lock.json
Labels: 4.x

#7718 RUN-902: Fix:Webhook minimum actions error message showing incorrectly
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
Labels: 4.x

#7705 Updates to readme
  README.md
Labels: release-notes/exclude, 4.x

#7684 RUN-862: Cleanup: remove bintray references and vagrant
  rundeck-authz/bintray.gradle
  rundeckapp/build.gradle
  scripts/circle-helpers.sh
  scripts/delete-bintray-package.sh
  scripts/deploy-deb-snapshots.sh
  scripts/deploy-maven-snapshots.sh
  scripts/deploy-rpm-snapshots.sh
  scripts/publish-deb-to-bintray.sh
  scripts/publish-jar-to-bintray.sh
  scripts/publish-rpm-to-bintray.sh
  test/docker/README.md
  test/docker/common.sh
  test/docker/docker-compose-ansible-test.yaml
  test/docker/docker-compose-api-mysql.yaml
  test/docker/docker-compose-api-test.yml
  test/docker/docker-compose-ldap-binding-test.yaml
  test/docker/docker-compose-ldap-sync-test.yaml
  test/docker/docker-compose-ldap-test.yaml
  test/docker/docker-compose-multinode-test.yml
  test/docker/docker-compose-pam-test.yaml
  test/docker/docker-compose-plugin-blocklist.yaml
  test/docker/docker-compose-ssl-test.yml
  test/docker/docker-compose-tomcat-test.yml
  test/docker/dockers/rundeck/Dockerfile
  test/docker/test-api-tomcat.sh
  test/vagrant/centos-yum-vbox-ci/README.md
  test/vagrant/centos-yum-vbox-ci/Vagrantfile
  test/vagrant/centos-yum-vbox-ci/add-project.sh
  test/vagrant/centos-yum-vbox-ci/bootstrap.sh
  test/vagrant/centos-yum-vbox-ci/prepare-tests.sh
  test/vagrant/centos-yum-vbox-ci/teardown.sh
  test/vagrant/run-vagrant-test.sh
  test/vagrant/src/api-test.sh
  test/vagrant/yum-aws-ci/README.md
  test/vagrant/yum-aws-ci/Vagrantfile
  test/vagrant/yum-aws-ci/bootstrap.sh
  test/vagrant/yum-aws-ci/prepare-tests.sh
  test/vagrant/yum-aws-ci/run-vagrant-test.sh
  test/vagrant/yum-aws-ci/teardown.sh
  test/vagrant/yum-aws-multinode/Vagrantfile
  test/vagrant/yum-aws-multinode/pre-run-vagrant-test.sh
  test/vagrant/yum-aws-multinode/provisioning/general/add-sshuser.sh
  test/vagrant/yum-aws-multinode/provisioning/general/create-user.sh
  test/vagrant/yum-aws-multinode/provisioning/rundeck/add-nodes.sh
  test/vagrant/yum-aws-multinode/provisioning/rundeck/copy-sshkey.sh
  test/vagrant/yum-aws-multinode/provisioning/rundeck/create-project.sh
  test/vagrant/yum-aws-multinode/provisioning/rundeck/install.sh
  test/vagrant/yum-aws-multinode/provisioning/rundeck/upload-sshkey-storage.sh
  test/vagrant/yum-aws-multinode/run-vagrant-test.sh
  test/vagrant/yum-aws-multinode/tests/roundup
  test/vagrant/yum-aws-multinode/tests/rundeck/project-should-exist-test.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/should-dispatch-remote-adhoc-storagekey-test.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/should-dispatch-remote-adhoc-test.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/should-dispatch-script-remotely-storagekey-test.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/should-dispatch-script-remotely-test.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/test-all.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/test-dispatch-script-dos.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/test-dispatch-script-utf8.sh
  test/vagrant/yum-aws-multinode/tests/rundeck/test-dispatch-script.sh
Labels: release-notes/exclude, to-jira, 4.x

#7687 RUN-709: Only show Local Filesystem ACL summary if OpsAdmin or higher
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 4.x

#7716 RUN-886: GUI bug pagerduty webhook actions toggle switch
  rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_tooltip-and-popovers.scss
Labels: 4.x

#7511 RUN-617: Fix/2207 import job with many same type notif
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
  rundeckapp/src/integration-test/groovy/rundeck/codecs/JobsYAMLCodecIntegrationSpec.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobXMLFormatSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
  rundeckapp/src/test/groovy/rundeck/JobsXMLCodecTests.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/codecs/JobsYAMLCodecSpec.groovy
Labels: needs documentation, 3.4.x, 4.x

#7732 RUN-913: When recreating storage tree, include converter plugin props
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTree.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreator.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTreeSpec.groovy
Labels: 4.x

#7729 RUN-925: Fix stored acls not require app admin auth
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthResources.java
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/RundeckAccess.java
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
  rundeckapp/grails-app/views/menu/acls.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 4.x
