Repository rundeck/rundeck, pull requests merged in 2023-11, with the labels that each got.

#8616 RUN-1989: update Node to 18.18.1
  .circleci/config.yml
  .nvmrc
  gradle.properties
  rundeckapp/grails-spa/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  test/.nvmrc
  test/selenium/Dockerfile
  test/testdeck/.nvmrc
Labels: release-notes/exclude

#8658 Change how the disableContentConversion parameter is cast to boolean
  core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactory.java
  core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactorySpec.groovy
Labels: auto-backport, backport-to-release/4.17.x

#8672 RCLOUD-1046: Add svc prefix for API endpoints that require alternate security mechanisms
  rundeckapp/grails-app/conf/application.groovy
Labels: release-notes/exclude

#8676 Small tweaks to execution and notification services for RCLOUD-1046
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/notification/SendNotificationEvent.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
Labels: release-notes/exclude

#8696 RSE-896: Add specific message when facing a liquibase LockException
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
Labels: needs documentation
