Repository rundeck/rundeck, pull requests merged in 2023-02, with the labels that each got.

#8118 RSE-266 Fix: Cannot remove notifications from a job by loading an XML file
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#8108 RUN-1229: Implementing a component to display runner info in execution pag
  rundeckapp/grails-app/views/execution/_wfstateNodeModelDisplay.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/UIStore.ts
  rundeckapp/grails-spa/packages/ui/src/components/ui/main.ts
Labels: 4.x

#8123 Fix class name inconsistency in projectHome.gsp
  rundeckapp/grails-app/views/menu/projectHome.gsp
Labels: 4.x

#7982 RSE-49: Fix: passing groups via proxy for preauth shows dupe groups in the Rundeck Profile
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerPrincipalRoleSource.groovy
  rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerRoleSource.groovy
  rundeckapp/src/main/groovy/org/rundeck/web/infosec/PreauthenticatedAttributeRoleSource.groovy
  rundeckapp/src/test/groovy/org/rundeck/web/infosec/ContainerRoleSourceSpec.groovy
Labels: 4.x

#8005 RSE-133: Fix: Notifications payload format are not imported properly by the API and the UI
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
Labels: 4.x

#8100 RSE-253 Fix: Cannot Add Node Wizard Sources
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Labels: 4.x

#8043 RSE-245: Fix: deb install not taking wrong base dir for commands
  packaging/lib/deb/etc/init.d/rundeckd
Labels: 4.x

#8116 RUN-1447: Job with Job references does not use correct Runners in referenced jobs
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobExecutionItem.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobRefCommand.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobRefCommandBase.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobReferenceItem.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/execution/ExecutionItemFactory.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/jobreference/JobReferenceNodeStepExecutor.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/jobreference/JobReferenceStepExecutor.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/execution/ExecutionItemFactoryTest.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
Labels: to-jira, 4.x

#8124 RUN-1445: Upgrade the version of sshj-plugin to 0.1.4 which fixed the…
  build.yaml
Labels: 4.x

#8131 Run 1466: fix create project plugin group null save error
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Labels: 4.x, backport release/4.10.x

#8029 Cleanup: remove unnecessary openapi flags
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
Labels: 4.x

#8135 Add null check before writing plugin group props to project settings
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Labels: 4.x

#8132 RUN-1464: Fix settings change handling on execution log UI
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logEntryFlex.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Labels: 4.x, backport release/4.10.0

#8137 RUN-1474: Update chromedriver to 109
  test/selenium/package.json
  test/testdeck/package.json
Labels: to-jira, 4.x

#8140 RUN-1471 change update from storage data service to gorm data object save to f…
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/storage/GormStorageDataProvider.groovy
Labels: 4.x, backport release/4.10.x

#8141 RUN-1477: Fix error handling on job component failure
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
Labels: 4.x

#8147 Bump SNAPSHOT version to 4.11.0
  gradle.properties
  version.properties
Labels: 4.x

#8040 RUN-1374: job json format
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Common.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Import.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/views/scheduledExecution/_jobActionButtonMenuContent.gsp
  rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/upload.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobJSONFormat.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/RundeckJobDefinitionManager.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  test/api/include.sh
  test/api/test-job-export-json.sh
  test/api/test-job-export-unsupported-json-v43.sh
  test/api/test-job-export-unsupported.sh
  test/api/test-job-export-xml.sh
  test/api/test-job-export-yaml.sh
  test/api/test-job-export.sh
  test/api/test-job-flip-scheduleEnabled-bulk.sh
  test/api/test-job-flip-scheduleEnabled-scheduler-bug.sh
  test/api/test-jobs-export-json.sh
  test/api/test-jobs-export-xml.sh
  test/api/test-jobs-import-invalid.sh
  test/api/test-jobs-import-json.sh
  test/api/testall.sh
  test/docker/test-api.sh
Labels: needs documentation, 4.x

#7997 RSE-186: syncOauthUser properties don't have hot reload
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
Labels: 4.x

#8151 RUN-1434: fix exec page UI plugins: send event to indicate page loaded has completed
  rundeckapp/grails-app/views/execution/show.gsp
Labels: 4.x, backport release/4.10.x

#8153 RUN-1496: fix job edit job notifications selenium test
  test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts
  test/selenium/src/pages/jobShow.page.ts
Labels: to-jira, 4.x

#8150 RUN-1436: Change FeatureService to use an interface instead of the Features enum
  core/src/main/java/com/dtolabs/rundeck/core/config/FeatureService.java
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/FeaturesDefinition.java
  rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy
Labels: to-jira, 4.x

#8152 RUN-1472: No Message On GUI For Scheduled Job On Unhealthy Runner
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobEvent.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobExecutionEvent.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobLifecycleStatus.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobPersistEvent.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobPreExecutionEvent.java
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
Labels: 4.x

#8161 RUN-1502: upgrade commons-fileupload
  rundeckapp/build.gradle
Labels: to-jira, 4.x

#8136 RUN-1473: Update error message for runner not found
  rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
Labels: 4.x

#8144 RSE-255 : Allow Roles pagination when using Active Directory
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCombinedLdapLoginModule.java
  rundeckapp/src/test/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest2.java
Labels: needs documentation, 4.x

#8165 RUN-1509: Fix: ExecutionLifecycle component is not loaded when a job is imported
  rundeckapp/src/main/groovy/rundeck/services/ExecutionLifecycleComponentService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclComponentServiceSpec.groovy
Labels: to-jira, 4.x

#8157 RUN-1479: Establish new section in execution head page for feature use.
  rundeckapp/grails-app/views/execution/show.gsp
Labels: 4.x

#8168 RSE-255: AD paged results default
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
Labels: 4.x

#8166 RUN-1518: Update two pckage-lock json file
  rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
Labels: release-notes/exclude, 4.x
