Repository rundeck/rundeck, pull requests merged in 2023-09, with the labels that each got.

#8526 RUN-1923: fix: short description not shown for node/workflow steps in workflow step create picker
  rundeckapp/grails-app/views/execution/_wfAddStep.gsp
Labels: to-jira

#8533 RUN-1922: include all validation data in validateJobDefinition map
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: release-notes/exclude

#8545 RUN-1947 key storage view does not show error when saving fails
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageEdit.vue
Labels: auto-backport, backport-to-release/4.17.x

#8548 Update circle-ci to install node before openAPI validation
  .circleci/config.yml
Labels: release-notes/exclude, to-jira

#8543 RUN-1942 table
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_tables.scss
Labels: auto-backport, backport-to-release/4.17.x

#8551 RUN-1940: info widget should appear before loading finishes
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/rundeck-info/RundeckInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/rundeck-info/RundeckInfoWidget.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Releases.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/System.ts
Labels: release-notes/exclude, auto-backport, backport-to-release/4.17.x

#8546 RUN-1959: replace div for a span to make it inline
  rundeckapp/grails-app/views/user/profile.gsp
Labels: release-notes/exclude, auto-backport, backport-to-release/4.17.x

#8554 RUN-1962 Fix logViewer regression
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Labels: auto-backport, backport-to-release/4.17.x

#8529 RUN-1924: Server identity UI updates
  rundeckapp/grails-app/views/common/_footer.gsp
  rundeckapp/grails-app/views/common/_mainbar.gsp
  rundeckapp/grails-app/views/execution/_wfstateSummaryLine.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/navbar/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/server-identity/serverIdentity.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/server-identity/serverIdentity.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/i18n.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/UiSocket.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/version/ServerDisplay.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/rundeck-info/RundeckInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
Labels: release-notes/exclude

#8561 RUN-1975: fix: execution mode is not retained after config refresh
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy
Labels: auto-backport, backport-to-release/4.17.x

#8559 RUN-1973 Fix webhook update to keep auth config
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
Labels: auto-backport, backport-to-release/4.17.x
