Repository rundeck/rundeck, pull requests merged in 2023-08, with the labels that each got.

#8454 RUN-1859: Dark mode updates
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditorVue.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/custom/process-flow.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_code.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_input-groups.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_variables.scss
Labels: to-jira

#8460 update chromedriver
  .circleci/config.yml
  test/selenium/.npmrc
  test/testdeck/.npmrc
Labels: release-notes/exclude, to-jira

#8436 RSE-406::Flag to enable/disable search for more than 1000 users
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
  rundeckapp/src/test/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest2.java
Labels: needs documentation

#8408 RUN-1821: fix: docker tag used for twistlock check
  scripts/circle-helpers.sh
Labels: release-notes/exclude, to-jira

#8326 RUN-1743: Cleanup: remove unused events fragment
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/views/common/_js.gsp
  rundeckapp/grails-app/views/reports/_baseReport.gsp
  rundeckapp/grails-app/views/reports/_eventsFragment.gsp
  rundeckapp/grails-app/views/reports/eventsFragment.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/library/interfaces/AppLinks.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stories/setup.ts
Labels: to-jira

#8471 RUN-1873: remove unstylish border from notifications
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_media.scss
Labels: to-jira

#8450 RSE-712 Fix: Map Different Required Authorizing Roles
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: needs documentation

#8473 Chrome installation with orb (circleci)
  .circleci/config.yml
Labels: release-notes/exclude

#8485 RSE-724: Keep "allGroups" in true by default.
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
Labels: needs documentation

#8456 RUN-1853: UI main layout updates
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_view.scss
Labels: release-notes/exclude, to-jira

#8493 Bump SNAPSHOT version to 4.17.0
  gradle.properties
  version.properties
Labels: release-notes/exclude

#8502 RUN-1897: enable execution of script file resource model in a remote runner
  core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceModelSource.java
  core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptResourceModelSourceSpec.groovy
Labels: auto-backport, backport-to-release/4.16.x

#8433 Rcloud-665: execution to spi
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/constants/ExecutionConstants.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/RdExecution.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/RdExecutionDataSummary.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdWorkflowStep.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/paging/RdPageable.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/ExecutionDataUtil.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/shared/SharedExecutionConstraints.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/shared/SharedServerNodeUuidConstraints.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/ExecutionDataUtilSpec.groovy
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/ExecutionData.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/ExecutionDataSummary.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/job/workflow/WorkflowStepData.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/execution/ExecutionDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/RdExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/RdJobController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
  rundeckapp/grails-app/migrations/core/Execution.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/RdExecutionService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/domain/execution/AppAuthorizingExecution.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ExecutionFromRdExecutionUpdater.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/OrchestratorToRdOrchestratorConverter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/OrchestratorUpdater.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionFromRdJobUpdater.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionToJobConverter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/WorkflowToRdWorkflowConverter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/WorkflowUpdater.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecutionDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ExecutionFromRdExecutionUpdaterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/OrchestratorToRdOrchestratorConverterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/WorkflowToRdWorkflowConverterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/WorkflowUpdaterSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecutionDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/RdExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/testhelper/TestDomainFactory.groovy
Labels: 4.x

#8505 RUN-1902: Add execution context for log filter plugins
  core/src/main/java/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriter.java
  core/src/main/java/com/dtolabs/rundeck/core/logging/PluginLoggingContext.java
  core/src/test/groovy/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriterSpec.groovy
Labels: release-notes/exclude, to-jira

#8518 Fix flaky test
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: release-notes/exclude
