Repository rundeck/rundeck, pull requests merged in 2023-03, with the labels that each got.

#8167 RUN-1492: Fix: Webhooks not showing proper information After Create
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue
Labels: 4.x

#8172 RUN-1485: upgrade sshj-plugin to 0.1.6
  build.yaml
Labels: to-jira, 4.x

#8173 Bump SNAPSHOT version to 4.12.0
  gradle.properties
  version.properties
Labels: release-notes/exclude, 4.x

#8178 RUN-1542: Fix: scm import/export options for job JSON
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobJSONFormat.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobJSONFormatSpec.groovy
Labels: release-notes/exclude, 4.x, backport release/4.11.x

#8182 RUN-1542: backport to 4.11.x
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobJSONFormat.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/JobJSONFormatSpec.groovy
Labels: release-notes/exclude

#8184 Update chromedriver to 110
  test/selenium/package.json
  test/testdeck/package.json
Labels: release-notes/exclude, 4.x, backport release/4.11.x

#8185 Backport: Update chromedriver 110
  test/selenium/package.json
  test/testdeck/package.json
Labels: release-notes/exclude

#8189 RUN-1552: backport to 4.11.x
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
Labels: release-notes/exclude

#8188 RUN-1552: fix: webhook import should fail for existing token (4.11.0-rc1)
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
Labels: release-notes/exclude, 4.x, backport-completed, backport release/4.11.x

#8156 RSE-297: Notifications fixes for Average Duration, OnRestart, etc.
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyEmailNotificationPlugin.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: 4.x

#8192 Migration only startup exit code fix
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Labels: release-notes/exclude, 4.x

#8181 RUN-1139: Add link to execution mode toggle page on passive mode display
  rundeckapp/grails-app/views/common/_mainbar.gsp
Labels: 4.x

#8208 Fix plugin registry loading behavior
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
  rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Labels: 4.x

#8138 RUN-1356: remove in-page js tests in dev mode
  rundeckapp/grails-app/views/execution/_wfAddStep.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/framework/nodes.gsp
  rundeckapp/grails-app/views/menu/jobs.gsp
Labels: 4.x

#8174 RUN-1554: Convert twistlock output to junit for circleci
  .circleci/config.yml
  scripts/circle-helpers.sh
  scripts/convert_tl_junit.sh
Labels: release-notes/exclude, to-jira, 4.x

#8193 RUN-199: Improve Authentication Options for Remote URL Option Input
  core/src/main/java/com/dtolabs/rundeck/core/jobs/JobOption.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/options/JobOptionConfigData.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/options/JobOptionConfigEntry.java
  core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobOptionImpl.java
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdOption.groovy
  rundeckapp/grails-app/assets/javascripts/optionEditKO.js
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Option.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobDataProvider.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/ApiTokenReporter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigPluginAttributes.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/RemoteUrlAuthenticationType.groovy
  rundeckapp/src/main/groovy/org/rundeck/util/HttpClientCreator.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/OptionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: to-jira, 4.x

#8214 RUN-1614: Update jquery to 3.6.4
  rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json
  rundeckapp/grails-app/assets/javascripts/_package-manager/package.json
Labels: 4.x

#8220 RSE-321: Fix: ERROR while running a dir command in a path with Japanese files (Upgrade plugin version)
  build.yaml
Labels: 4.x
