Repository rundeck/rundeck, pull requests merged in 2023-01, with the labels that each got.

#8063 RUN-1389: fix error choosing runner on execution runtime
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Labels: to-jira, 4.x

#8064 RCLOUD-728: Fix Project Picker not loading when Projects with special characters exist
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/domain/rundeck/Project.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Labels: 4.x

#8056 RUN-1388: upgrade sshj version
  build.yaml
Labels: to-jira, 4.x

#8071 RUN-1414: Package Upgrades for CVE-2022-41881
  gradle.properties
Labels: 4.x

#8073 RUN-1418: Job activity tab not loading
  rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Labels: 4.x

#8074 RUN-1385: Plugin group null definitions
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Labels: 4.x

#8070 Fixes RSE-229: Fix the Http Header Injection Vulnerability
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 4.x

#8079 RUN-1424: Update testdeck to use node 16
  .circleci/Dockerfile
  .circleci/config.yml
  .gitignore
  scripts/circle-helpers.sh
  test/.nvmrc
  test/package.json
  test/selenium-docker-compose.yml
  test/selenium/.nvmrc
  test/selenium/Dockerfile
  test/selenium/lib/compose/cluster/docker-compose.yml
  test/selenium/lib/compose/cluster/test-tokens.properties
  test/selenium/lib/compose/single/docker-compose.yml
  test/selenium/package.json
  test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts
  test/selenium/src/pages/jobCreate.page.ts
  test/testdeck/.nvmrc
  test/testdeck/package.json
  test/testdeck/src/ClusterManager.ts
  test/testdeck/src/DockerCompose.ts
  test/testdeck/src/commands/TestCommand.ts
  test/testdeck/src/util/RundeckAPI.ts
  test/testdeck/src/util/apiShim.ts
  test/testdeck/tsconfig.json
Labels: 4.x

#8047 RSE-244 Fix: edit/view jobs when SCM Import Plugin is forbidden for user
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/views/menu/jobs.gsp
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: 4.x

#8033 RUN-1298: generate copyright year at build time
  rundeckapp/grails-spa/packages/ui-trellis/src/components/version/Copyright.vue
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.js
Labels: 4.x

#8078 RCLOUD-344: Fix test
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Labels: 4.x

#8062 RUN-1397: modular annotation authZ
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/BaseAppRequestMethodAuthorizer.java
  rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/RequestMethodAuthorizer.java
  rundeck-authz/rundeck-authz-core/src/main/resources/META-INF/services/org.rundeck.core.auth.app.RequestMethodAuthorizer
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/RdAuthorizeInterceptor.groovy
Labels: release-notes/exclude, 4.x

#8106 Bump SNAPSHOT version to 4.10.0
  gradle.properties
  version.properties
Labels: 4.x

#8076 RSE-257 Fix: Cannot edit rulesets if the page is too heavy
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowGraphController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/WorkflowGraphControllerSpec.groovy
Labels: needs documentation, 4.x

#8072 RUN-1417: Fix use of promise
  rundeckapp/grails-app/views/common/_queryFilterManagerModal.gsp
Labels: 4.x

#8034 RUN-1367: Fix: groovy plugins with suffix matching the service should load correctly
  rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/PluginCustomizer.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Labels: 4.x

#8080 RUN-1423: Update add plugin button label
  rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Labels: 4.x

#8092 RUN-1230 - Add UiSocket support for execution log
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logEntryFlex.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/UiSocket.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts
  rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui/src/components/ui/main.ts
  rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
  test/api/include.sh
Labels: 4.x

#8083 RUN-1410: Add a new ExecutionLifecicleComponent
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLifecycleComponentException.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLifecyclePluginException.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceThread.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/FileCopierService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/ExecutionLifecycleComponent.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/ExecutionLifecycleComponentHandler.java
  core/src/main/java/com/dtolabs/rundeck/core/jobs/IExecutionLifecycleComponentService.java
  core/src/main/java/com/dtolabs/rundeck/plugins/jobs/ExecutionLifecyclePlugin.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/TestWEServiceThread.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceJobIntegrationSpec.groovy
  rundeckapp/src/main/groovy/rundeck/services/ExecutionLifecycleComponentService.groovy
  rundeckapp/src/main/groovy/rundeck/services/ExecutionReferenceLifecycleComponentHandler.groovy
  rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclComponentServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobLifecycleComponentServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: to-jira, 4.x

#8117 RUN-1426: update ansible plugin to version 3.2.3
  build.yaml
Labels: to-jira, 4.x

#8094 RUN-1370: Change jaas-loginmodule remco template to be able to use ReloadablePropertyFileLoginModule
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: to-jira, 4.x

#8035 RCLOUD-666: Convert access of Storage entity to be pass through a data provider
  rundeck-data-model/build.gradle
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/storage/RundeckStorage.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/storage/SimpleStorageBuilder.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/storage/StorageDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/domain/rundeck/Storage.groovy
  rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
  rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/data/StorageDataService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/storage/GormStorageDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/providers/GormStorageDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/StorageTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/DbStorageServiceTests.groovy
Labels: 4.x

#8115 Fix to user profile flash spacing
  rundeckapp/grails-app/views/user/profile.gsp
Labels: 4.x

#8091 RSE-280 Fix: Cannot Edit Job Schedules
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#8112 RSE-290: Fix: cannot update jobs after upgrade 3.3 to 4.8 job (error 500)
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
Labels: 4.x
