Repository rundeck/rundeck, pull requests merged in 2023-12, with the labels that each got.

#8713 Delete old CI scripts
  scripts/old/circle-build.sh
  scripts/old/circle-helpers.sh
  scripts/old/circle-shim.sh
  scripts/old/circleci-old-config.yml
  scripts/old/helpers.sh
  scripts/old/replace-filename-token.sh
Labels: release-notes/exclude

#8726 RUN-2083 Fix icon for command and script plugins
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/CommandNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptFileNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/resources/resources/WorkflowNodeStep.exec-command.icon.png
  plugins/script-node-step-plugin/src/main/resources/resources/WorkflowNodeStep.script-command.icon.png
  plugins/script-node-step-plugin/src/main/resources/resources/WorkflowNodeStep.script-file-command.icon.png
  plugins/script-node-step-plugin/src/main/resources/resources/icon.png
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: auto-backport, backport-to-release/5.0.x

#8727 Update sonatype command to automagically close and release stagin repo
  scripts/circleci/packaging-functions.sh
Labels: auto-backport, backport-to-release/5.0.x

#8736 RUN-2091: Fix cancel action in user edit page
  rundeckapp/grails-app/views/user/edit.gsp
Labels: auto-backport, backport-to-release/5.0.x

#8731 RUN-2084: job import with JSON format with unsupported version should return expected error
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/jobs/JobImportSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: auto-backport, backport-to-release/5.0.x

#8740 Backport sonatype update
  scripts/circleci/packaging-functions.sh
Labels: release-notes/exclude

#8749 Remove breaking comment
  scripts/circleci/packaging-functions.sh
Labels: auto-backport, backport-to-release/5.0.x

#8751 RSE-919: Fix whale logs crashing browser
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/ExecutionOutput.ts
Labels: auto-backport, backport-to-release/4.17.x, backport-to-release/5.0.x

#8498 RUN-2107: Use a fixed version of go for remco in Docker Image
  docker/ubuntu-base/Dockerfile
Labels: auto-backport, backport-to-release/5.0.x

#8758 RUN-2109: Fix node step plugin filter
  core/src/main/java/org/rundeck/core/execution/ScriptCommand.java
  core/src/main/java/org/rundeck/core/execution/ScriptFileCommand.java
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/JobCreatePage.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptFileNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/resources/resources/WorkflowNodeStep.script-file-url.icon.png
  plugins/script-node-step-plugin/src/main/resources/resources/WorkflowNodeStep.script-inline.icon.png
  rundeckapp/grails-app/views/execution/_wfAddStep.gsp
Labels: auto-backport, backport-to-release/5.0.x

#8760 RUN-2114: Fix replacing data references in script as it uses different tokens to define them
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptNodeStepPlugin.groovy
Labels: auto-backport, backport-to-release/5.0.x

#8762 add version 5 names and tilt
  rundeckapp/grails-spa/packages/ui-trellis/src/library/utilities/RundeckVersion.ts
Labels: release-notes/exclude, auto-backport, backport-to-release/5.0.x
