Repository rundeck/rundeck, pull requests merged in 2023-06, with the labels that each got.

#8362 RUN-1771: upgrade libraries azure-object-store-plugin
  plugins/azure-object-store-plugin/build.gradle
Labels: to-jira

#8370 RUN-1782: Support local assets in UI plugins by using asset: prefix
  rundeckapp/grails-app/views/layouts/base.gsp
Labels: to-jira

#8379 RUN-1537: upgrade oss plugins
  build.yaml
Labels: needs-backport, backport release/4.14.x

#8383 RUN-1762: Fix notifications not triggering
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Labels: needs-backport, backport release/4.14.x

#8382 RSE-522: import status not consistant in cluster after importing jobs through gui
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
Labels: backport release/4.14.x

#8388 RUN-1791: Fix references to ctxProject.
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/views/feed/_jobreportItem.gsp
  rundeckapp/grails-app/views/feed/index.gsp
  rundeckapp/grails-app/views/reports/_baseReport.gsp
Labels: needs-backport, 4.x, backport release/4.14.x

#8380 RUN-1765: BaseReport migration
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/BaseReport.groovy
  rundeckapp/grails-app/migrations/core/BaseReportSpi.groovy
Labels: needs-backport, release-notes/exclude, 4.x, backport release/4.14.x

#8389 RUN-1800: Upgrade to spring boot 2.7.12
  gradle.properties
Labels: needs-backport, backport release/4.14.x

#8322 RSE-326: Fix: Error responses including stacktraces
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  docker/official/remco/templates/rundeck-config-features.properties
  rundeckapp/grails-app/controllers/rundeck/interceptors/InternalErrorsInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/InternalErrorsInterceptorSpec.groovy
Labels: needs documentation

#8251 RCLOUD-856: Move LogFileStorageRequest to data spi
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/logstorage/RdLogFileStorageRequest.groovy
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/ExecutionData.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/logstorage/LogFileStorageRequestData.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/logstorage/LogFileStorageRequestProvider.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/logstorage/dto/CompletedStatusLogFileStorageResponse.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/logstorage/dto/DuplicateLogFileStorageResponse.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
Labels: 4.x

#8402 Fixes an incorrect method param name in the GormLogFileStorageProvider.
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#8387 RUN-1797: fix: authz checks for project type annotations
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/domain/projectType/AppAuthorizingProjectType.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/authorization/domain/projectType/AppProjectTypeAuthorizingProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/authorization/domain/projectType/AppAuthorizingProjectTypeSpec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/authorization/domain/projectType/AppProjectTypeAuthorizingProviderSpec.groovy
Labels: to-jira

#8405 RUN-1815: Update Job definition manager interface
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java
  core/src/main/java/org/rundeck/app/components/jobs/JobDefinitionManager.java
  rundeckapp/src/main/groovy/org/rundeck/app/components/RundeckJobDefinitionManager.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormJobDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: release-notes/exclude, to-jira

#8347 RSE-430 Fix: HTTP Strict Transport Security (HSTS) Header Not Used
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletHstsCustomizer.groovy
  rundeckapp/src/test/groovy/rundeckapp/init/servlet/JettyServletHstsCustomizerSpec.groovy
Labels: needs documentation

#8412 RUN-1814: fix: typescript build errors
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/modules/filterPrefs.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/rundeckService.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NavBar.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/UtilityBar.ts
Labels: release-notes/exclude
