Repository rundeck/rundeck, pull requests merged in 2023-04, with the labels that each got.

#8217 RUN-1615: Invalidate user sessions upon password change/reset
  rundeckapp/grails-app/conf/spring/resources.groovy
Labels: 4.x

#8191 RUN-759: Convert Key Storage to Vue
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/i18n.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/KeyStorageSelector.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/InputType.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageEdit.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStoragePage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyType.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_utilities.scss
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
Labels: 4.x

#8230 RUN-1646: Always use chromedriver latest in selenium tests
  test/selenium/.gitignore
  test/selenium/.npmrc
Labels: release-notes/exclude, to-jira, 4.x

#8224 RUN-1619: Add JSON Path Option to Remote URL Option Input
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: to-jira, 4.x

#8233 More testdeck chromedriver update
  test/selenium/package.json
  test/testdeck/.gitignore
  test/testdeck/.npmrc
  test/testdeck/package.json
Labels: release-notes/exclude, 4.x

#8234 fix json-smart duplicate dependency
  rundeckapp/build.gradle
Labels: release-notes/exclude, 4.x

#8228 RUN-1629: Upgrade core libraries for CVE-2023-20861
  core/build.gradle
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpIntegrationSpec.groovy
Labels: 4.x

#8221 RUN-1616: Set Cookie SemeSite Flag To Strict
  rundeckapp/grails-app/conf/application.yml
Labels: 4.x

#8149 Adding PluginMeta spi
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/pluginMeta/RdPluginMeta.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/PluginMetaDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/domain/rundeck/PluginMeta.groovy
  rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormPluginMetaDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobMetadataServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#8239 RUN-1657:Fix KeyStorageUpload vue typo
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Labels: 4.x, backport release/4.12.x

#8243 RUN-1663: SameSite configuration incorrect indent
  rundeckapp/grails-app/conf/application.yml
Labels: 4.x, backport release/4.12.x

#8245 RUN 1655 | Schedules Page is not Being Displayed
  rundeckapp/grails-app/views/layouts/base.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/schedule/ScheduleEditor.vue
Labels: 4.x, backport release/4.12.x

#8247 RUN-1664: Job option Json Path Filter can’t be deleted
  rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Labels: 4.x, backport release/4.12.x

#8242 RUN-1666: fix import when configRemoteUrl is set
  rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy
  rundeckapp/src/test/groovy/rundeck/OptionSpec.groovy
Labels: 4.x, backport release/4.12.x

#8244 RUN-1665: Remote URL doesn't work with Json Path Filter
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 4.x, backport release/4.12.x

#8252 RUN-1676: 4.12.0-rc2: disable defer for ui plugins
  rundeckapp/grails-app/views/layouts/base.gsp
Labels: 4.x, backport release/4.12.x

#8257 RUN-1684: Revert storage.gsp
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/KeyStorageSelector.vue
Labels: 4.x, backport release/4.12.x

#8263 Update version to 4.13.0-SNAPSHOT
  gradle.properties
  version.properties
Labels: release-notes/exclude, 4.x

#8270 RUN-1692: Upgrade spring-core CVE-2023-20863
  gradle.properties
Labels: 4.x

#8232 RSE-328 Fix: NPE Job Retry with No Failed Nodes
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Labels: 4.x

#8266 RUN-1691: pass configuration values to the runner when plugins use @PluginProperty annotations
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapterSpec.groovy
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
Labels: 4.x

#8240 RUN-1654: fix: remove duplicated UISocket.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/ResourcesEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/ui/UiSocket.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/ui/main.ts
Labels: 4.x

#8271 RUN-1693: job UI socket
  rundeckapp/grails-app/views/menu/_jobslist.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/UiSocket.vue
Labels: 4.x

#8264 RSE-183 Fix: Misplaced SCM Tooltip on Job Show
  rundeckapp/grails-app/views/scm/_statusBadge.gsp
Labels: 4.x

#8169 RSE-335: Fix: Enable schedules from project settings don't work as expected in clustermode
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: 4.x

#8170 RSE-254: Enh: add multiple node wizard sources
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Property.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyUtil.java
  core/src/main/java/com/dtolabs/rundeck/plugins/util/PropertyBuilder.java
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/ProjectPluginConfig.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue
Labels: 4.x

#8280 RSE-324 Fix: Updated vue-moment dependency to latest moment version
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
Labels: 4.x

#8282 RUN-1700: Keystorage selenium tests
  test/selenium/src/__tests__/selenium/key-storage-test.ts
  test/selenium/src/pages/keyStorage.page.ts
Labels: 4.x

#8281 RUN-1642: Plugins that default to Local Runner execution
  core/src/main/java/com/dtolabs/rundeck/plugins/ExecutionEnvironmentConstants.java
  plugins/flow-control-plugin/src/main/java/org/rundeck/plugin/flowcontrol/FlowControlWorkflowStep.java
  plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java
  plugins/source-refresh-plugin/src/main/java/org/rundeck/plugin/nodes/NodeRefreshWorkflowStep.java
  plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/LogDataStep.java
  plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/StubDataNodeStep.java
  plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/StubDataStep.java
  plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java
Labels: 4.x

#8287 Add workflow to create a release from pushed tag
  .github/workflows/release.yml
Labels: 4.x

#8286 Added unit test for RSE-335
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#8289 remove release branch trigger
  .github/workflows/release.yml
Labels: release-notes/exclude, 4.x
