Repository rundeck/rundeck, pull requests merged in 2023-10, with the labels that each got.

#8560 RUN-1974: Disable resource model runner selector for only local plugins
  core/src/main/java/com/dtolabs/rundeck/core/resources/LocalResourceModelSource.java
Labels: auto-backport, backport-to-release/4.17.x

#8589 RUN-2005: fix log viewer progress bar
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Labels: to-jira, auto-backport, backport-to-release/4.17.x

#8595 RUN-2008: runner name
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Labels: auto-backport, backport-to-release/4.17.x

#8594 RCLOUD-1064: Add ability to create ExecReport using an Execution uuid
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/ExecReportDataProvider.java
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
Labels: release-notes/exclude

#8599 Move DataValidationException and response class to shared plugin
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/ValidationResponse.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/exception/DataValidationException.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/RdExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/RdJobController.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecutionDataProvider.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/RdExecutionControllerSpec.groovy
Labels: release-notes/exclude

#8600 RCLOUD-1068: Add ability to trigger job notification using an event
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/notification/SendNotificationEvent.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: release-notes/exclude

#8605 RCLOUD-1069: Allow quartz job type to be supplied by a bean.
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/quartz/QuartzJobSpecifier.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/quartz/ExecutionJobQuartzJobSpecifier.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: release-notes/exclude

#8597 The ScheduleExecution to JobData converter was broken when attempting to convert job options
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdOption.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionToJobConverter.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionToJobConverterSpec.groovy
Labels: release-notes/exclude

#8614 RUN-2020: Upgrade Jetty due CVE-2023-36478
  gradle.properties
  testbuild.groovy
Labels: backport-to-release/4.17.x

#8609 RUN-2015: Fix: flickering execution log view
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Labels: to-jira, auto-backport, backport-to-release/4.17.x

#8613 RCLOUD-1070: Add createExecution method with alternate parameters
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
Labels: release-notes/exclude

#8608 RCLOUD-1070: Update option processing
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/OptionsParserUtil.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/OptionsUtilTests.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
  rundeckapp/src/test/groovy/rundeck/FrameworkServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/OptionsParserUtilsSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/OptionsParserUtilsTests.groovy
Labels: release-notes/exclude

#8618 RUN-2024: avoid NPE if UserGroupSourcePlugin returns a null entry
  rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
  rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/UserService.groovy
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Labels: auto-backport, backport-to-release/4.17.x

#8607 RUN-1967: Fix Project Component Export
  rundeckapp/grails-app/views/menu/_projectExportForm.gsp
Labels: auto-backport, backport-to-release/4.17.x

#8635 RUN-2031: remove AVERAGE_DURATION_EXCEEDED execution status
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Labels: auto-backport, backport-to-release/4.17.x

#8621 RUN-2025: Update snakeyaml usage to be forward compatible with snakeyaml 2.0
  core/src/main/java/com/dtolabs/rundeck/core/common/NodesYamlParser.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java
  core/src/test/java/com/dtolabs/rundeck/core/common/TestNodesYamlGenerator.java
  rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/yaml/model/YamlPolicyDocConstructor.java
Labels: auto-backport, backport-to-release/4.17.x

#8624 RUN-2019: project config plugin validation issue from API request
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Labels: auto-backport, backport-to-release/4.17.x

#8630 RUN-2023 fix getCaretPos
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/schedule/ScheduleEditor.vue
Labels: auto-backport, backport-to-release/4.17.x

#8644 RUN-1987: upgrade ansible plugin to 3.2.8
  build.yaml
Labels: auto-backport, backport-to-release/4.17.x

#8350 RUN-459: add interfaces for system configuration
  core/src/main/java/com/dtolabs/rundeck/core/config/FeatureService.java
  rundeck-app-util/src/main/java/org/rundeck/app/config/ConfigService.java
  rundeck-app-util/src/main/java/org/rundeck/app/config/SysConfigProp.java
  rundeck-app-util/src/main/java/org/rundeck/app/config/SystemConfig.java
  rundeck-app-util/src/main/java/org/rundeck/app/config/SystemConfigurable.java
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/grails-app/services/rundeck/services/NodeService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
  rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/feature/FeatureServiceSpec.groovy
Labels: release-notes/exclude

#8655 restore getConfig method
  rundeck-app-util/src/main/java/org/rundeck/app/config/ConfigService.java
  rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
Labels: release-notes/exclude
