Repository rundeck/rundeck, pull requests merged in 2023-05, with the labels that each got.

#8297 RUN-1706: Upgrade spring-security to 5.8.3
  gradle.properties
Labels: 4.x

#8284 RUN-1701: key storage vue conversion
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/views/menu/storage.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/i18n.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/KeyStorageSelector.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageEdit.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStoragePage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Labels: 4.x

#8294 RUN-1576: PluginGroups Feature Flag Defaults to true
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: 4.x

#8291 RUN-1625: Select Runner For Adhoc Command
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/views/framework/adhoc.gsp
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiRunAdhocRequest.groovy
  test/selenium/src/pages/adhocCommand.page.ts
Labels: 4.x

#8299 Bump SNAPSHOT version to 4.14.0
  gradle.properties
  version.properties
Labels: 4.x

#8301 RUN-1709: Sets SameSite cookie policy to Lax as default to allow OAuth2 SSO flows
  rundeckapp/grails-app/conf/application.yml
Labels: 4.x, backport release/4.12.x, backport release/4.13.x

#8307 RUN-1725: Update to jackson 2.15.0
  gradle.properties
Labels: to-jira, 4.x, backport release/4.13.x

#8312 RUN-1727: Correct loading indicator text
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Labels: 4.x, backport release/4.13.x

#8231 RUN-1647: Remove mergify
  .mergify.yml
Labels: to-jira, 4.x

#8196 RUN-437: Add OpenAPI Spec annotations
  .circleci/config.yml
  build.gradle
  gradle.properties
  gradle/grailsopenapispec.gradle
  grails-execution-mode-timer/build.gradle
  grails-execution-mode-timer/grails-app/controllers/com/rundeck/plugin/EditProjectController.groovy
  grails-execution-mode-timer/grails-app/controllers/com/rundeck/plugin/ExecutionModeController.groovy
  grails-execution-mode-timer/src/main/groovy/com/rundeck/plugin/api/model/ModeLaterRequest.groovy
  grails-execution-mode-timer/src/main/groovy/com/rundeck/plugin/api/model/ModeLaterResponse.groovy
  grails-execution-mode-timer/src/main/groovy/com/rundeck/plugin/api/model/ProjectModeLaterRequest.groovy
  grails-webhooks/build.gradle
  grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
  rundeckapp/build.gradle
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiBulkJobDeleteRequest.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/CDataString.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/Paging.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkRequest.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkRequestArray.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkRequestArrayLong.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkRequestLong.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkRequestXml.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/DeleteBulkResponse.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/FailedItem.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/MetricsQueryResponse.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/execution/RequestElement.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/executionmode/ExecutionModeResult.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/jobs/upload/ExecutionFileInfoList.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/jobs/upload/JobFileInfo.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/plugins/ApiPluginListProvider.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/JobReference.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmAction.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmActionInput.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmActionResult.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmExportActionItem.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmImportActionItem.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmPluginInputField.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmProjectPluginConfig.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/scm/ScmProjectStatus.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
Labels: 4.x

#8318 RUN-1733: Fix bootrun and openapi
  build.gradle
  gradle.properties
  gradle/grailsopenapispec.gradle
  grails-execution-mode-timer/build.gradle
  grails-webhooks/build.gradle
  rundeckapp/build.gradle
Labels: release-notes/exclude

#8285 RSE-271 Fix: Successful remote job import from API but getting error in SCM API response
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
Labels: 4.x

#8249 RCLOUD-875: ScheduledExecutionStats to spi
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/RdJobStats.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/dto/StatsContent.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/dto/StatsContentImpl.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/execution/JobStatsDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecutionStats.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
  rundeckapp/grails-app/migrations/core/ScheduledExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/grails-app/views/menu/_runningExecutions.gsp
  rundeckapp/grails-app/views/scheduledExecution/_showStats.gsp
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobStatsDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#8296 RUN-1708: change user summary UI attach to use ui-socket
  rundeckapp/grails-app/views/menu/userSummary.gsp
  rundeckapp/grails-app/views/user/profile.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/menu/main.js
Labels: 4.x

#8237 RCLOUD-869: Move ReferencedExecution to spi
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/Execution.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/execution/RdReferencedExecution.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/execution/ReferencedExecutionDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/grails-app/migrations/core/ReferencedExecution.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp
  rundeckapp/grails-app/views/scheduledExecution/_renderJobStats.gsp
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpIntegrationSpec.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormReferencedExecutionDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ReportsControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionsCleanUpSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: 4.x

#8328 Put webpack copied jquery autocomplete asset in the vendor folder.
  rundeckapp/grails-app/assets/javascripts/_package-manager/mix-manifest.json
  rundeckapp/grails-app/assets/javascripts/_package-manager/webpack.mix.js
  rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
  rundeckapp/grails-app/views/scheduledExecution/show.gsp
Labels: 4.x

#8290 RUN-1704: Cleanup: remove use of static form fields for job notifications input
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/constants/NotificationConstants.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/shared/SharedNotificationConstraints.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/validation/validators/notification/EmailNotificationValidatorSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/execution/_execDetails.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp
  rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: to-jira, 4.x

#8126 RCLOUD-767: move basereport to data spi
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/query/RdExecQuery.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/RdExecReport.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportRequest.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportRequestImpl.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportResponse.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportResponseImpl.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/ExecReportDataProvider.java
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/domain/rundeck/BaseReport.groovy
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/integration-test/groovy/ReportServiceTests.groovy
  rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpIntegrationSpec.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecQuery.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ReportQuery.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/ExecReportSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionsCleanUpSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#8089 RUN-1703: Fix RSS feed servlet
  rundeckapp/grails-app/views/feed/_jobreportItem.gsp
  rundeckapp/grails-app/views/feed/index.gsp
Labels: to-jira, 4.x

#8331 Fix issue with showing referenced execution data in gsp layer
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/execution/ReferencedExecutionDataProvider.java
  rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/job/JobDataProvider.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
  rundeckapp/grails-app/views/scheduledExecution/_jobActionButton.gsp
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobQueryProvider.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormReferencedExecutionDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
Labels: 4.x

#8300 RSE-410 & RSE-418 SCM General Disconnection Issues ☹
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
  core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Labels: 4.x

#8333 When SaveReportRequest builder hits a deprecated field it should not print a stack trace.
  rundeck-data-model/build.gradle
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportRequestImpl.java
  rundeckapp/grails-app/domain/rundeck/BaseReport.groovy
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
Labels: 4.x

#8309 Run 1716 Update extraMetadata before adhoc command execution
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
Labels: 4.x

#8306 RSE-415: Java11 compatibility core
  .circleci/config.yml
  build.gradle
  core/build.gradle
  core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobOptionImpl.java
  examples/example-java-execution-lifecyle-plugin/build.gradle
  examples/example-java-job-lifecycle-plugin/build.gradle
  examples/example-java-logging-plugins/build.gradle
  examples/example-java-nodeexecutor-plugin/build.gradle
  examples/example-java-notification-plugin/build.gradle
  examples/example-java-step-plugin/build.gradle
  examples/example-java-storage-converter-plugin/build.gradle
  examples/example-java-storage-plugin/build.gradle
  examples/json-plugin/build.gradle
  gradle.properties
  gradle/java-version.gradle
  gradle/java.gradle
  grails-execution-mode-timer/build.gradle
  grails-metricsweb/build.gradle
  grails-persistlocale/build.gradle
  grails-repository/build.gradle
  grails-rundeck-data-shared/build.gradle
  grails-securityheaders/build.gradle
  grails-webhooks/build.gradle
  grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
  plugins/audit-logging-plugin/build.gradle
  plugins/azure-object-store-plugin/build.gradle
  plugins/build.gradle
  plugins/copyfile-plugin/build.gradle
  plugins/flow-control-plugin/build.gradle
  plugins/git-plugin/build.gradle
  plugins/jasypt-encryption-plugin/build.gradle
  plugins/job-state-plugin/build.gradle
  plugins/localexec-plugin/build.gradle
  plugins/object-store-plugin/build.gradle
  plugins/orchestrator-plugin/build.gradle
  plugins/script-plugin/build.gradle
  plugins/source-refresh-plugin/build.gradle
  plugins/stub-plugin/build.gradle
  plugins/upvar-plugin/build.gradle
  rundeck-app-util/build.gradle
  rundeck-authz/rundeck-authz-api/build.gradle
  rundeck-authz/rundeck-authz-core/build.gradle
  rundeck-authz/rundeck-authz-yaml/build.gradle
  rundeck-data-model/build.gradle
  rundeck-storage/build.gradle
  rundeckapp/build.gradle
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Labels: 4.x

#8337 RCLOUD-909: BaseReport JobUuid adjustments
  rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/RdExecReport.java
  rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
  rundeckapp/grails-app/migrations/core/BaseReport.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: release-notes/exclude, 4.x

#8308 RUN-1719: convert project node source edit page to Vue
  core/src/main/java/com/dtolabs/rundeck/core/common/NodesYamlGenerator.java
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/test/java/com/dtolabs/rundeck/core/common/TestNodesYamlGenerator.java
  rundeckapp/grails-app/assets/javascripts/application.js
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/views/framework/_legacyEditProjectNodeSourceFile.gsp
  rundeckapp/grails-app/views/framework/editProjectNodeSourceFile.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/nodeSourcesUtil.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-editor/EditProjectNodeSourceFile.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-editor/EditProjectNodeSourcePage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-editor/i18n.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-editor/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/loadJsonData.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditorVue.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/UiSocket.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/modules/tokens.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NodeSourceFile.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/RootStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
  test/api/test-v23-project-source-resources.sh
Labels: 4.x

#8336 RUN-1707 Adhoc Command UI Change To Support Runner Selector
  rundeckapp/grails-app/assets/javascripts/adhocCommandKO.js
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
Labels: 4.x

#8215 RSE-156: Fix/add changeset preconditions
  docker/official/remco/templates/rundeck-config.properties
  gradle.properties
  rundeckapp/build.gradle
  rundeckapp/grails-app/init/rundeckapp/Application.groovy
  rundeckapp/grails-app/migrations/changelog.groovy
  rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
  rundeckapp/grails-app/migrations/core/DBChangelogPrimaryKey.groovy
  rundeckapp/grails-app/migrations/core/ExecReportJcExecIdToExecutionId.groovy
Labels: needs documentation, 4.x
