Repository rundeck/rundeck, pull requests merged in 2024-03, with the labels that each got.

#8964 RUN-2229: Update backport action version
  .github/workflows/backport.yml
Labels: to-jira

#8977 Update CircleCI Remote Docker Image
  .circleci/config.yml
Labels: auto-backport, backport-to-release/4.17.x, backport-to-release/5.1.x

#8988 RSE-1051: Replace api call for fetching execution modes for nodes
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeCard.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/services/nodeServices.ts
Labels: auto-backport, backport-to-release/5.1.x

#8990 RSE-981: Fix for nodes not showing
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/nodeUi.ts
Labels: auto-backport, backport-to-release/5.1.x

#8972 RUN-2227: Remove Twistlock step from CircleCI pipeline
  .circleci/Makefile
  .circleci/README.md
  .circleci/config.yml
  scripts/circleci/helper-functions.sh
  scripts/circleci/setup.sh
  scripts/convert_tl_junit.sh
Labels: release-notes/exclude, to-jira

#8980 Update machine image to avoid using deprecated image
  .circleci/config.yml
Labels: release-notes/exclude, auto-backport, backport-to-release/5.1.x

#9008 RUN-2248: Fix: don't include UI timezone data in schedules json
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/SchedulesEditorSection.vue
Labels: to-jira

#9012 RSE-985: Fix inconsistent Execution class constraints.
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
Labels: auto-backport, backport-to-release/5.1.x

#9020 RCLOUD-1184: cleanup LogFileStorageRequestProvider
  core/build.gradle
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
  rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Labels: release-notes/exclude
