Repository rundeck/rundeck, pull requests merged in 2024-09, with the labels that each got.

#9350 RUN-2766: 5.6.0-rc1: fix script step job definition imported boolean values
  core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilitySpec.groovy
  rundeckapp/grails-app/domain/rundeck/CommandExec.groovy
  rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/RundeckJobDefinitionManagerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/JobsXMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/JobsYAMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
Labels: release-notes/exclude, auto-backport, backport-to-release/5.6.x

#9360 Chore: Update version to 5.7.0-SNAPSHOT
  gradle.properties
  version.properties
Labels: release-notes/exclude

#9365 RUN-2853: Flaky - rundeck: T Selenium > Scheduled job
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
Labels: release-notes/exclude, flaky-tests

#9367 RUN-2854: rundeck: T Selenium > execution succeeds on all nodes matching the ANY filter
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/execution/CommandOnMultipleNodesSpec.groovy
Labels: release-notes/exclude, flaky-tests

#9366 RUN-2847: Flaky - rundeck: T Selenium > disable schedules at project level
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectEditPage.groovy
Labels: release-notes/exclude, flaky-tests
