Repository rundeck/rundeck, pull requests merged in 2024-08, with the labels that each got.

#9257 RUN-2606: Look up execution by id if uuid not in report
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ReportsControllerSpec.groovy
Labels: auto-backport, backport-to-release/5.5.x

#9259 RUN-2606: fix report delete by execution ID
  rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/DBExecReportSupport.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Labels: auto-backport, backport-to-release/5.5.x

#9255 Testdeck improvement scm
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/ConfigureScmPage.groovy
Labels: release-notes/exclude

#9263 RUN-2730: Increase CI speed by splitting functional tests
  .circleci/config.yml
  functional-test/build.gradle
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobTabsSpec.groovy
  scripts/circleci/build-functions.sh
Labels: release-notes/exclude

#9267 RUN-2730: Remove unrequired dependency installation for functional tests
  .circleci/config.yml
Labels: release-notes/exclude

#9266 RUN-2721: Add alphaUi flag
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Labels: release-notes/exclude

#9144 RUN-2267: new local node executor feature flag
  .circleci/config.yml
  core/src/main/java/com/dtolabs/rundeck/core/common/BaseFrameworkExecutionServices.java
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/NewLocalNodeExecutor.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorServiceProfile.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeSpecifiedPlugins.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/utils/ResolverUtil.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowStrategyService.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepExecutionService.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/AbstractProviderRegistryService.java
  core/src/main/java/com/dtolabs/rundeck/core/plugins/IFrameworkProviderRegistryService.java
  core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/service/NodeExecutorServiceSpec.groovy
  functional-test/build.gradle
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionOutputSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/integration/BlocklistSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/ExecutorSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/annotations/APIExecOutputTest.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
  functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
  functional-test/src/test/resources/spock-configs/IncludeAPIExecOutputTestsConfig.groovy
  plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/JschNodeExecutor.java
  plugins/jsch-plugin/src/test/groovy/org/rundeck/plugins/jsch/JschNodeExecutorSpec.groovy
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/FeatureToggleNodeExecutorProfile.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/NodeExecutorServiceFactory.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/RundeckNodeExecutorProfile.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/AppExecutionPluginLoader.groovy
Labels: release-notes/exclude

#9281 RCLOUD-1425: Prevent bootstrap event when starting Rundeck with -m
  rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
  rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
Labels: release-notes/exclude

#9253 RUN-573: Convert execution tab to vue
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/common/ScheduledExecutionDetails.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/common/tests/ScheduledExecutionDetails.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/details/DetailsEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/details/tests/DetailsEditor.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/execution/ExecutionEditor.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/execution/tests/ExecutionEditor.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/execution/tests/mocks.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/execution/types/executionTypes.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/ExecutionEditorSection.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/main.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/PluginDetails.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/PluginInfo.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginPropEdit.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/tests/PluginDetails.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditorVue.vue
Labels: bug-bash

#9271 RUN-2744: follow-up, unit test
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeTable.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/NodeTable.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/mocks/apiData.ts
Labels: auto-backport, backport-to-release/5.5.x

#9296 RCLOUD-1427: Enhance query that returns job data for schedule takeover
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Labels: release-notes/exclude, backport-to-release/5.5.x

#9244 RUN-2769: Readme update java version, copyright
  README.md
Labels: release-notes/exclude, to-jira

#9313 RCLOUD-1427: Use JdbcTemplate instead of Groovy Sql
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Labels: release-notes/exclude

#9316 Manual backport RCLOUD-1427
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Labels: release-notes/exclude

#9229 RUN-2661, RUN-2663: CSS fixes and switch component started
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/InputSwitch.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/inputswitch.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Message/message.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/TabView/tabview.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tag/Tag.stories.ts
Labels: release-notes/exclude

#9297 RUN-2766: fix: imported command/script steps should be plugin steps
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
  rundeckapp/grails-app/domain/rundeck/CommandExec.groovy
  rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
  rundeckapp/grails-app/domain/rundeck/Workflow.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/components/RundeckJobDefinitionManagerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/CommandExecTests.groovy
  rundeckapp/src/test/groovy/rundeck/JobsXMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/JobsXMLCodecTests.groovy
  rundeckapp/src/test/groovy/rundeck/JobsYAMLCodecSpec.groovy
  rundeckapp/src/test/groovy/rundeck/JobsYAMLCodecTests.groovy
  rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
  rundeckapp/src/test/groovy/rundeck/WorkflowTests.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: to-jira

#8822 RUN-2741: Add LDAP rolePagination config option for docker
  docker/official/remco/templates/jaas-loginmodule.conf
Labels: to-jira
