Repository rundeck/rundeck, pull requests merged in 2024-01, with the labels that each got.

#8757 RUN-2110: Minor update for openapi docs
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Labels: to-jira

#8725 RUN-2081: nextUI: job list page: add job filters
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobFilterSaveModal.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobGroupsBreadcrumbs.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobListPage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobPageFiltersPopup.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobSearchModal.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobsPage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobsPageHeader.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tree/Browser.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/JobListFilterStore.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/JobPageStore.ts
Labels: to-jira

#8516 RUN-2124: Update and fix brazillian translation
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
Labels: to-jira

#8791 RSE-937: Fix replace token for command plugin
  core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
  core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/CommandNodeStepPlugin.groovy
Labels: auto-backport, backport-to-release/5.0.x

#8797 RSE-956: fix: step labels unavailable for workflow strategy
  rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
Labels: auto-backport, backport-to-release/5.0.x

#8790 RUN-2132: [Snyk] Security upgrade axios from 1.4.0 to 1.6.4
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
Labels: to-jira

#8651 RSE-734 Fix: Asynchronous Project Import
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportEvents.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportException.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportMilestone.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportService.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportStatusDTO.groovy
  rundeckapp/grails-app/services/rundeck/services/asyncimport/AsyncImportStatusFileOperations.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveParams.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/AsyncImportServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
  rundeckapp/src/test/resources/async-import-sample-project-wo-execs.jar
  rundeckapp/src/test/resources/async-import-sample-project.jar
Labels: needs documentation

#8833 RSE-969 Testdeck Migration: test-job-retry.sh, test-job-run-GET-405.sh, test-job-run-later.sh
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/ResponseModels/Execution.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/ResponseModels/Job.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/api/ExecutionStatus.groovy
  functional-test/src/test/groovy/org/rundeck/util/api/JobUtils.groovy
  functional-test/src/test/groovy/org/rundeck/util/api/WaitingTime.groovy
  functional-test/src/test/resources/realm.properties
Labels: needs refactor

#8835 RUN-2155: job output highlight
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/LogViewerOutput.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/JobCreatePage.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/execution-show/main.js
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue
Labels: auto-backport, backport-to-release/5.1.x

#8836 RUN-2156: don't create a new webhook when already exists in the project
  grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
  rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
Labels: auto-backport, backport-to-release/5.1.x

#8845 RUN-2165: legacyXml feature flag should support defaultEnabled
  rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/src/main/groovy/org/rundeck/web/WebUtil.groovy
Labels: to-jira, auto-backport, backport-to-release/5.0.x, backport-to-release/5.1.x

#8855 RUN-2171: Moving code to the try/catch block in order to show errors in the GUI
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
Labels: auto-backport, backport-to-release/5.1.x

#8792 RUN-2133: UI: activity list spacing and layout fixes
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityFilter.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
Labels: to-jira

#8468 RUN-2125: Remove static UUID from Docker images
  docker/official/etc/framework.properties
Labels: to-jira

#8862 RUN-2179: Keep job definitions created in 5.x working in previous versions
  rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
  rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
  rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
Labels: auto-backport, backport-to-release/5.0.x, backport-to-release/5.1.x
