Repository rundeck/rundeck, pull requests merged in 2024-05, with the labels that each got.

#9062 RSE-864 Fix: Case sensitive in users when used LDAP OSS
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/providers/GormUserDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Labels: needs documentation

#9103 RUN-2326: Fix handling step failures with null message (e.g. cancellation)
  plugins/script-node-step-plugin/build.gradle
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/CommandNodeStepPlugin.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptFileNodeStepExecutor.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptURLNodeStepExecutor.groovy
  plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/Util.groovy
  plugins/script-node-step-plugin/src/test/groovy/org/rundeck/plugin/scriptnodestep/UtilSpec.groovy
Labels: auto-backport, backport-to-release/5.2.x

#9111 Moving BaseNodeFilters and ExtNodeFilters to shared project
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/reference/JobReferenceImpl.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/NodeFiltersUtil.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/support/filters/BaseNodeFilters.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/support/filters/ExtNodeFilters.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/i18n/messages_es_419.properties
  rundeckapp/grails-app/i18n/messages_fr_FR.properties
  rundeckapp/grails-app/i18n/messages_ja.properties
  rundeckapp/grails-app/i18n/messages_pt_BR.properties
  rundeckapp/grails-app/i18n/messages_zh_cn.properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/JobImportReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/JobReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/JobRevReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/JobSerializerReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
  rundeckapp/grails-app/services/rundeck/services/execution/ExecutionReferenceImpl.groovy
  rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionContext.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/schedule/DefaultJobDataChangeDetector.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobDataProvider.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkController2Spec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/JobStateServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/jobs/ResolvedAuthJobServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Labels: release-notes/exclude

#9123 RUN-2369 Login as local user doesn't evaluate case sensitive feature
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
Labels: auto-backport, backport-to-release/5.3.x

#9120 RUN-2453: Feature rundeck.feature.caseInsensitiveUsername.enabled doesn't show on System configuration page
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
Labels: auto-backport, backport-to-release/5.3.x

#8536 RUN-2344: Specify zip aspect for GAV for bundled plugins
  build.yaml
  testbuild.groovy
Labels: release-notes/exclude

#9126 RUN-2483: Cleanup some dependencies
  rundeckapp/build.gradle
Labels: release-notes/exclude, to-jira

#9135 RUN-2491: Delete unused component version-notification
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/version-notification/App.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/version-notification/main.js
Labels: release-notes/exclude, to-jira

#9114 RUN-2354: fix: npe during cleanup incomplete executions
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProviderSpec.groovy
Labels: to-jira

#9152 RUN-2335: QAF migration for multi execution job
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
Labels: release-notes/exclude

#9110 RSE-1052: fix IP disclosure when request doesnt have Host header
  rundeckapp/grails-app/conf/spring/resources.groovy
  rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
  rundeckapp/grails-app/init/rundeckapp/init/servlet/RundeckHostHeaderCustomizer.groovy
Labels: bug-bash

#9141 [RUN-2508] Enables building arm64 Docker images locally
  docker/ubuntu-base/Dockerfile
Labels: to-jira

#9156 Testdeck: increase timeout
  functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
Labels: release-notes/exclude

#9130 RCLOUD-1221: ExecReport adjustments
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/ExecReportUtil.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/WorkflowStepUtil.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/ExecReportUtilSpec.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/WorkflowStepUtilSpec.groovy
  rundeckapp/grails-app/domain/rundeck/CommandExec.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/domain/rundeck/JobExec.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/grails-app/views/execution/show.gsp
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/WorkflowToRdWorkflowConverter.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: release-notes/exclude

#9066 RUN-2308: packaging lib dir removed from packaging submodule
  packaging/lib/deb/etc/init.d/rundeckd
  scripts/circleci/packaging-functions.sh
Labels: release-notes/exclude
