Repository rundeck/rundeck, pull requests merged in 2024-02, with the labels that each got.

#8856 RUN-2172: add compatibility to execute script/runner old runners
  core/src/main/java/com/dtolabs/rundeck/core/common/BaseFrameworkExecutionProviders.java
  core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
  core/src/main/java/com/dtolabs/rundeck/core/common/IExecutionProviders.java
  core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/AppExecutionPluginLoader.groovy
Labels: auto-backport, backport-to-release/5.0.x, backport-to-release/5.1.x

#8868 RUN-2175: fix: legacyXml flag not working
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
  rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
Labels: auto-backport, backport-to-release/5.1.x

#8859 RUN-2173: NPE While Reading Null Default Values for Secure Options
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy
  rundeckapp/grails-app/assets/javascripts/optionEditKO.js
  rundeckapp/grails-app/i18n/messages.properties
  rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
  rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: auto-backport, backport-to-release/5.1.x

#8874 Fix: Plugin config data was not being exported
  rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
  rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
Labels: auto-backport, backport-to-release/5.0.x, backport-to-release/5.1.x

#8826 RSE-903: Rdcli is not working properly updating projects on severals rundeck versions
  core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Labels: auto-backport, backport-to-release/4.17.x, backport-to-release/5.1.x

#8882 RUN-2191: fix: feature flag defaultEnabled doesn't work
  core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
  rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
Labels: auto-backport, backport-to-release/5.0.x, backport-to-release/5.1.x

#8816 RUN-1920: Update eslint, prettier and add eslint-plugin-vuejs-accessibility
  rundeckapp/grails-spa/packages/ui-trellis/.eslintrc.js
  rundeckapp/grails-spa/packages/ui-trellis/.prettierignore
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
Labels: release-notes/exclude

#8906 RUN-2202: [Snyk] Fix for 1 vulnerabilities
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
Labels: to-jira

#8888 RUN-2196: Update API tests harness project import
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ImportSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/AceEditorSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/ProjectListNextUiSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/execution/CommandSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/BasicJobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/navigation/NavigationSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/project/NodesSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/project/ProjectExportSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/project/ProjectsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
  functional-test/src/test/resources/projects-import/SeleniumBasic.zip
  functional-test/src/test/resources/projects-import/SeleniumBasic/rundeck-SeleniumBasic/files/etc/project.properties
  functional-test/src/test/resources/projects-import/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-0088e04a-0db3-4b03-adda-02e8a4baf709.xml
  functional-test/src/test/resources/projects-import/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-b7b68386-3a52-46dc-a28b-1a4bf6ed87de.xml
  functional-test/src/test/resources/projects-import/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-d5b2c2dd-cf59-43ab-9c04-b99cef2bfe3a.xml
  functional-test/src/test/resources/projects-import/TestJobs.zip
  functional-test/src/test/resources/projects-import/TestJobs/rundeck-TestJobs/files/etc/project.properties
  functional-test/src/test/resources/projects-import/TestJobs/rundeck-TestJobs/jobs/job-9b43e4ab-7ff2-4159-9fc7-7437901914f7.xml
  functional-test/src/test/resources/projects-import/TestJobs/rundeck-TestJobs/jobs/job-a04da560-98c7-4e8a-b6d7-5619e2867624.xml
  functional-test/src/test/resources/projects-import/TestJobs/rundeck-TestJobs/webhooks.yaml
  functional-test/src/test/resources/projects-import/archive-test-readme.zip
  functional-test/src/test/resources/projects-import/archive-test-readme/rundeck-monkey/files/motd.md
  functional-test/src/test/resources/projects-import/archive-test-readme/rundeck-monkey/files/readme.md
  functional-test/src/test/resources/projects-import/archive-test.zip
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1295.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1296.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1297.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1298.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1299.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/execution-1300.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1295.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1296.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1297.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1298.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1299.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/output-1300.rdlog
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1295.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1296.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1297.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1298.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1299.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/executions/state-1300.state.json
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/jobs/job-1574a71c-56b8-47ed-8a5e-a52e362cf572.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/jobs/job-6e21cf79-a6c7-46f5-9e30-204762ec3359.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/jobs/job-808b4a49-67db-4576-866e-2ee3e57011b9.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1312.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1313.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1314.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1315.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1316.xml
  functional-test/src/test/resources/projects-import/archive-test/rundeck-monkey/reports/report-1317.xml
  functional-test/src/test/resources/projects-import/resourcesTest.zip
  functional-test/src/test/resources/projects-import/resourcesTest/rundeck-resourcesTest/calendars.yaml
  functional-test/src/test/resources/projects-import/resourcesTest/rundeck-resourcesTest/files/etc/project.properties
  functional-test/src/test/resources/projects-import/resourcesTest/rundeck-resourcesTest/schedules.yaml
  functional-test/src/test/resources/projects-import/resourcesTest/rundeck-resourcesTest/webhooks.yaml
Labels: to-jira

#8923 RUN-2208: cleanup: prettier for pluginConfig
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue
Labels: to-jira

#8814 RUN-2148: UI:Next: jobs list SCM status fixes
  plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
  plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobListScmStatus.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/metadata/JobScmMetadataComponent.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/project/ProjectScmMetadataComponent.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/metadata/JobScmMetadataComponentSpec.groovy
Labels: to-jira

#8905 RUN-2200: Fix old tests
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/containers/tabs/Tabs.test.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/theme-select/ThemeSelect.test.ts
  rundeckapp/grails-spa/packages/ui-trellis/tests/unit/ExecutionOutput.spec.ts
Labels: release-notes/exclude, to-jira

#8929 RUN-2211: Fix: restore class to java core library
  core/src/main/java/com/dtolabs/rundeck/core/utils/SSHAgentProcess.java
  plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/ExtSSHExec.java
  plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/ExtScp.java
  plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/SSHTaskBuilder.java
  plugins/jsch-plugin/src/test/java/org/rundeck/plugins/jsch/net/TestSSHTaskBuilder.java
Labels: auto-backport, backport-to-release/5.1.x

#8914 fixed the vue warning on readme
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/i18n.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/main.ts
Labels: release-notes/exclude

#8957 RUN-2216: Update spring to 5.3.32 because CVE-2024-22243
  gradle.properties
Labels: auto-backport, backport-to-release/5.1.x
