Repository rundeck/rundeck, pull requests merged in 2024-06, with the labels that each got.

#9157 RUN-2308: Use release/5.3.x branch of packaging repo
  .gitmodules
Labels: release-notes/exclude, auto-backport, backport-to-release/5.2.x

#9040 RUN-2525: Update storybook and style components to match continuum
  rundeckapp/grails-spa/packages/ui-trellis/.gitignore
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.js
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.ts
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/preview.js
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/preview.ts
  rundeckapp/grails-spa/packages/ui-trellis/.storybook/storybook.css
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/css/COMPONENT_NAME.mdx.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/css/COMPONENT_NAME.scss.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/css/COMPONENT_NAME.stories.ts.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/wrapper/COMPONENT_NAME.mdx.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/wrapper/COMPONENT_NAME.spec.ts.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/wrapper/COMPONENT_NAME.stories.ts.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/_templates/primevue-generator/wrapper/COMPONENT_NAME.vue.ejs.t
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Badge/Badge.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Badge/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Badge/badge.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Message/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Message/Message.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Message/message.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/ProgressBar/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/ProgressBar/ProgressBar.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/ProgressBar/progressBar.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtButton/PtButton.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtButton/PtButton.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtMessage/PtMessage.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtSteps/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtSteps/PtSteps.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtSteps/PtSteps.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/PtSteps/ptStepTypes.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/TabView/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/TabView/TabView.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/TabView/tabview.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tag/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tag/Tag.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tag/tag.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tooltip/Docs.mdx
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tooltip/Tooltip.stories.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tooltip/tooltip.scss
  rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/tokens.css
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
Labels: release-notes/exclude

#9163 add locator for jobgraph and job dashboard
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobListPage.groovy
Labels: release-notes/exclude

#9146 RUN-2540: Webpack fix for assets urls inside css files
  rundeckapp/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
Labels: release-notes/exclude, to-jira

#9165 RUN-2159: new methods for projectComponent interface
  core/src/main/java/org/rundeck/app/components/project/ProjectComponent.java
  rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
  rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
  rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Labels: release-notes/exclude

#9173 fix flaky tests
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobReferenceSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
Labels: release-notes/exclude

#9169 RUN-2195: change on forecast api to fetch future executions for "run job later"
  rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
  rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/jobs/info/JobInfo.groovy
  rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Labels: needs documentation

#9175 Add stability for tests
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
Labels: release-notes/exclude

#9176 RUN-2566: upgrade ansible version
  build.yaml
Labels: backport-to-release/5.3.x

#9189 RUN-2339: qaf testdeck
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/nodes/NodesPage.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/NodeSourcePage.groovy
Labels: release-notes/exclude

#9171 RUN-2540: Webpack fix - ensure that assets in css still use relative paths
  rundeckapp/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
  rundeckapp/grails-spa/packages/ui-trellis/package.json
  rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
Labels: release-notes/exclude

#9191 RCLOUD-1345: Add jetty jmx metrics
  rundeckapp/build.gradle
  rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
Labels: auto-backport, backport-to-release/5.4.x

#9197 Run 2498: Add File/URL Script Step Functional Tests
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExecuteScriptSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/workflowSteps/FileUrlScriptStepSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
  functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
  functional-test/src/test/resources/docker/compose/oss/executor/jsch-node.yaml
  functional-test/src/test/resources/docker/compose/oss/keys/id_rsa
  functional-test/src/test/resources/docker/compose/oss/keys/id_rsa.pub
  functional-test/src/test/resources/docker/compose/oss/keys/id_rsa_passphrase
  functional-test/src/test/resources/docker/compose/oss/keys/id_rsa_passphrase.pub
  functional-test/src/test/resources/docker/compose/oss/mock-scripts/helloWorld.sh
  functional-test/src/test/resources/docker/compose/oss/node/Dockerfile
  functional-test/src/test/resources/docker/compose/oss/node/init.sh
  functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/files/acls/node-acl.policy
  functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/files/etc/project.properties
  functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/jobs/job-1c496173-f9ec-4991-b93f-4761c2cf947e.xml
  functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/jobs/job-c14c992d-4738-44b8-945e-9349ae487b77.xml
Labels: release-notes/exclude

#9193 RUN-2505 : Functional tests for Key Value Data log filter
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/KeyValueDataLogFilterSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/LogFilterSpec.groovy
Labels: release-notes/exclude
