Repository rundeck/rundeck, pull requests merged in 2024-04, with the labels that each got.

#9035 RUN-2257: upgrade spring-security.version to 5.8.11
  gradle.properties
Labels: auto-backport, backport-to-release/5.2.x

#9042 RUN-2258: Update to Spring 5.3.33 for CVE-2024-22259
  gradle.properties
Labels: auto-backport, backport-to-release/5.2.x

#9045 RUN-2260: Fix: spinner always shown in nextUi jobs list
  functional-test/src/test/groovy/org/rundeck/util/gui/scm/ScmStatusBadge.groovy
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tests/JobScmStatus.spec.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tree/JobScmStatus.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/head/scm/scm-status-badge.ts
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
Labels: auto-backport, backport-to-release/5.2.x

#9058 Fix/selenium2
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
Labels: release-notes/exclude

#9065 RCLOUD-1110: Add models for creating job and execution reference objects.
  core/build.gradle
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/RdExecution.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/reference/ExecutionReferenceImpl.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/reference/JobReferenceImpl.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/reference/JobRevReferenceImpl.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/ExecutionDataUtil.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobDataUtil.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/shared/SharedExecutionConstraints.groovy
  grails-rundeck-data-shared/src/main/groovy/rundeck/events/RdExecutionCompleteEvent.groovy
  grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/ExecutionDataUtilSpec.groovy
  rundeckapp/grails-app/domain/rundeck/Execution.groovy
  rundeckapp/grails-app/services/rundeck/services/ExecutionEventsService.groovy
  rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
  rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
  rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverter.groovy
  rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverterSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/ExecutionEventsServiceSpec.groovy
  rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Labels: release-notes/exclude

#9075 RPL-6: reduce machine resources to its default (medium)
  .circleci/config.yml
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/webhook/WebhooksSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/container/SeleniumBase.groovy
Labels: release-notes/exclude

#9070 RUN-2309: Update tsconfig.build.json to properly recognize jest
  rundeckapp/grails-spa/packages/ui-trellis/tsconfig.build.json
Labels: release-notes/exclude, to-jira

#9079 RUN-2313: Delete unused image files
  test/selenium/__image_snapshots__/create-test-ts-job-has-not-visually-regressed-1-snap.png
  test/selenium/__image_snapshots__/create-test-ts-project-has-not-visually-regressed-1-snap.png
  test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-activity-1-snap.png
  test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-commands-1-snap.png
  test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-jobs-1-snap.png
  test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-nodes-1-snap.png
Labels: release-notes/exclude, to-jira

#9085 RUN-2317: convert plugin blocklist test
  .circleci/config.yml
  docker/official/remco/templates/rundeck-config.properties
  functional-test/build.gradle
  functional-test/src/test/groovy/org/rundeck/tests/functional/integration/BlocklistSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/annotations/BlocklistTest.groovy
  functional-test/src/test/resources/blocklist-test/blocklist.yaml
  functional-test/src/test/resources/docker/compose/oss/docker-compose-blocklist.yml
  functional-test/src/test/resources/spock-configs/IncludeBlocklistTestsConfig.groovy
  test/api/blocklist-missing-plugin-test.sh
  test/api/blocklist-plugin-count-test.sh
  test/api/include.sh
  test/api/rundecklogin.sh
  test/api/testall.sh
  test/docker/common.sh
  test/docker/docker-compose-plugin-blocklist.yaml
  test/docker/dockers/rundeck/Dockerfile
  test/docker/dockers/rundeck/scripts/run-plugin-blocklist-api-tests.sh
  test/docker/test-api-plugin-blocklist.sh
  test/run-docker-plugin-blocklist-test.sh
  test/src/test.sh
Labels: release-notes/exclude, to-jira
