Repository rundeck/rundeck, pull requests merged in 2024-07, with the labels that each got.

#9230 RUN-2672: Fix flaky unit test for `emits update:modelValue when time changes`
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
Labels: to-jira

#9248 Prevents chrome windows to open unnecessarily
  functional-test/src/test/groovy/org/rundeck/util/container/SeleniumBase.groovy
Labels: release-notes/exclude

#9246 RUN-2709: update log4j to 2.17.2
  gradle.properties
  testbuild.groovy
Labels: to-jira

#9249 RUN-537: Fix for group selection on old UI
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
  rundeckapp/grails-app/assets/javascripts/jobedit.js
  rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/details/DetailsEditor.vue
Labels: auto-backport, backport-to-release/5.5.x
