Repository rundeck/rundeck, pull requests merged in 2024-10, with the labels that each got.

#9384 RUN-2879: Bump node to 18.20.4 on build and circleCi + update node orb to latest version
  .circleci/config.yml
  .nvmrc
  gradle.properties
  rundeckapp/grails-spa/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/build.gradle
  test/.nvmrc
Labels: release-notes/exclude

#9376 RUN-2864 : Update `object-store-plugin` dependencies to prevent CVE-2021-0341
  plugins/object-store-plugin/build.gradle
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/ObjectStorePlugin.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreDirectAccessDirectorySource.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreMemoryDirectorySource.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/stream/CloseAfterCopyStream.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/stream/LazyAccessObjectStoreInputStream.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTree.groovy
  plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreUtils.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreDirectAccessDirectorySourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreMemoryDirectorySourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithDirectAccessDirSourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithMemoryDirSourceTest.groovy
  plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/TimeoutTest.groovy
  plugins/object-store-plugin/src/test/groovy/testhelpers/MinioContainer.groovy
  plugins/object-store-plugin/src/test/groovy/testhelpers/MinioTestUtils.groovy
Labels: bug-bash

#9385 RUN-2879: Simplifies node versioning
  .circleci/config.yml
  gradle.properties
  rundeckapp/grails-spa/build.gradle
  rundeckapp/grails-spa/packages/ui-trellis/build.gradle
Labels: release-notes/exclude

#9393 RCLOUD-1489: Add ability to load required role from spring bean
  core/src/main/java/org/rundeck/app/auth/RequiredRoleProvider.java
  rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Labels: release-notes/exclude

#9390 RUN-2865: Fix: scheduled jobs stop running
  rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
  rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Labels: backport-to-release/5.6.x

#9335 RUN-2620: selenium job definition view tests
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/DuplicateJobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobSummarySpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
  functional-test/src/test/resources/test-files/jobWithOptions.xml
Labels: release-notes/exclude

#9399 Functional Test improvement: validate job import response
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecExportSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionOnMultipleNodesSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/input/SecureInputSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExecuteScriptSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/schedule/ScheduleSpec.groovy
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
Labels: release-notes/exclude

#9405 RUN-2885: add english to the dictionary of available languages so that fallback behaviour works correctly (follow-up)
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/i18n.ts
Labels: release-notes/exclude

#9413 RUN-2889: Cache Node Installs
  .circleci/config.yml
Labels: release-notes/exclude
