Repository rundeck/rundeck, pull requests merged in 2025-06, with the labels that each got.

#9637 RUN-3397: fix max param for activity page
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/activity/ActivitySpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/pages/activity/ActivityPage.groovy
  rundeckapp/grails-app/views/reports/index.gsp
Labels: to-jira

#9694 RUN-3329: Migrate to central portal
  build.gradle
Labels: release-notes/exclude, auto-backport, backport-to-release/5.13.x

#9666 RUN-3452: fix: flaky test when a JSON parse error occurs
  functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
Labels: release-notes/exclude

#9692 RUN-3335 Restart api call should be disabled if user have AppAdmin
  rundeckapp/grails-app/controllers/rundeck/interceptors/PostApiTokenInterceptor.groovy
  rundeckapp/src/test/groovy/rundeck/interceptors/PostApiTokenInterceptorSpec.groovy
Labels: release-notes/exclude

#9681 RUN-3491: add single retry with page refresh to scm test
  functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/scm/ScmStatusBadgeSpec.groovy
  functional-test/src/test/groovy/org/rundeck/util/gui/scm/ScmStatusBadge.groovy
Labels: release-notes/exclude
