Repository rundeck/rundeck, pull requests merged in 2025-07, with the labels that each got.

#9685 RUN-3508: Update setversion.sh
  setversion.sh
Labels: release-notes/exclude

#9717 RUN-3575: escaping chars for unix, ps and cmd
  core/src/main/java/com/dtolabs/rundeck/core/cli/CLIUtils.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArgList.java
  core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
  core/src/test/groovy/com/dtolabs/rundeck/core/cli/CLIUtilsSpec.groovy
  core/src/test/java/com/dtolabs/rundeck/core/cli/TestCLIUtils.java
  core/src/test/java/com/dtolabs/rundeck/core/execution/ExecArgListTest.java
Labels: needs documentation

#9713 RUN-3680: Job editor card header section in vue
  rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp
  rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/DetailsEditorSection.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/HeaderSection.vue
  rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/main.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/es_419.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/fr_FR.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/ja_JP.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/pt_BR.js
  rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/zh_CN.js
Labels: to-jira
